import { chromium, CHROMIUM, MAQUETTE, capture } from './env.mjs';
const nav = await chromium.launch({ executablePath: CHROMIUM, args: ['--no-sandbox','--allow-file-access-from-files'], headless: true });
const ctx = await nav.newContext({ viewport: { width: 1536, height: 864 } }); const page = await ctx.newPage(); const errs = []; page.on('pageerror', e => { errs.push(e.message); console.log('ERREUR JS :', e.message, (e.stack||'').split('\n')[1]); });
const D = []; const p = ms => page.waitForTimeout(ms); const ok = (c, m) => { if (!c) D.push(m); }; const ev = (f, a) => page.evaluate(f, a);
await page.goto(MAQUETTE); await p(600); const jCh = await ev(() => J.filter(x => x.type === 'diapo' || x.type === 'devoile').length); await page.click('#edt-cases [data-atelier="1"]'); await p(500); await p(100); /* la diapo 1 : un bloc de six étapes ; « + bloc » en ajoute un second pour monter / descendre */
// 1. un clic dans une étape, on tape : le texte change dans la diapo ET dans la trame ; le bloc est marqué en édition, la barre du bloc apparaît ; le témoin passe en « modification en cours » puis « enregistré »
const li1 = '#mur li[data-p="0.0"]'; ok(await ev(() => document.querySelectorAll('#mur [data-p][contenteditable]').length >= 4), 'les éléments de la diapo ne sont pas éditables dans l\'atelier');
await page.click(li1); await p(200); ok(await ev(() => !!document.querySelector('#mur .bloc-edit') && !!document.querySelector('#mur .bloc-barre') && /BLOC 1/.test(document.querySelector('#mur .bloc-barre .nom').textContent)), 'le clic dans une étape ne marque pas le bloc en édition avec sa barre');
await page.keyboard.press('End'); await page.keyboard.type(' et je souligne ce qui m\'étonne'); await p(300);
const t1 = await ev(() => ({ dom: document.querySelector('#mur li[data-p="0.0"]').textContent, trame: ecran().blocs[0].el[0], save: document.getElementById('at-save').textContent, dirty: !!S.atelierDirty, journal: J.some(x => x.type === 'atelier-modif') }));
ok(/et je souligne ce qui m'étonne$/.test(t1.dom) && t1.trame === t1.dom && /modification en cours/.test(t1.save) && t1.dirty && t1.journal, 'la frappe n\'écrit pas dans la trame (ou le témoin ne bouge pas) : ' + JSON.stringify(t1).slice(0, 200));
await p(4500); ok(await ev(() => /✔ enregistré/.test(document.getElementById('at-save').textContent) && !S.atelierDirty && J.some(x => x.type === 'atelier-enregistre')), 'l\'enregistrement automatique n\'a pas eu lieu après 4,5 s : ' + (await ev(() => document.getElementById('at-save').textContent)));
// le tableau et le journal ne voient rien ; le rendu du pilotage lit la trame modifiée (identité stable)
ok((await ev(() => J.filter(x => x.type === 'diapo' || x.type === 'devoile').length)) === jCh, 'l\'écriture a écrit des diapos vues ou des dévoilements au journal');
// 2. Tab passe à l'élément suivant, Maj + Tab au précédent
await page.keyboard.press('Tab'); await p(150); ok(await ev(() => document.activeElement.dataset.p === '0.1'), 'Tab ne passe pas à l\'élément suivant : ' + (await ev(() => document.activeElement.dataset.p)));
await page.keyboard.press('Shift+Tab'); await p(150); ok(await ev(() => document.activeElement.dataset.p === '0.0'), 'Maj + Tab ne revient pas à l\'élément précédent');
// 3. Entrée en fin de ligne crée un élément après, vide, avec son invite ; on tape ; Échap sur une ligne vide l'annule
const n0 = await ev(() => ecran().blocs[0].el.length); await page.keyboard.press('End'); await page.keyboard.press('Enter'); await p(300);
ok(await ev(n0 => ecran().blocs[0].el.length === n0 + 1 && ecran().blocs[0].el[1] === '' && document.activeElement.dataset.p === '0.1' && document.activeElement.hasAttribute('data-vide'), n0), 'Entrée ne crée pas un élément vide après, avec le curseur dedans : ' + (await ev(() => JSON.stringify([ecran().blocs[0].el.length, document.activeElement.dataset.p]))));
await page.keyboard.type('Je compare mes notes avec mon voisin.'); await p(200); ok((await ev(() => ecran().blocs[0].el[1])) === 'Je compare mes notes avec mon voisin.', 'la nouvelle étape n\'est pas écrite dans la trame');
await page.keyboard.press('Enter'); await p(300); await page.keyboard.press('Escape'); await p(300); ok(await ev(n0 => ecran().blocs[0].el.length === n0 + 1 && document.activeElement.dataset.p === '0.1', n0), 'Échap sur une ligne vide ne l\'annule pas (ou ne remonte pas)');
// 4. la barre du bloc : ▼ descend le bloc ; ▲ le remonte ; + étape ajoute à la fin ; ✕ demande confirmation si des réponses y sont accrochées
await page.click('#at-bloc'); await p(300); await page.click('.choix-obj .c[data-t="consigne"]'); await p(400); ok(await ev(() => ecran().blocs.length === 2 && ecran().blocs[1].txt === 'Nouvelle consigne' && document.activeElement.dataset.p === '1.t'), '« + bloc » n\'ajoute pas un bloc avec le curseur dans son titre : ' + (await ev(() => JSON.stringify([ecran().blocs.length, document.activeElement.dataset.p]))));
await page.keyboard.type(' — bilan'); await p(200); ok((await ev(() => ecran().blocs[1].txt)) === 'Nouvelle consigne — bilan', 'le titre du bloc ne s\'écrit pas dans la trame');
const ordre0 = await ev(() => ecran().blocs.map(b => b.bid)); await page.click('#mur .bloc-barre [data-bb="haut"]'); await p(300); const ordre1 = await ev(() => ecran().blocs.map(b => b.bid)); ok(ordre1[0] === ordre0[1] && ordre1[1] === ordre0[0], '▲ ne remonte pas le bloc : ' + ordre0 + ' → ' + ordre1);
ok(await ev(() => (document.activeElement.dataset.p || '').startsWith('0.')), 'après ▲, le curseur n\'est pas dans le bloc déplacé : ' + (await ev(() => document.activeElement.dataset.p))); await page.keyboard.press('Alt+ArrowDown'); await p(300); ok((await ev(() => ecran().blocs.map(b => b.bid))).join() === ordre0.join(), 'Alt + ↓ ne redescend pas le bloc : ' + (await ev(() => JSON.stringify([ecran().blocs.map(b => b.bid), document.activeElement && document.activeElement.dataset.p]))) + ' attendu ' + ordre0);
await page.click('#mur [data-p="1.t"]'); await p(200); const n1 = await ev(() => ecran().blocs[1].el.length); await page.click('#mur .bloc-barre [data-bb="etape"]'); await p(300); ok(await ev(n1 => ecran().blocs[1].el.length === n1 + 1 && document.activeElement.dataset.p === '1.' + n1, n1), '« + étape » n\'ajoute pas un élément à la fin du bloc avec le curseur dedans');
await page.keyboard.press('Escape'); await p(200);
// ✕ : sans réponses accrochées → supprimé sans question ; avec réponses → confirmation (refusée ici)
page.once('dialog', d => d.dismiss()); await ev(() => { const st = parDiapo[K(S.di)] || (parDiapo[K(S.di)] = { textes: {}, reps: {}, tailles: {} }); st.reps = st.reps || {}; st.reps[1] = [{ i: 'GA', r: 'une réponse', eleve: 'Gatien' }]; }); const nb0 = await ev(() => ecran().blocs.length); await page.click('#mur li[data-p="1.0"]'); await p(200); await page.click('#mur .bloc-barre [data-bb="suppr"]'); await p(400); ok((await ev(() => ecran().blocs.length)) === nb0, 'le bloc avec des réponses accrochées est supprimé sans confirmation');
await ev(() => { parDiapo[K(S.di)].reps = {}; }); await page.click('#mur li[data-p="1.0"]'); await p(200); await page.click('#mur .bloc-barre [data-bb="suppr"]'); await p(400); ok((await ev(() => ecran().blocs.length)) === nb0 - 1 && (await ev(() => J.some(x => x.type === 'atelier-modif' && x.supprime === 1))), '✕ ne supprime pas le bloc sans réponses');
// 4 bis. le piège du morph : après un changement de diapo dans la colonne, Entrée crée l'élément dans LA diapo ouverte, pas dans la précédente
await page.click('#volet .at-chap .d[data-at-di="6"]'); await p(400); const n6 = await ev(() => seance().ecrans[6].blocs[0].el.length); const n0b = await ev(() => seance().ecrans[0].blocs[0].el.length); await page.click('#mur li[data-p="0.1"]'); await p(200); await page.keyboard.press('End'); await page.keyboard.press('Enter'); await p(400); ok(await ev(([n6, n0b]) => seance().ecrans[6].blocs[0].el.length === n6 + 1 && seance().ecrans[0].blocs[0].el.length === n0b && document.activeElement.dataset.p === '0.2', [n6, n0b]), 'après un changement de diapo, Entrée écrit dans la mauvaise diapo (le nœud réutilisé par le morph gardait l\'ancienne)');
await page.keyboard.press('Escape'); await p(300); await page.click('#volet .at-chap .d[data-at-di="0"]'); await p(400);
// 5. le pilotage lit la trame modifiée (la classe verra le texte écrit) ; l'aide se ferme
ok(await ev(() => !!document.getElementById('at-aide')), 'l\'aide manque'); await page.click('#at-aide .x'); await p(100); ok(await ev(() => !document.getElementById('at-aide')), 'l\'aide ne se ferme pas');
await page.click('#ong-pilotage'); await p(300); ok(await ev(() => /et je souligne ce qui m'étonne/.test(document.getElementById('mur').textContent)), 'le pilotage ne lit pas la trame modifiée dans l\'atelier : ' + (await ev(() => JSON.stringify([ecran().blocs.map(b => b.txt.slice(0, 20) + '/' + (b.el || []).length), (ecran().blocs[0].el || [])[0]]))));
if (errs.length) D.push('erreurs JS : ' + JSON.stringify(errs)); console.log(D.length ? D.join('\n') : 'aucun défaut'); console.log('--- fin :', D.length, 'défaut(s)'); await nav.close();
