p='vis/v9c14a-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:70])
    s = s.replace(a, b, n)
rep("const $ = id => document.getElementById(id);", r"""const $ = id => document.getElementById(id);
(function normaliserTrame(){ /* (a) cadrage 4 · 2.6 : chaque heure se termine par une diapo de rôle « fin » ; si la trame ne l'a pas, elle est ajoutée et dite */ DATA.seances.forEach((sce, si) => { const heures = [...new Set(sce.ecrans.map(e => e.heure))].sort(); heures.forEach(h => { if (sce.ecrans.some(e => e.heure === h && e.role === 'fin')) return; let last = -1; sce.ecrans.forEach((e, i) => { if (e.heure === h) last = i; }); sce.ecrans.splice(last + 1, 0, { eid: 'fin-s' + si + '-h' + h, act: 'Cahier de textes', role: 'fin', heure: h, dur: 5, blocs: [{ t: 'cahier' }], ajouteeALImport: true }); }); }); })();""")
rep("function ordreHeureCalc(h){ const E = seance().ecrans; const idx = E.map((e, i) => i); const glisse = (e, i) => { co","function ordreHeureCalc0(h){ const E = seance().ecrans; const idx = E.map((e, i) => i); const glisse = (e, i) => { if (e.role === 'fin') return false; co")
rep("function ordreHeureCalc0(h){","function ordreHeureCalc(h){ const o0 = ordreHeureCalc0(h); const E = seance().ecrans; const fins = o0.filter(i => E[i].role === 'fin'); return o0.filter(i => E[i].role !== 'fin').concat(fins); } /* (a) le rôle fin est toujours en dernier */\nfunction ordreHeureCalc0(h){")
rep("function elements(e){ const out = []; e.blocs.forEach((b, bi) => (b.el || []).forEach((t, ei) => out.push({ b: bi, e: ei, txt: t, t: b.t }))); return out; }", r"""function elements(e){ const out = []; e.blocs.forEach((b, bi) => { if (b.t === 'cahier') { ['l\'échéance', 'le travail à faire', 'le contenu de la séance', 'qui a participé'].forEach((t, ei) => out.push({ b: bi, e: ei, txt: t, t: 'cahier' })); return; } (b.el || []).forEach((t, ei) => out.push({ b: bi, e: ei, txt: t, t: b.t })); }); return out; }""")
rep("finHeure: S.enFin && !S.close ? (() => {","cahier: (e.role === 'fin') ? (() => {")
a=s.index("  if (et.finHeure) {"); b=s.index("  if (et.attente) h = `<div class=\"attente\">"); s=s[:a]+s[b:]
rendu = r"""  else if (b0 && b0.t === 'cahier' && et.cahier) { const f = et.cahier; const nd = et.nDev || 0; const cel = (k, inner) => (!et.pilote && k >= nd) ? '' : `<div class="cel${k >= nd ? ' pas' : ''}${et.flash === k ? ' spot-on' : ''}" data-k="${k}" data-p="0.c.${k}">${inner}</div>`;
    h += `<div class="corpsd ecran"><span class="act">Cahier de textes — ${esc(f.jour)}, ${esc(f.de)} – ${esc(f.a)}</span>` + `<div class="ed-agenda"><div class="ed-bandeau"><span class="ed-logo">MON ESPACE<br>ÉLÈVE</span><span class="ed-etab">Collège Saint-Joseph</span></div><div class="ed-corps"><div class="ed-titre">Cahier de textes <span class="ed-classe">(3 ${esc(DATA.classe.nom.replace(/^3E /, ''))})</span></div>`
      + cel(0, `<div class="ed-date">PRENEZ VOS AGENDAS — POUR ${esc(f.date).toUpperCase()}</div>`)
      + `<div class="ed-onglets"><span class="${f.onglet === 'contenu' ? '' : 'on'}"${et.pilote ? ' data-onglet="travail" title="Montre le travail à faire"' : ''}>Travail à faire</span><span class="${f.onglet === 'contenu' ? 'on' : ''}${nd < 3 ? ' voile' : ''}"${et.pilote && nd >= 3 ? ' data-onglet="contenu" title="Montre le contenu de la séance (le récit)"' : ''}>Contenus de séances</span></div>`
      + (f.onglet === 'contenu' && nd >= 3
          ? cel(2, `<div class="ed-carte"><div class="ed-matiere">FRANCAIS — contenu de la séance</div><div class="ed-texte ed-recit" data-p="0.r">${f.recit || '<i>rien encore</i>'}</div></div>`)
          : cel(1, `<div class="ed-carte"><div class="ed-matiere">FRANCAIS</div>${f.deja ? `<div class="ed-deja">déjà donné pour cette date (${esc(f.dejaQuand)}) : ${esc(f.deja)}</div>` : ''}<div class="ed-texte"${et.pilote ? ' contenteditable="true" id="ed-edit" title="Écris ici : c\'est ce que les élèves voient, ce qui partira dans École Directe, le récit et l\'historique"' : ''} data-p="0.w">${f.travail ? esc(f.travail).replace(/\n/g, '<br>') : (et.pilote ? '' : '<i>rien pour la prochaine fois</i>')}</div><div class="ed-donne">Donné le ${esc(f.donne)} par M. MENEY P.</div></div>`))
      + `</div></div>` + cel(3, `<div class="ed-part"><span class="g">${f.qui.length} élève${f.qui.length > 1 ? 's' : ''} sur ${f.total} ${f.qui.length > 1 ? 'ont' : 'a'} participé</span><span>${f.qui.length ? f.qui.map(o => esc(o.p) + (o.n > 1 ? ' <i class="qn">×' + o.n + '</i>' : '')).join(' · ') : 'personne pour l\'instant'}</span><span class="m">${f.ecrit} réponse${f.ecrit > 1 ? 's' : ''} écrite${f.ecrit > 1 ? 's' : ''} · ${f.oral} prise${f.oral > 1 ? 's' : ''} de parole · ${f.total - f.qui.length ? 'il reste ' + (f.total - f.qui.length) + ' à passer' : 'tout le monde a participé'}</span></div>`) + `</div>`; }
"""
rep("  else if (et.doc) { h += `<span class=\"act\">${esc(actLib)}</span>` + docHtml(et.doc); }", rendu + "  else if (et.doc) { h += `<span class=\"act\">${esc(actLib)}</span>` + docHtml(et.doc); }")
css = r"""
/* (a) la diapo « Cahier de textes » : tout le texte suit le curseur (em du mur) ; les éléments non dévoilés gris au pilote, absents au tableau */
.mur .ed-agenda{font-family:"EB Garamond",Garamond,"Times New Roman",serif;background:#edf3fd;color:#333;display:flex;flex-direction:column;margin-top:.3em;flex:1;min-height:0;border:1px solid #d8e0ea}.mur .ed-bandeau{background:#0e478d;color:#fff;display:flex;align-items:center;gap:1em;padding:0 1em 0 0;font-size:.5em;height:2.6em}.mur .ed-logo{background:#0e579e;color:#fff;font-weight:700;font-size:.72em;line-height:1.15;letter-spacing:.02em;text-align:center;padding:0 1em;height:100%;display:flex;align-items:center;border-radius:0 0 1em 0}.mur .ed-etab{font-size:1em}.mur .ed-corps{padding:.35em .7em;display:flex;flex-direction:column;gap:.2em;flex:1;min-height:0}.mur .ed-titre{color:#0f8fd1;font-size:.72em;font-weight:300}.mur .ed-classe{color:#777;font-size:.7em;margin-left:.5em}.mur .ed-onglets{display:flex;font-size:.5em;margin:.2em 0}.mur .ed-onglets span{border:1px solid #cfd8e3;padding:.3em 1em;background:#fff;color:#0f8fd1;cursor:default}.mur .ed-onglets span.on{background:#e4e7ea;color:#333}.mur .ed-onglets span.voile{opacity:.4}.mur .ed-date{text-align:center;font-size:1.1em;font-weight:700;color:#0e478d;margin:.15em 0 .3em;animation:edpulse 1.8s ease-in-out infinite}@keyframes edpulse{0%,100%{opacity:1}50%{opacity:.3}}.mur .ed-carte{background:#fff;border:1px solid #d8e0ea;border-left:.2em solid #0f8fd1;padding:.4em .7em;flex:1;min-height:0;overflow:hidden}.mur .ed-matiere{text-align:center;color:#0f8fd1;font-size:.6em;letter-spacing:.04em;margin-bottom:.4em}.mur .ed-deja{color:#5c7186;font-style:italic;font-size:.75em;border-left:3px solid #cfd8e3;padding-left:.5em;margin-bottom:.4em}.mur .ed-texte{font-size:1em;line-height:1.4;color:#222;outline:none}.mur .ed-recit{font-size:.8em;line-height:1.45;max-height:100%;overflow:hidden}.mur .ed-recit p{margin:0 0 .4em}.mur .ed-recit .act-r{display:block;font-weight:700;color:#0f8fd1;font-size:.9em}.mur .ed-recit .cadre,.mur .ed-recit .sous,.mur .ed-recit .devoirs,.mur .ed-recit .bilan{display:none}.mur .ed-donne{text-align:right;font-style:italic;color:#555;font-size:.6em;margin-top:.4em}
.mur .ed-part{border-top:.12em solid #c99a4e;padding:.3em .6em;font-size:.55em;text-align:center;display:flex;gap:1.2em;align-items:baseline;justify-content:center;flex-wrap:wrap;color:#22303f}.mur .ed-part .g{color:#0f8f53;font-weight:600}.mur .ed-part .m{color:#5c7186;font-size:.85em}
.mur.pilote .cel.pas{opacity:.35}.mur.tableau .cel.pas{display:none}.mur .cel{position:relative}.mur .cel.spot-on{animation:allume 1s ease-in-out 10}
"""
rep("/* l'agenda École Directe, reconnaissable (capture de Paul du 17/09) — pas la pub, pas le calendrier */", css + "/* (ancien, v9c.9-13, sans objet) */")
rep("mur.querySelectorAll('[data-onglet]').forEach(o => o.onclick = () => { S.finVue = o.dataset.onglet; journal('tableau-onglet', { onglet: S.finVue }); tout(); }); }","mur.querySelectorAll('[data-onglet]').forEach(o => o.onclick = () => { S.finVue = o.dataset.onglet; journal('cahier-onglet', { onglet: S.finVue, di: S.di }); tout(); }); }")
rep("function devoiler(){","function devoiler(){ if (ecran().role === 'fin') { const d0 = etatDiapo(); if (d0.nDev === 2) S.finVue = 'contenu'; }")
garde_html = r"""<div class="garde" id="garde-cahier" title="La garde du cahier de textes : ce qui resterait non fait pour cette heure, ou la validation ; « Y aller » est la deuxième confirmation"><div class="boite" style="width:640px;border-color:var(--or)"><h3 id="gc-titre" style="margin:0 0 8px;color:var(--or);font-size:1.05rem">Aller au cahier de textes</h3><div id="gc-corps"></div><div class="choix" style="justify-content:flex-end;margin-top:12px"><button class="btn" id="gc-rester">Rester</button><button class="btn or" id="gc-aller">Y aller</button></div></div></div>
"""
rep('<div class="garde" id="garde">', garde_html + '<div class="garde" id="garde">')
gc = r"""function gardeCahier(faire){ const E = seance().ecrans; const o = ordreHeure(S.heure); const acts = {}; o.forEach(i => { const e = E[i]; if (e.role) return; const a = actDe(e); if (!a) return; const k = a.id; acts[k] = acts[k] || { a, diapos: [], restantes: 0, dur: 0, commencee: false }; acts[k].diapos.push(i); if (!finie(e, i)) acts[k].restantes++; else acts[k].commencee = true; acts[k].dur += (e.dur || 0); }); const rest = Object.values(acts).filter(x => x.restantes > 0 && !decisionDe(E[x.diapos[0]])); const avance = E.map((e, i) => ({ e, i })).filter(x => x.e.heure > S.heure && !x.e.role && finie(x.e, x.i)); let titre, corps;
  if (rest.length) { titre = 'Aller au cahier de textes — ce qui resterait non fait pour cette heure'; corps = rest.map(x => `<div class="gc-l"><span class="gc-n">A${x.a.num}</span><span>${esc(x.a.titre || x.a.act || '')} — ${x.restantes} diapo${x.restantes > 1 ? 's' : ''} restante${x.restantes > 1 ? 's' : ''}</span><span class="gc-r">${x.dur} min prévues · ${x.commencee ? 'commencée' : 'pas commencée'}</span></div>`).join('') + `<div class="gc-s">${rest.length > 1 ? 'Ces ' + rest.length + ' activités seront à décider' : 'Cette activité sera à décider'} dans la colonne de droite (à l'heure suivante, à la maison, en réserve, non fait).</div>`; }
  else if (avance.length) { const parH = {}; avance.forEach(x => { const k = 'heure ' + x.e.heure; parH[k] = (parH[k] || 0) + 1; }); titre = 'Aller au cahier de textes — tu es en avance'; corps = avance.map(x => `<div class="gc-l"><span class="gc-n">${numDe(x.e) ? 'A' + numDe(x.e) : ''}</span><span>${esc(x.e.act)} — faite</span><span class="gc-r">prévue pour l'heure ${x.e.heure}</span></div>`).join('') + `<div class="gc-s">Tu as fait ${avance.length} diapo${avance.length > 1 ? 's' : ''} en avance (${Object.entries(parH).map(([k, n]) => n + ' pour l\'' + k).join(', ')}). L'ordre de l'heure suivante s'en souviendra.</div>`; }
  else { titre = 'Aller au cahier de textes — validation'; corps = `<div class="gc-l"><span class="gc-n">✔</span><span>Aucune activité restante prévue pour cette heure — tu es à l'heure.</span><span class="gc-r"></span></div><div class="gc-s">Rien à décider : le cahier de textes n'aura que le travail à faire et le récit.</div>`; }
  $('gc-titre').textContent = titre; $('gc-corps').innerHTML = corps; $('garde-cahier').classList.add('on'); $('gc-rester').onclick = () => { $('garde-cahier').classList.remove('on'); journal('cahier-garde', { choix: 'rester' }); }; $('gc-aller').onclick = () => { $('garde-cahier').classList.remove('on'); journal('cahier-garde', { choix: 'y-aller' }); faire(); }; $('gc-aller').focus({ preventScroll: true }); }
"""
rep("function garde(faire, quoi){", gc + "function garde(faire, quoi){")
rep(".garde .choix{",".gc-l{display:flex;gap:10px;padding:6px 0;border-bottom:1px dotted var(--bord2);align-items:baseline}.gc-l:last-of-type{border:0}.gc-n{color:var(--sourd);width:3.2em;flex:0 0 auto}.gc-r{color:var(--texte2);font-size:.88rem;margin-left:auto;white-space:nowrap}.gc-s{color:var(--texte2);font-size:.9rem;margin-top:8px}\n.garde .choix{")
rep("function aller(i, parLeFil){ i = Math.max(0, Math.min(seance().ecrans.length - 1, i)); if (i === S.di) return;","function aller(i, parLeFil){ i = Math.max(0, Math.min(seance().ecrans.length - 1, i)); if (i === S.di) return; if (seance().ecrans[i].role === 'fin' && !S.gel && !S._parGardeCahier) { gardeCahier(() => { S._parGardeCahier = true; aller(i, true); S._parGardeCahier = false; }); return; }")
rep("function t5(){ S.t5 = true; journal('t5'); ouvrirFin(false); }","function t5(){ S.t5 = true; journal('t5'); const i = ordreHeure(S.heure).find(k => seance().ecrans[k].role === 'fin'); if (i != null) aller(i); /* (a) provisoire : l'alerte T-5 arrive en (b) */ }")
rep("$('bfin').onclick = () => ouvrirFin(true);","$('bfin').onclick = () => { ouvrirFin(true); const i = ordreHeure(S.heure).find(k => seance().ecrans[k].role === 'fin'); if (i != null && S.di !== i) aller(i); };")
rep("$('droite').classList.add('fin'); if (S.sansDroite) { S.sansDroite = false; poserColonnes(); } /* les décisions ont besoin de la colonne */ if (!S.enFin) { S.enFin = true; setTimeout(tout, 0); }","$('droite').classList.add('fin'); if (S.sansDroite) { S.sansDroite = false; poserColonnes(); } S.enFin = true;")
rep("· v9c.14 a0 <span","· v9c.14 a — <b>provisoire</b> : l'alerte T-5 et la séquence arrivent en (b), le récit en trois temps en (d) <span")
open(p,'w',encoding='utf-8').write(s); print("(a) écrit ;", s.count("'cahier'"), "cahier")
