p='vis/v9c14b-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:80])
    s = s.replace(a, b, n)
# ── 1. le chrono : compte à rebours vers l'heure du cahier à T-5, paliers, dépassement du cahier après zéro
rep("setInterval(() => { if (!S.lancee) { $('chr').textContent = '—'; $('heure').textContent = ''; return; } if (!S.close && !S.t5 && !document.getElementById('ecran-fin').classList.contains('on')) { const fin = HEURES_SIM[S.heure].base + 55 * 60000; if (now() >= fin - 5 * 60000) { t5(); } } S.ecoule++; const m = Math.floor(S.ecoule / 60), s = S.ecoule % 60; $('chr').textContent = String(m).padStart(2, '0') + ':' + String(s).padStart(2, '0'); $('heure').textContent = hhmm(); }, 1000);",
r"""const heureCahier = () => HEURES_SIM[S.heure].base + 55 * 60000 - 5 * 60000; /* 6.3 : le repère de la fin d'heure = la fin moins les cinq minutes réservées au cahier de textes */
function tick(){ if (!S.lancee) { $('chr').textContent = '—'; $('chr').className = ''; $('heure').textContent = ''; return; } S.ecoule++; $('heure').textContent = hhmm(); const chr = $('chr'); const reste = heureCahier() - now();
  if (S.close || reste > 5 * 60000) { const m = Math.floor(S.ecoule / 60), s = S.ecoule % 60; chr.textContent = String(m).padStart(2, '0') + ':' + String(s).padStart(2, '0'); chr.className = ''; chr.title = 'Le temps écoulé depuis le lancement de l\'heure'; return; }
  const abs = Math.abs(reste); const m = Math.floor(abs / 60000), sec = Math.floor((abs % 60000) / 1000); chr.textContent = (reste >= 0 ? '−' : '+') + m + ':' + String(sec).padStart(2, '0'); chr.className = reste <= 0 ? 'cr-zero' : reste <= 60000 ? 'cr-t1' : reste <= 180000 ? 'cr-t3' : 'cr-t5'; chr.title = reste >= 0 ? 'Compte à rebours vers l\'heure du cahier de textes (' + hhmm(heureCahier()) + ')' : 'Le cahier de textes a commencé depuis ' + m + ' min ' + sec + ' s (l\'heure court jusqu\'à Clore)';
  S.paliers = S.paliers || {}; const kk = reste <= 0 ? 'zero' : reste <= 60000 ? 't1' : reste <= 180000 ? 't3' : 't5'; ['t5', 't3', 't1', 'zero'].forEach(k => { const seuil = { t5: 5 * 60000, t3: 3 * 60000, t1: 60000, zero: 0 }[k]; if (reste <= seuil && !S.paliers[k]) { S.paliers[k] = true; palier(k); } }); }
setInterval(tick, 1000);""")
# ── 2. l'alerte : la boîte entre les outils et la zone de notes ; paliers ; « Plus tard » ; clic à côté ; déplaçable ; « Aller au cahier de textes »
rep('<div class="notes">', r"""<div id="al-boite" class="al-boite" style="display:none"><span class="al-poignee" id="al-poignee" title="Saisis ici pour déplacer la boîte et lire ce qu'il y a derrière ; relâchée en bas, elle reprend sa place">⠿</span><div class="al-txt" id="al-txt"></div><button class="btn or" id="al-aller" title="Va au cahier de textes — après la garde (ce qui resterait non fait), puis « Y aller »">Aller au cahier de textes</button><button class="btn" id="al-tard" title="Replie l'alerte ; elle reviendra au palier suivant (T-3, T-1, puis l'heure du cahier de textes, qui ne se replie plus)">Plus tard</button></div><div id="al-ligne" class="al-ligne" style="display:none" title="L'alerte repliée : un clic la rouvre"></div>
<div class="notes">""")
rep("\n.mur .ed-part{", r"""
/* (b) l'alerte T-5 (6.3) : au-dessus des notes, non bloquante, déplaçable ; les paliers ambre → orange → rouge ; sans pulser */
.al-boite{margin:8px 0 0;border-radius:10px;padding:9px 12px 9px 8px;display:flex;gap:12px;align-items:center;box-shadow:0 6px 18px rgba(0,0,0,.35);position:relative;font-size:.95rem;background:#1c1712;border:1px solid #c99a4e;z-index:25}.al-boite.t5{border-color:#c99a4e}.al-boite.t5 b{color:#c99a4e}.al-boite.t3{border:1.5px solid #e0812e;background:#221812}.al-boite.t3 b{color:#f0a05a}.al-boite.t1,.al-boite.zero{border:2px solid #e8484c;background:#2a1414;box-shadow:0 0 0 3px rgba(232,72,76,.25),0 6px 18px rgba(0,0,0,.45)}.al-boite.t1 b,.al-boite.zero b{color:#ff8a8c}.al-boite.t1 .btn.or,.al-boite.zero .btn.or{background:#e8484c;border-color:#e8484c;color:#fff}.al-boite .al-poignee{cursor:grab;color:var(--sourd);font-size:1.3rem;padding:0 4px;user-select:none;letter-spacing:-2px}.al-boite .al-txt{flex:1;line-height:1.35}.al-boite .al-txt span{color:var(--texte2)}.al-boite .btn{white-space:nowrap}.al-boite.flotte{position:fixed;width:640px;margin:0;box-shadow:0 12px 36px rgba(0,0,0,.6)}.al-boite .btn:disabled{opacity:.45;cursor:default}
.al-ligne{margin:8px 0 0;padding:5px 12px;border-radius:8px;background:#1c1712;border:1px solid #6b5230;color:var(--texte2);font-size:.9rem;cursor:pointer}.al-ligne.t3{border-color:#e0812e}.al-ligne.t1{border-color:#e8484c}
#chr.cr-t5{color:#c99a4e;animation:crp 1.6s ease-in-out infinite}#chr.cr-t3{color:#f0a05a;animation:crp .9s ease-in-out infinite}#chr.cr-t1{color:#ff5a5e;animation:crp .45s ease-in-out infinite;text-shadow:0 0 8px rgba(255,90,94,.6)}#chr.cr-zero{color:#ff5a5e;animation:crp .45s ease-in-out infinite;text-shadow:0 0 8px rgba(255,90,94,.6)}@keyframes crp{50%{opacity:.3}}
.mur .ed-part{""")
rep("function t5(){ S.t5 = true; journal('t5'); const i = ordreHeure(S.heure).find(k => seance().ecrans[k].role === 'fin'); if (i != null) aller(i); /* (a) provisoire : l'alerte T-5 arrive en (b) */ }",
r"""function t5(){ palier('t5'); }
const LIB_PALIER = { t5: 'le cahier de textes dans 5 minutes', t3: 'le cahier de textes dans 3 minutes', t1: 'le cahier de textes dans 1 minute', zero: 'c\'est l\'heure du cahier de textes' };
function etatActivite(){ const e = ecran(); const a = actDe(e); if (!a || e.role) return null; const E = seance().ecrans; const prevu = a.diapos.reduce((t, i) => t + (E[i].dur || 0), 0); let passe = 0; const ev = J.filter(x => x.type === 'diapo' && x.h === S.heure); ev.forEach((x, k) => { const fin = k + 1 < ev.length ? ev[k + 1].t : now(); if (a.diapos.includes(x.di)) passe += fin - x.t; }); (S.coupures || []).forEach(c => { if (!c.compte && a.diapos.includes(c.di)) passe -= (c.fin - c.debut); }); const min = Math.round(passe / 60000); return { a, prevu, min, txt: min > prevu ? `tu dépasses de ${min - prevu} min` : (prevu && min >= prevu * 0.8 ? 'il te reste peu de temps' : 'dans les temps') }; }
function palier(k){ if (S.close) return; S.t5 = true; S.palier = k; journal(k === 'zero' ? 'cahier-heure' : k); if (ecran().role === 'fin') { alerteFermer(); return; } alerteOuvrir(); }
function alerteTexte(){ const k = S.palier; const et = etatActivite(); return `<b>${k === 'zero' ? 'C\'est l\'heure du cahier de textes.' : 'T-' + { t5: 5, t3: 3, t1: 1 }[k] + ' — ' + LIB_PALIER[k] + '.'}</b> <span>${et ? 'L\'activité en cours : <b style="color:var(--texte)">Activité ' + et.a.num + ' — ' + esc(et.a.titre) + '</b>, ' + et.txt + '. ' : ''}${k === 'zero' ? 'Va au cahier de textes : l\'heure court (' + hhmm(HEURES_SIM[S.heure].base + 55 * 60000) + ').' : 'Le cahier de textes attend — le tableau ne bouge pas tant que tu n\'y vas pas.'}</span>`; }
function alerteOuvrir(){ const b = $('al-boite'); b.className = 'al-boite ' + S.palier; b.style.display = 'flex'; $('al-ligne').style.display = 'none'; $('al-txt').innerHTML = alerteTexte(); $('al-tard').style.display = S.palier === 'zero' ? 'none' : ''; S.alerteOuverte = true; }
function alerteReplier(){ if (S.palier === 'zero') return; $('al-boite').style.display = 'none'; const l = $('al-ligne'); l.className = 'al-ligne ' + S.palier; l.style.display = 'block'; l.textContent = 'T-' + { t5: 5, t3: 3, t1: 1 }[S.palier] + ' · le cahier de textes attend — ▸'; S.alerteOuverte = false; journal('alerte-repliee', { palier: S.palier }); }
function alerteFermer(){ $('al-boite').style.display = 'none'; $('al-ligne').style.display = 'none'; S.alerteOuverte = false; }
$('al-tard').onclick = () => alerteReplier(); $('al-ligne').onclick = () => alerteOuvrir();
$('al-aller').onclick = () => { if (document.querySelector('.garde.on')) return; const i = ordreHeure(S.heure).find(k => seance().ecrans[k].role === 'fin'); if (i != null) aller(i); };
document.addEventListener('click', ev => { if (!S.alerteOuverte || S.palier === 'zero') return; if (ev.target.closest('#al-boite, .garde, #vif-palette, #ppop, #menu, #menuplus, #fsimu')) return; alerteReplier(); });
(function glisserAlerte(){ const b = $('al-boite'); const pg = $('al-poignee'); let dx = 0, dy = 0, ph = null; const move = ev => { const w = b.offsetWidth, h = b.offsetHeight; const x = Math.max(0, Math.min(innerWidth - w, ev.clientX - dx)), y = Math.max(46, Math.min(innerHeight - h, ev.clientY - dy)); b.style.left = x + 'px'; b.style.top = y + 'px'; }; const up = ev => { document.removeEventListener('mousemove', move); document.removeEventListener('mouseup', up); if (ev.clientY > innerHeight * 2 / 3) { b.classList.remove('flotte'); b.style.left = b.style.top = ''; if (ph) { ph.remove(); ph = null; } } journal('alerte-deplacee'); };
  pg.addEventListener('mousedown', ev => { ev.preventDefault(); const r = b.getBoundingClientRect(); dx = ev.clientX - r.left; dy = ev.clientY - r.top; if (!b.classList.contains('flotte')) { ph = document.createElement('div'); ph.style.height = r.height + 8 + 'px'; b.insertAdjacentElement('afterend', ph); b.classList.add('flotte'); b.style.left = r.left + 'px'; b.style.top = r.top + 'px'; } document.addEventListener('mousemove', move); document.addEventListener('mouseup', up); }); })();""")
# quand on arrive au cahier, l'alerte se ferme ; quand on le quitte avant zéro, elle revient au palier courant
rep("function tout(){","function tout(){ if (S.t5 && !S.close) { if (ecran().role === 'fin') alerteFermer(); else if (!S.alerteOuverte && $('al-ligne').style.display === 'none' && S.palier) alerteOuvrir(); }")
# ── 3. la simulation : T-5 (cahier − 5), T-3, T-1, l'heure du cahier
rep('<button class="btn" id="s-t5" title="Avance l\'horloge simulée à cinq minutes de la fin','<button class="btn" id="s-t3" title="Simulation : avance l\'horloge à trois minutes du cahier de textes">T-3</button> <button class="btn" id="s-t1" title="Simulation : avance l\'horloge à une minute du cahier de textes">T-1</button> <button class="btn" id="s-cahier" title="Simulation : avance l\'horloge à l\'heure du cahier de textes">L\'heure du cahier</button> <button class="btn" id="s-t5" title="Simulation : avance l\'horloge à cinq minutes du cahier de textes (le cahier commence cinq minutes avant la fin)')
rep("$('s-t5').onclick = () => { $('fsimu').classList.remove('on'); t5(); }","const avancerA = ms => { const cible = heureCahier() - ms; if (cible > now()) { S.ecoule += Math.floor((cible - now()) / 1000); DECALAGE += cible - now(); } tick(); }; $('s-t5').onclick = () => { $('fsimu').classList.remove('on'); avancerA(5 * 60000); }; $('s-t3').onclick = () => { $('fsimu').classList.remove('on'); avancerA(3 * 60000); }; $('s-t1').onclick = () => { $('fsimu').classList.remove('on'); avancerA(60000); }; $('s-cahier').onclick = () => { $('fsimu').classList.remove('on'); avancerA(0); };")
# ── 4. « Fin de l'heure » n'emmène plus au cahier (c'est l'alerte qui le propose) ; il ouvre la séquence
rep("$('bfin').onclick = () => { ouvrirFin(true); const i = ordreHeure(S.heure).find(k => seance().ecrans[k].role === 'fin'); if (i != null && S.di !== i) aller(i); };","$('bfin').onclick = () => ouvrirFin(true);")
# ── 5. la séquence : ouvrirFin compose ses quatre sections à partir de son contenu (mêmes identifiants), avec les flèches et les résumés
rep("  const scrollAvant = $('droite').scrollTop; poserHtml($('fin'), h);", r"""  h = sequenceHtml(h, cloture, restantes);
  const scrollAvant = $('droite').scrollTop; poserHtml($('fin'), h);""")
rep("function ouvrirFin(cloture){", r"""function sequenceHtml(h, cloture, restantes){ /* (b) 7.0 : quatre sections repliées qui s'empilent — même contenu, mêmes identifiants, l'ordre de Paul */
  const tmp = document.createElement('div'); tmp.innerHTML = h; const q = sel => tmp.querySelector(sel); const out = n => (n ? n.outerHTML : '');
  const echLabel = tmp.querySelector('#f-ech') ? tmp.querySelector('#f-ech').closest('label') : null; if (echLabel) echLabel.remove(); const travail = q('.travail'); const rangee = q('.rangee'); const h3prevu = tmp.querySelector('h3'); const avant = q('.avant'); const barre = q('.barre-fin'); tmp.querySelectorAll('[data-finvue]').forEach(x => x.parentElement.remove());
  S.finSection = S.finSection || 1; S.finFaites = S.finFaites || {}; const f1 = !!S.finFaites[1], f2 = !!S.finFaites[2] || (restantes || []).every(x => S.decisions[x.a.id] && !S.decisions[x.a.id].defaut), f3 = !!S.finFaites[3];
  const resume1 = S.echeance ? '✔ ' + esc((DATA.classe.prochaines.find(x => x.iso === S.echeance) || {}).l || S.echeance) + ' — « Prenez vos agendas » est au tableau' : '✔ sans échéance'; const dec = (restantes || []).map(x => (S.decisions[x.a.id] || {}).choix).filter(Boolean); const resume2 = (restantes || []).length ? dec.map(c => ({ suivante: 'à l\'heure suivante', terminer: 'à la maison', preparer: 'à préparer', reserve: 'en réserve', nonfait: 'non fait', reporter: 'reportée', pastemps: 'à la maison', passee: 'passée' }[c] || c)).join(', ') + ' · ' + (S.travail.apprendre || []).length + ' notion' + ((S.travail.apprendre || []).length > 1 ? 's' : '') + ' à apprendre' : 'rien ne restait · ' + (S.travail.apprendre || []).length + ' notions à apprendre'; const resume3 = 'verser, garder les notes, le mot aux absents';
  const sec = (n, titre, corps, faite, resume) => { const ouverte = S.finSection === n; return `<div class="sec${ouverte ? ' ouverte' : ''}${faite ? ' faite' : ''}" data-sec="${n}"><div class="tt"${!ouverte ? ' style="cursor:pointer"' : ''} data-ouvre="${n}">${n} · ${titre}${faite && !ouverte ? ' <span class="okr">' + resume + '</span>' : ''}</div>${ouverte ? corps : ''}</div>`; };
  const fleche = (n, ok) => `<div class="fleche${ok ? '' : ' grise'}" data-fleche="${n}" title="${ok ? 'Ouvre la section suivante' : 'La section précédente n\'est pas faite'}">▼</div>`;
  const corps1 = `<div class="sous">Prenez vos agendas pour le… — la date part au tableau, dans le cahier de textes.</div>${out(echLabel)}<div style="margin-top:6px"><button class="btn" id="f-sans-ech" title="Pas d\'échéance donnée : le cahier dira « la prochaine fois »">Sans échéance</button></div>`;
  const corps2 = `${out(h3prevu)}${out(rangee)}${out(travail)}`; const corps3 = cloture ? out(avant) : '<div class="sous">(à la clôture)</div>'; const corps4 = out(barre);
  return `<div class="seq"><div class="seq-tete"><b>Fin de l'heure — dans l'ordre</b> <button class="btn" id="f-fermer" title="Referme la colonne et reprend le cours ; rien n\'est fermé, tes choix restent">Reprendre le cours</button></div>` + sec(1, 'L\'échéance', corps1, f1, resume1) + fleche(2, f1) + sec(2, 'Ce qui reste, et les notions', corps2, f2, resume2) + fleche(3, f2) + sec(3, 'Avant de clore', corps3, f3, resume3) + fleche(4, f3) + sec(4, 'Clore l\'heure', corps4, false, '') + `</div>`; }
function ouvrirFin(cloture){""")
# les branchements de la séquence, après poserHtml
rep("  $('droite').scrollTop = scrollAvant;", r"""  $('fin').querySelectorAll('[data-ouvre]').forEach(t => t.onclick = () => { const n = +t.dataset.ouvre; if (n === S.finSection) return; if (n < S.finSection || S.finFaites[n - 1] || n === 1) { S.finSection = n; ouvrirFin(cloture); } });
  $('fin').querySelectorAll('[data-fleche]').forEach(f => f.onclick = () => { if (f.classList.contains('grise')) return; const n = +f.dataset.fleche; S.finFaites[n - 1] = true; S.finSection = n; journal('fin-section', { n }); ouvrirFin(cloture); });
  const fse = $('f-sans-ech'); if (fse) fse.onclick = () => { S.echeance = null; S.finFaites[1] = true; S.finSection = 2; edTexte(); tout(); ouvrirFin(cloture); };
  const fe2 = $('f-ech'); if (fe2) fe2.addEventListener('change', () => { S.finFaites[1] = true; ouvrirFin(cloture); });
  $('droite').scrollTop = scrollAvant;""")
# l'ancienne barre : « Annuler » disparaît (le bouton est en tête) ; f-ok n'existe plus
rep("$('f-fermer').onclick = () => { $('ecran-fin').classList.remove('on'); $('droite').classList.remove('fin'); S.enFin = false; tout(); }; const fo = $('f-ok'); if (fo) fo.onclick = () => { $('ecran-fin').classList.remove('on'); $('droite').classList.remove('fin'); S.enFin = false; tout(); };","$('f-fermer').onclick = () => { $('ecran-fin').classList.remove('on'); $('droite').classList.remove('fin'); S.enFin = false; tout(); };")
rep(".gc-l{display:flex;", r""".seq{display:flex;flex-direction:column;gap:6px}.seq-tete{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:4px}.sec{background:var(--carte);border:1px solid var(--bord);border-radius:8px;padding:8px 10px}.sec.faite{border-color:#2f4a3c}.sec.ouverte{border-color:var(--or)}.sec .tt{font-weight:600}.sec .okr{color:var(--joue);font-size:.8rem;font-weight:400;display:block;margin-top:2px}.fleche{text-align:center;color:var(--or);font-size:1.1rem;line-height:1;cursor:pointer}.fleche.grise{color:var(--sourd);cursor:default}#droite-fin .fin .barre-fin{position:static;padding:4px 0}#droite-fin .fin .barre-fin > span:first-child{display:block;font-size:.85rem;margin-bottom:6px}
.gc-l{display:flex;""")
rep("· v9c.14 a — <b>provisoire</b> : l'alerte T-5 et la séquence arrivent en (b), le récit en trois temps en (d) <span","· v9c.14 b — <b>provisoire</b> : les durées par activité en (c), le récit en trois temps et « figer » en (d), Maj + P en (e), « Le chapitre » en (f) <span")
open(p,'w',encoding='utf-8').write(s); print("(b) écrit")
