p='vis/v9c14c-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:80])
    s = s.replace(a, b, n)
# ── (c) LES DURÉES PAR ACTIVITÉ, MODIFIABLES EN DIRECT, AVEC LES ÉTATS DE WORKTRACK (5.4 bis) — une seule source de durée, une seule source de temps passé
rep("function etatActivite(){", r"""const dureeDe = a => { if (S.durees && S.durees[a.id] != null) return S.durees[a.id]; const E = seance().ecrans; return a.diapos.filter(i => ordreHeure(S.heure).includes(i)).reduce((t, i) => t + (E[i].dur || 0), 0); }; /* (c) la durée d'une activité pour cette heure : la trame, ou ce que Paul a changé (la copie de classe) */
function tempsActivite(a){ /* le temps passé sur ses diapos au journal, hors temps mis à part (1.3 bis) */ let passe = 0; const ev = J.filter(x => x.type === 'diapo' && x.h === S.heure); ev.forEach((x, k) => { const fin = k + 1 < ev.length ? ev[k + 1].t : now(); if (a.diapos.includes(x.di)) passe += fin - x.t; }); (S.coupures || []).forEach(c => { if (!c.compte && a.diapos.includes(c.di)) passe -= (c.fin - c.debut); }); return Math.max(0, Math.round(passe / 60000)); }
function etatWorktrack(a){ const E = seance().ecrans; const diapos = a.diapos.filter(i => ordreHeure(S.heure).includes(i)); if (!diapos.length) return null; const prevu = dureeDe(a); const min = tempsActivite(a); const toutes = diapos.every(i => finie(E[i], i)); const commencee = diapos.some(i => (vuMax[K(i)] || 0) > 0 || J.some(x => x.type === 'diapo' && x.di === i)); if (toutes) return { k: 'fin', txt: 'terminée', prevu, min }; if (!commencee) return { k: 'attend', txt: '', prevu, min }; if (min > prevu) return { k: 'dep', txt: 'tu dépasses · +' + (min - prevu) + ' min', prevu, min }; if (prevu && min >= prevu * 0.8) return { k: 'peu', txt: 'il te reste peu de temps', prevu, min }; return { k: 'ok', txt: 'dans les temps', prevu, min }; }
function activitesDeLHeure(){ const E = seance().ecrans; const o = ordreHeure(S.heure); const vues = []; const out = []; o.forEach(i => { const e = E[i]; if (e.role) return; const a = actDe(e); if (!a || vues.includes(a.id)) return; vues.push(a.id); out.push(a); }); return out; }
function etatActivite(){ const e = ecran(); const a = actDe(e); if (!a || e.role) return null; const w = etatWorktrack(a); return { a, prevu: w.prevu, min: w.min, txt: w.txt || 'dans les temps' }; }
function etatActiviteAncien(){""")
# « Où on en est » : l'en-tête (prévu par activité, utile, dépasse) puis la liste des durées
rep("function ouOnEnEst(){ const e = ecran(); const prevu = seance().ecrans.filter(x => x.heure === S.heure).reduce((a, x) => a + x.dur, 0); const utile = 46; const debord = prevu - utile;\n  $('ou').innerHTML = `<span>${esc(e.act)} — en cours</span><b>H${S.heure} · ${prevu} min prévues / ${utile} utiles</b>`; $('retard').textContent = debord > 0 ? `l'heure dépasse de ${debord} min` : ''; }",
r"""function ouOnEnEst(){ const e = ecran(); const acts = activitesDeLHeure(); const prevu = acts.reduce((t, a) => t + dureeDe(a), 0) + 5; const misAPart = (S.coupures || []).filter(c => !c.compte).reduce((t, c) => t + c.duree, 0); const utile = 46 - Math.floor(S.ecoule / 60) + misAPart + Math.floor(S.ecoule / 60); const debord = prevu - 50; /* 50 = 55 − 5 réservées au cahier */
  $('ou').innerHTML = `<span>${esc(e.act)} — en cours</span><b>H${S.heure} · ${prevu} min prévues / 50 utiles</b>`; $('retard').textContent = debord > 0 ? `l'heure dépasse de ${debord} min` : '';
  /* (c) la liste des durées par activité (5.4 bis) : [min] hh:mm titre · l'état de worktrack */
  let t = HEURES_SIM[S.heure].base; const enCours = actDe(e); const focus = document.activeElement && document.activeElement.classList.contains('dur-in') ? document.activeElement.dataset.a : null;
  const lignes = acts.map(a => { const w = etatWorktrack(a) || { k: 'attend', txt: '' }; const debut = t; t += dureeDe(a) * 60000; const cours = enCours && enCours.id === a.id; const val = focus === a.id ? document.activeElement.value : dureeDe(a); return `<div class="dur-l${w.k === 'fin' ? ' faite' : ''}${cours ? ' cours' : ''}"><input class="dur-in" data-a="${a.id}" value="${val}" title="Les minutes prévues pour cette activité — change-les pendant le cours : les heures de début de la suite se recalent ; ça vaut pour cette classe, la trame ne change que si tu verses à la clôture"><span class="dur-h">${hhmm(debut)}</span><span class="dur-t" title="${esc(a.titre || '')}">A${a.num} · ${esc(a.titre || '')}</span><span class="dur-e ${w.k}">${w.txt}</span></div>`; });
  lignes.push(`<div class="dur-l cahier"><input class="dur-in" value="5" disabled title="Les cinq minutes réservées au cahier de textes ne se changent pas"><span class="dur-h">${hhmm(heureCahier())}</span><span class="dur-t">Cahier de textes</span><span class="dur-e"></span></div>`);
  const d = $('durees'); poserHtml(d, lignes.join('')); d.querySelectorAll('.dur-in:not([disabled])').forEach(inp => { const valider = () => { const a = activitesDeLHeure().find(x => x.id === inp.dataset.a); if (!a) return; const v = Math.max(1, Math.min(55, parseInt(inp.value, 10) || dureeDe(a))); if (v === dureeDe(a)) { inp.value = v; return; } const avant = dureeDe(a); S.durees = S.durees || {}; S.durees[a.id] = v; journal('duree-changee', { act: a.id, num: a.num, avant, apres: v }); tout(); }; inp.onkeydown = ev => { if (ev.key === 'Enter') { ev.preventDefault(); inp.blur(); } if (ev.key === 'Escape') { inp.value = dureeDe(activitesDeLHeure().find(x => x.id === inp.dataset.a)); inp.blur(); } ev.stopPropagation(); }; inp.onblur = valider; }); }""")
rep('<h5>Où on en est</h5><div class="ou" id="ou"></div><div class="retard" id="retard"></div>','<h5>Où on en est</h5><div class="ou" id="ou"></div><div class="retard" id="retard"></div><div class="dur" id="durees" title="Une ligne par activité de l\'heure : les minutes prévues (modifiables), l\'heure prévue de début, le titre, l\'état — terminée · dans les temps · il te reste peu de temps · tu dépasses"></div>')
rep("\n.mur .ed-part{", r"""
/* (c) les durées par activité (5.4 bis) */
.dur{font-size:.84rem;line-height:1.3;margin-top:6px}.dur-l{display:flex;gap:6px;align-items:center;padding:2px 0;border-bottom:1px dotted var(--bord)}.dur-l:last-child{border:0}.dur-in{width:2.4em;background:#191411;color:var(--texte);border:1px solid var(--bord2);border-radius:3px;text-align:right;font:inherit;font-size:.8rem;padding:0 3px}.dur-in:disabled{opacity:.5}.dur-h{color:var(--sourd);width:3.2em;font-variant-numeric:tabular-nums;flex:0 0 auto}.dur-t{flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0}.dur-l.faite{color:var(--sourd)}.dur-l.faite .dur-t{text-decoration:line-through}.dur-l.cours .dur-t{color:var(--texte);font-weight:600}.dur-l.cahier{color:var(--sourd)}.dur-e{font-size:.66rem;border-radius:999px;padding:0 6px;white-space:nowrap;flex:0 0 auto}.dur-e.fin{background:rgba(111,179,224,.15);color:#a8cbea}.dur-e.ok{background:rgba(60,187,128,.18);color:#8fe0b8}.dur-e.peu{background:rgba(201,154,78,.2);color:#e0c48c;animation:edpulse 1.8s ease-in-out infinite}.dur-e.dep{background:rgba(232,72,76,.2);color:#f0a0a0;animation:edpulse 1.4s ease-in-out infinite}
.mur .ed-part{""")
# les cartes du T-5 et la garde lisent la durée changée
rep("acts[k].dur += (e.dur || 0); }); const rest = Object.values(acts)","acts[k].dur = dureeDe(a); }); const rest = Object.values(acts)")
# « verser » à la clôture : les durées changées
rep("Diapos modifiées pendant l'heure","Durées changées pendant l'heure</b> — verser dans la trame ? ${(S.durees && Object.keys(S.durees).length) ? Object.keys(S.durees).map(id => { const a = (DATA.activites[String(S.si)] || []).find(x => x.id === id); return a ? `<label><input type=\"checkbox\" data-verse-duree=\"${id}\"> A${a.num} · ${esc(a.titre || '')} : ${S.durees[id]} min</label>` : ''; }).join('') : '<span class=\"sourd\">aucune</span>'}<br><b>Diapos modifiées pendant l'heure")
# la simulation : « avancer sans compter » (le décalage sans temps d'activité) ; T-5 etc. avancent SANS gonfler l'activité en cours (on note un temps mis à part de simulation)
rep("const avancerA = ms => { const cible = heureCahier() - ms; if (cible > now()) { S.ecoule += Math.floor((cible - now()) / 1000); DECALAGE += cible - now(); } tick(); };","const avancerA = ms => { const cible = heureCahier() - ms; if (cible > now()) { const saut = cible - now(); S.coupures = S.coupures || []; S.coupures.push({ debut: now(), fin: now() + saut, di: S.di, eid: ecran().eid, duree: Math.round(saut / 60000), compte: false, simulation: true }); /* le saut de simulation ne compte pour aucune activité */ S.ecoule += Math.floor(saut / 1000); DECALAGE += saut; } tick(); tout(); };")
rep("· v9c.14 b2 — <b>provisoire</b>","· v9c.14 c — <b>provisoire</b>")
open(p,'w',encoding='utf-8').write(s); print("(c) écrit")
