p='vis/v9c14d-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── 1. le récit en trois temps (2 · 1.2 ter / quater) : chaque paragraphe d'activité porte le temps où elle a commencé ; les repères, les entre-temps, « on a continué », le verdict
rep("p.push('<p><span class=\"act-r\">' + titreP + '</span> ' + (phrases.length ? tete + corpsP : '') + notes.map(n => ' <span class=\"versee\">' + esc(n.t.replace(/[.\\s]+$/, '')) + '</span>').join('') + '</p>')",
"p.push('<p data-cle=\"' + esc(g.cle) + '\" data-t0=\"' + (vus[g.dis[0]] || 0) + '\" data-t1=\"' + (Math.max(...g.dis.map(di => vuJ(h, di).fin || vus[di] || 0)) || 0) + '\" data-titre=\"' + titreP.replace(/\"/g, '&quot;') + '\"><span class=\"act-r\">' + titreP + '</span> ' + (phrases.length ? tete + corpsP : '') + notes.map(n => ' <span class=\"versee\">' + esc(n.t.replace(/[.\\s]+$/, '')) + '</span>').join('') + '</p>')")
rep("function recitHtml(fin, h, bornes){ h = h || S.heure; const finHeure = (S.closes && S.closes[h]) || fin;",
r"""function recitHtml(fin, h, bornes){ h = h || S.heure; if (S.recitVersion && S.recitVersion[h] === 'moi' && S.recitMoi && S.recitMoi[h] != null) return `<div class="recit ma-version">${S.recitMoi[h]}</div>`; /* (d) 3.8 : ma version, une seule source */ return troisTemps(recitHtml0(fin, h, bornes), h, fin); }
const TEMPS = [['debut', 0, 10], ['entre1', 10, 25], ['milieu', 25, 35], ['entre2', 35, 45], ['fin', 45, 99]];
function tempsDe(ms, h){ const min = (ms - HEURES_SIM[h].base) / 60000; return (TEMPS.find(t => min >= t[1] && min < t[2]) || TEMPS[TEMPS.length - 1])[0]; }
function troisTemps(html, h, fin){ /* (d) 2 · 1.2 ter et quater — les paragraphes d'activité regroupés par le temps où elle a commencé (l'heure réelle), les repères, « on a continué », le verdict */
  const d = document.createElement('div'); d.innerHTML = html; const rec = d.querySelector('.recit') || d; const ps = Array.from(rec.querySelectorAll('p[data-cle]')); if (!ps.length) return html;
  const REP = { debut: 'Au début de l\'heure, on a commencé par', milieu: 'Puis, au milieu de l\'heure, on a fait', fin: 'Enfin, à la fin de l\'heure, on a fait', entre1: 'Ensuite, on a fait', entre2: 'Après cela, on a fait' };
  const groupes = {}; TEMPS.forEach(t => groupes[t[0]] = []); ps.forEach(pEl => { const t0 = +pEl.dataset.t0; groupes[tempsDe(t0, h)].push(pEl); });
  const E = seance().ecrans; const JH = J.filter(x => x.h === h); const enCoursDans = (t) => { /* une activité commencée avant ce temps et qui s'y poursuit (des diapos vues dans ce temps) */ const b = TEMPS.find(x => x[0] === t); const deb = HEURES_SIM[h].base + b[1] * 60000, finT = HEURES_SIM[h].base + b[2] * 60000; return ps.find(pEl => +pEl.dataset.t0 < deb && +pEl.dataset.t1 >= deb) ? ps.find(pEl => +pEl.dataset.t0 < deb && +pEl.dataset.t1 >= deb) : null; };
  const vuesDans = (cle, t) => { const b = TEMPS.find(x => x[0] === t); const deb = HEURES_SIM[h].base + b[1] * 60000, finT = HEURES_SIM[h].base + b[2] * 60000; return JH.filter(x => x.type === 'diapo' && x.t >= deb && x.t < finT && E[x.di] && (E[x.di].actId || ('r-' + E[x.di].eid)) === cle).map(x => E[x.di].act); };
  const out = []; let dernierTemps = null;
  TEMPS.forEach(([t]) => { const g = groupes[t]; if (g.length) { const rt = document.createElement('p'); rt.className = 'rt rt-' + t; rt.innerHTML = REP[t] + ' <b>' + g[0].dataset.titre.replace(/^Activité (\d+) — /, 'l\'activité $1 — ') + '</b>' + (g.length > 1 ? ', puis ' + g.slice(1).map(x => '<b>' + x.dataset.titre.replace(/^Activité (\d+) — /, 'l\'activité $1 — ') + '</b>').join(', ') : '') + '.'; out.push(rt); g.forEach(x => out.push(x)); dernierTemps = t; }
    else if (['milieu', 'fin'].includes(t)) { const cont = enCoursDans(t); if (cont) { const vues = vuesDans(cont.dataset.cle, t); const rt = document.createElement('p'); rt.className = 'rt rt-' + t + ' continue'; rt.innerHTML = (t === 'milieu' ? 'Puis, au milieu de l\'heure, on a continué ' : 'Enfin, à la fin de l\'heure, on a continué ') + '<b>' + cont.dataset.titre.replace(/^Activité (\d+) — /, 'l\'activité $1 — ') + '</b>' + (vues.length ? ' avec ' + vues.map(v => '<i>' + esc(v) + '</i>').join(', ') : '') + '.'; out.push(rt); dernierTemps = t; } } });
  /* le verdict : l'activité en cours au passage au cahier (ou la dernière vue) */ const dCahier = JH.find(x => x.type === 'diapo' && E[x.di] && E[x.di].role === 'fin'); const avant = JH.filter(x => x.type === 'diapo' && E[x.di] && !E[x.di].role && (!dCahier || x.t < dCahier.t)); const last = avant[avant.length - 1]; if (last) { const a = actDe(E[last.di]); if (a) { const diapos = a.diapos.filter(i => ordreHeure(h).includes(i)); const toutes = diapos.every(i => finie(E[i], i)); const min = tempsActivite(a); const v = document.createElement('p'); v.className = 'rt verdict'; v.innerHTML = toutes ? 'Et on l\'a terminée.' : (min >= 1 && min <= 5 ? 'Mais on ne l\'a pas terminée — tout juste commencée.' : 'Mais on ne l\'a pas terminée.'); const dernierP = out.length ? out[out.length - 1] : null; out.push(v); } }
  ps.forEach(x => x.remove()); const ancre = rec.querySelector('p.cadre'); let cur = ancre; out.forEach(el => { if (cur && cur.parentElement === rec) { cur.insertAdjacentElement('afterend', el); cur = el; } else rec.appendChild(el); });
  return d.innerHTML; }
function recitHtml0(fin, h, bornes){ h = h || S.heure; const finHeure = (S.closes && S.closes[h]) || fin;""")
# l'ancien « figer » de la relecture retiré (remplacé par le sélecteur)
rep("  if (S.recitFige && S.recitFigeHtml) return `<div class=\"recit\" contenteditable=\"true\" style=\"outline:2px dashed #c9a04a\">${S.recitFigeHtml}</div>","  if (false) return ``")
rep("\n.mur .ed-part{", r"""
/* (d) le récit en trois temps, le sélecteur composé | ma version, le défilement synchronisé */
.recit .rt{color:#0f8fd1;font-weight:700;margin:.6em 0 .2em}.recit .rt.verdict{color:#0f8f53}.recit .rt b{color:inherit}.mur .ed-recit .rt{font-size:.95em;margin:.5em 0 .15em}
.mur .ed-carte{overflow:auto}.mur.tableau .ed-carte{overflow:hidden}
.rv{display:flex;gap:0;font-size:.5em;margin:.2em 0 .3em}.rv span{border:1px solid #cfd8e3;padding:.3em 1em;background:#fff;color:#0f8fd1;cursor:pointer}.rv span.on{background:#0f8fd1;color:#fff}.rv .rv-h{margin-left:auto;display:flex;gap:.4em}.rv .rv-h button{font:inherit;border:1px solid #cfd8e3;background:#fff;color:#0f8fd1;border-radius:.3em;padding:0 .5em;cursor:pointer}.rv .rv-h button:disabled{opacity:.35}
.mur .ed-recit[contenteditable="true"]{outline:2px dashed #c9a04a;outline-offset:.2em}
.mur .ed-part{""")
# ── 2. le sélecteur dans le cahier (onglet Contenus, pilote) ; ma version modifiable ; ↶ ↷ ; la garde après copie
rep("? cel(2, `<div class=\"ed-carte\"><div class=\"ed-matiere\">FRANCAIS — contenu de la séance</div><div class=\"ed-texte ed-recit\" data-p=\"0.r\">${f.recit || '<i>rien encore</i>'}</div></div>`)",
"? cel(2, `<div class=\"ed-carte\">${et.pilote ? `<div class=\"rv\"><span class=\"${f.version === 'moi' ? '' : 'on'}\" data-rv=\"site\" title=\"Le récit composé par le site — il se réécrit tout seul à chaque geste ; ta version reste gardée\">composé par le site</span><span class=\"${f.version === 'moi' ? 'on' : ''}\" data-rv=\"moi\" title=\"Ta version : le récit devient modifiable ici, avec Ctrl+Z / Ctrl+Y ; chaque modification est une version gardée\">ma version (modifier)</span><span class=\"rv-h\"><button id=\"rv-undo\" title=\"Revenir à la version précédente\">↶</button><button id=\"rv-redo\" title=\"Rétablir la version suivante\">↷</button></span></div>` : ''}<div class=\"ed-matiere\">FRANCAIS — contenu de la séance${f.version === 'moi' ? ' · ma version' : ''}</div><div class=\"ed-texte ed-recit\"${et.pilote && f.version === 'moi' ? ' contenteditable=\"true\" id=\"ed-recit-edit\"' : ''} data-p=\"0.r\">${f.recit || '<i>rien encore</i>'}</div></div>`)")
rep("return { onglet: S.finVue || 'travail', recit: (S.finVue === 'contenu') ? recitPourED(S.heure) : '',","return { onglet: S.finVue || 'travail', version: (S.recitVersion || {})[S.heure] || 'site', scroll: (S.cahierScroll || {})[S.heure] || 0, recit: (S.finVue === 'contenu') ? recitPourED(S.heure) : '',")
# recitPourED lit « ma version » telle quelle
rep("function recitPourED(h){ const d = document.createElement('div'); d.innerHTML = recitHtml(now(), h);","function recitPourED(h){ if (S.recitVersion && S.recitVersion[h] === 'moi' && S.recitMoi && S.recitMoi[h] != null) return S.recitMoi[h]; const d = document.createElement('div'); d.innerHTML = recitHtml(now(), h);")
rep("function recitPourED(h){","function versionsDe(h){ S.recitVersions = S.recitVersions || {}; S.recitVersions[h] = S.recitVersions[h] || { l: [], k: -1 }; return S.recitVersions[h]; }\nfunction poserVersion(h, html){ const v = versionsDe(h); v.l = v.l.slice(0, v.k + 1); v.l.push({ t: now(), html }); v.k = v.l.length - 1; S.recitMoi = S.recitMoi || {}; S.recitMoi[h] = html; }\nfunction basculerRecit(h, vers){ const faire = () => { S.recitVersion = S.recitVersion || {}; S.recitVersion[h] = vers; if (vers === 'moi' && (!S.recitMoi || S.recitMoi[h] == null)) poserVersion(h, recitPourED0(h)); journal(vers === 'moi' ? 'recit-ma-version' : 'recit-compose-par-le-site', { h }); tout(); if ($('rel') && document.getElementById('ecran-relecture').classList.contains('on')) relecture(); }; if (vers === 'moi' && S.copieED && S.copieED[h]) { gardeCopie(h, faire); } else faire(); }\nfunction gardeCopie(h, faire){ const c = S.copieED[h]; $('gcopie-titre').textContent = `Ce récit a déjà été copié pour École Directe à ${hhmm(c.t).replace(':', ' h ')} — poursuivre quand même ?`; $('garde-copie').classList.add('on'); $('gcopie-oui').onclick = () => { $('garde-copie').classList.remove('on'); journal('recit-poursuivre-apres-copie', { h }); faire(); }; $('gcopie-non').onclick = () => { $('garde-copie').classList.remove('on'); }; $('gcopie-non').focus(); }\nfunction recitPourED0(h){ const d = document.createElement('div'); d.innerHTML = troisTemps(recitHtml0(now(), h), h, now()); const r = d.querySelector('.recit'); return r ? Array.from(r.querySelectorAll(':scope > p')).filter(x => !x.classList.contains('cadre') && !x.classList.contains('sous') && !x.classList.contains('devoirs')).map(x => x.outerHTML).join('') : ''; }\nfunction recitPourED(h){")
rep('<div class="garde" id="garde-cahier"', r"""<div class="garde" id="garde-copie" title="La garde après copie : ce récit est déjà parti dans École Directe"><div class="boite" style="width:560px;border-color:var(--or)"><h3 id="gcopie-titre" style="margin:0 0 10px;color:var(--or);font-size:1.05rem"></h3><div class="choix" style="justify-content:flex-end"><button class="btn" id="gcopie-non">Annuler</button><button class="btn or" id="gcopie-oui">Poursuivre quand même</button></div></div></div>
<div class="garde" id="garde-cahier\"""")
s=s.replace('id="garde-cahier\\"','id="garde-cahier"')
# brancherFin : le sélecteur, la frappe dans ma version (versions, journal), ↶ ↷, le défilement
rep("function brancherFin(){ const ed = mur.querySelector('#ed-edit');","function brancherFin(){ const h = S.heure; mur.querySelectorAll('[data-rv]').forEach(b => b.onclick = () => { if (((S.recitVersion || {})[h] || 'site') !== b.dataset.rv) basculerRecit(h, b.dataset.rv); }); const re = mur.querySelector('#ed-recit-edit'); if (re) { re.oninput = () => { S.recitMoi = S.recitMoi || {}; S.recitMoi[h] = re.innerHTML; if (!S._rvT) S._rvT = setTimeout(() => { S._rvT = null; poserVersion(h, re.innerHTML); journal('recit-modifie', { h }); tout(); }, 800); }; re.onkeydown = ev => { ev.stopPropagation(); }; } const u = mur.querySelector('#rv-undo'), r = mur.querySelector('#rv-redo'); if (u && r) { const v = versionsDe(h); u.disabled = v.k <= 0; r.disabled = v.k >= v.l.length - 1; u.onclick = () => { const v = versionsDe(h); if (v.k > 0) { v.k--; S.recitMoi[h] = v.l[v.k].html; journal('recit-version-precedente', { h }); tout(); } }; r.onclick = () => { const v = versionsDe(h); if (v.k < v.l.length - 1) { v.k++; S.recitMoi[h] = v.l[v.k].html; journal('recit-version-suivante', { h }); tout(); } }; }\n  const carte = mur.querySelector('.ed-carte'); if (carte) { const sc = (S.cahierScroll || {})[h] || 0; if (Math.abs(carte.scrollTop - sc) > 2) carte.scrollTop = sc; carte.onscroll = () => { S.cahierScroll = S.cahierScroll || {}; if (Math.abs((S.cahierScroll[h] || 0) - carte.scrollTop) < 2) return; S.cahierScroll[h] = carte.scrollTop; if (!S._scT) S._scT = setTimeout(() => { S._scT = null; pousser(etatComplet()); }, 60); }; }\n  const ed = mur.querySelector('#ed-edit');")
# la molette dans le cahier fait défiler la carte (pas les pages), sauf Ctrl (zoom)
rep("addEventListener('wheel', ev => { if (S.loupe || ev.ctrlKey) retur","addEventListener('wheel', ev => { if (ecran().role === 'fin' && !ev.ctrlKey) { const c = mur.querySelector('.ed-carte'); if (c) { c.scrollTop += ev.deltaY; ev.preventDefault(); } return; } if (S.loupe || ev.ctrlKey) retur")
# le tableau applique la position de défilement reçue
rep("  if (!et.pilote) h += `<span class=\"pt-cnx","  if (!et.pilote && et.cahier) setTimeout(() => { const c = mur.querySelector('.ed-carte'); if (c) c.scrollTop = et.cahier.scroll || 0; }, 0);\n  if (!et.pilote) h += `<span class=\"pt-cnx")
# la copie pour École Directe note l'heure (la garde après copie)
rep("rc.onclick = () => copier(document.querySelector('.recit').innerText.replace(","rc.onclick = () => { S.copieED = S.copieED || {}; S.copieED[S.heure] = { t: now(), quoi: 'contenu' }; journal('copie-ed', { quoi: 'contenu' }); } || copier(document.querySelector('.recit').innerText.replace(")
# la relecture : le même sélecteur (par heure) à la place de « figer »
rep("const rf = $('r-figer'); if (rf) rf.onclick = () => { S.recitFige = !S.recitFige; const r = document.querySelector('.recit'); if (S.recitFige) { S.recitFigeHtml = r.innerHTML; r.contentEditable = 'true'; r.style.outline = '2px dashed #c9a04a'; rf.textContent = 'Récit figé — tu le retouches à la main'; journal('recit-fige'); } else { r.contentEditable = 'false'; r.style.outline = ''; S.recitFigeHtml = null; relecture(); } };",
"const rf = $('r-figer'); if (rf) { const h = S.relHeure || S.heure; const v = (S.recitVersion || {})[h] || 'site'; rf.outerHTML = `<span class=\"rv\" style=\"font-size:.85rem\"><span class=\"${v === 'site' ? 'on' : ''}\" data-rv=\"site\">composé par le site</span><span class=\"${v === 'moi' ? 'on' : ''}\" data-rv=\"moi\">ma version (modifier)</span></span>`; $('rel').querySelectorAll('[data-rv]').forEach(b => b.onclick = () => basculerRecit(h, b.dataset.rv)); const r = document.querySelector('#rel .recit.ma-version'); if (r) { r.contentEditable = 'true'; r.oninput = () => { S.recitMoi[h] = r.innerHTML; if (!S._rvT) S._rvT = setTimeout(() => { S._rvT = null; poserVersion(h, r.innerHTML); journal('recit-modifie', { h }); }, 800); }; } }")
# ── 3. « Lancer l'animation en accéléré » (⚙) : l'heure se joue toute seule, chaque diapo tient sa durée prévue (l'horloge avance d'autant), jusqu'au cahier
rep('<button class="btn" id="s-inserer"','<button class="btn or" id="s-anim" title="Lance l\'animation en accéléré : l\'heure se joue toute seule, dévoile et avance de diapo en diapo, chaque diapo tenant sa durée prévue (l\'horloge avance d\'autant), jusqu\'au cahier de textes">Lancer l\'animation en accéléré</button> <button class="btn" id="s-inserer"')
rep("$('s-inserer').onclick = () => {", r"""$('s-anim').onclick = () => { $('fsimu').classList.remove('on'); if (S.anim) return; journal('animation-acceleree'); S.anim = setInterval(() => { if (!S.lancee || S.close) { clearInterval(S.anim); S.anim = null; return; } if (document.getElementById('garde-cahier').classList.contains('on')) { $('gc-aller').click(); clearInterval(S.anim); S.anim = null; return; } if (ecran().role === 'fin') { clearInterval(S.anim); S.anim = null; return; } const d = etatDiapo(); const n = elements(ecran()).length; if (d.nDev < n) { devoiler(); } else { /* la diapo est finie : l'horloge avance de sa durée prévue, puis la suivante */ const e = ecran(); const saut = (e.dur || 1) * 60000; DECALAGE += saut; S.ecoule += Math.floor(saut / 1000); tick(); allerSuivante(); } }, 350); };
$('s-inserer').onclick = () => {""")
rep("· v9c.14 c — <b>provisoire</b> : les durées par activité en (c), le récit en trois temps et « figer » en (d), Maj + P en (e), « Le chapitre » en (f) <span","· v9c.14 d — <b>provisoire</b> : Maj + P en (e), « Le chapitre » en (f) <span")
open(p,'w',encoding='utf-8').write(s); print("(d) écrit")
