p='vis/v9c14b3-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── 1. « Préparer le cahier de textes » / « Revenir au cours » (7.0 bis)
rep("function degeler(){", r"""function preparerCahier(){ if (S.preparation) return; const i = ordreHeure(S.heure).find(k => seance().ecrans[k].role === 'fin'); if (i == null) return; if (!S.gel) { journal('gel'); S.gel = etatComplet(); document.body.classList.add('gel'); $('bgel').classList.add('gelon'); } S.preparation = { di: S.gel.di, si: S.gel.si, vue: S.vueTableau }; S.vueTableau = true; journal('cahier-preparation'); S._parGardeCahier = true; S.di = i; S.page = null; S.doc = null; S._parGardeCahier = false; ouvrirFin(true); alerteFermer(); }
function revenirAuCours(){ if (!S.preparation) return; const pr = S.preparation; S.preparation = null; S.vueTableau = !!pr.vue; S.si = pr.si; S.di = pr.di; S.page = null; journal('cahier-preparation-fin'); if (S.gel) degeler(); else tout(); }
function degeler(){""")
rep('<div id="gc-apercu"', r"""<div class="garde" id="garde-clore" title="La garde à Clore : ce qui manque au cahier de textes, et ce que tu risques en clôturant quand même"><div class="boite" style="width:640px;border-color:var(--or)"><h3 style="margin:0 0 8px;color:var(--or);font-size:1.05rem">Il manque, avant de clore</h3><div id="gclore-corps"></div><div class="choix" style="justify-content:flex-end;margin-top:12px"><button class="btn" id="gclore-non">Y retourner</button><button class="btn or" id="gclore-oui">Clore quand même</button></div></div></div>
<div id="gc-apercu\"""")
s=s.replace('id="gc-apercu\\"','id="gc-apercu"')
# ── 2. la liste de contrôle, les étapes (7 sections), la garde à Clore
rep("function sequenceHtml(h, cloture, restantes){", r"""function controleCahier(restantes){ const h = S.heure; const dec = (restantes || []).every(x => { const d = S.decisions[x.a.id]; return d && !d.defaut; }); const travail = (texteTravail() || '').trim().length > 0 || !!(S.rienProchaine || {})[h]; const relu = !!(S.recitRelu || {})[h] || ((S.recitVersion || {})[h] === 'moi'); const absents = ELEVES.filter(e => (S.appel[e] || []).length); const copie = S.copieED && S.copieED[h] && S.copieED[h].contenu && S.copieED[h].travail;
  const etapes = [ { n: 1, lib: 'l\'échéance', ok: !!S.echeance || !!(S.finFaites || {})[1], risque: 'le cahier dira « la prochaine fois » : les élèves ne sauront pas pour quand' }, { n: 2, lib: 'ce qui reste' + ((restantes || []).length ? ' (' + (restantes || []).length + ' à décider)' : ''), ok: dec, risque: 'une activité restante sans décision glissera à l\'heure suivante par défaut' }, { n: 3, lib: 'le travail à faire', ok: travail, risque: 'rien dans École Directe ni dans l\'historique pour la prochaine fois' }, { n: 4, lib: 'le récit relu', ok: relu, risque: 'il partira tel quel dans l\'historique (et dans École Directe s\'il est copié)' }, { n: 5, lib: 'le mot aux absents' + (absents.length ? ' (' + absents.length + ')' : ' (aucun absent)'), ok: !absents.length || !!(S.motAbsents || '').trim(), facultatif: true, risque: 'les absents n\'auront pas de mot' }, { n: 6, lib: 'copié pour École Directe', ok: !!copie, risque: 'le cahier de textes de l\'école restera vide, à remplir à la main plus tard' }, { n: 7, lib: 'clore', ok: !!S.close, risque: '' } ];
  const prochaine = etapes.find(e => !e.ok && !e.facultatif) || etapes.find(e => !e.ok); return { etapes, prochaine }; }
function sequenceHtml(h, cloture, restantes){""")
# le corps de sequenceHtml : réorganiser en 7 sections ; les anciens résumés retirés
i0=s.index("  const resume1 = S.echeance ? '✔ ' + esc((DATA.classe.prochaines.find(x => x.iso === S.echeance) || {}).l || S.echeance) + ' — « Prenez vos agendas » est au tableau'"); j0=s.index("\n", i0); s=s[:i0]+s[j0+1:]
i=s.index("  const sec = (n, titre, corps, faite, resume) => {"); j=s.index("function ouvrirFin(cloture){")
new_seq = r"""  const sec = (n, titre, corps, faite, resume) => { const ouverte = S.finSection === n; return `<div class="sec${ouverte ? ' ouverte' : ''}${faite ? ' faite' : ''}" data-sec="${n}"><div class="tt"${!ouverte ? ' style="cursor:pointer"' : ''} data-ouvre="${n}">${n} · ${titre}${faite && !ouverte ? ' <span class="okr">' + resume + '</span>' : ''}</div>${ouverte ? corps : ''}</div>`; };
  const fleche = (n, ok) => `<div class="fleche${ok ? '' : ' grise'}" data-fleche="${n}" title="${ok ? 'Ouvre la section suivante' : 'La section précédente n\'est pas faite (tu peux quand même ouvrir la suivante par son titre)'}">▼</div>`;
  const ctl = controleCahier(restantes); const liste = `<div class="ctl" title="La liste de contrôle du cahier de textes : elle se coche toute seule ; un clic sur une ligne t'emmène au bon endroit">${ctl.etapes.map(e => `<div class="ctl-l${e.ok ? ' ok' : ''}${ctl.prochaine && ctl.prochaine.n === e.n ? ' ici' : ''}" data-ctl="${e.n}">${e.ok ? '✔' : '○'} ${esc(e.lib)}${e.facultatif ? ' <i>(facultatif)</i>' : ''}${ctl.prochaine && ctl.prochaine.n === e.n ? ' <b>— c\'est là que tu en es</b>' : ''}</div>`).join('')}</div>`;
  const tete = `<div class="seq-tete"><b>Fin de l'heure — dans l'ordre</b><span style="display:flex;gap:6px">${S.preparation ? '<button class="btn or" id="f-revenir" title="Te ramène à la diapo où la classe est restée, et dégèle le tableau">Revenir au cours</button>' : '<button class="btn" id="f-preparer" title="Gèle le tableau sur la diapo en cours, t\'emmène au cahier de textes et ouvre cette séquence : tu prépares tout pendant que la classe travaille">Préparer le cahier de textes</button>'}<button class="btn" id="f-fermer" title="Referme la colonne et reprend le cours ; rien n\'est fermé, tes choix restent">Reprendre le cours</button></span></div>`;
  const f = k => !!(S.finFaites || {})[k]; const e1 = ctl.etapes[0].ok, e2 = ctl.etapes[1].ok, e3 = ctl.etapes[2].ok, e4 = ctl.etapes[3].ok, e5 = ctl.etapes[4].ok, e6 = ctl.etapes[5].ok;
  const resume1 = S.echeance ? '✔ ' + esc((DATA.classe.prochaines.find(x => x.iso === S.echeance) || {}).l || S.echeance) : '✔ sans échéance'; const decs = (restantes || []).map(x => (S.decisions[x.a.id] || {}).choix).filter(Boolean); const resume2 = (restantes || []).length ? decs.map(c => ({ suivante: 'à l\'heure suivante', terminer: 'à la maison', preparer: 'à préparer', reserve: 'en réserve', nonfait: 'non fait', reporter: 'reportée', pastemps: 'à la maison', passee: 'passée' }[c] || c)).join(', ') : 'rien ne restait'; const resume3 = (S.rienProchaine || {})[S.heure] ? 'rien pour la prochaine fois' : esc((texteTravail() || '').trim().slice(0, 60)) + '…'; const resume4 = (S.recitVersion || {})[S.heure] === 'moi' ? 'ma version' : 'relu'; const resume5 = 'notes, versements, mot aux absents'; const resume6 = 'copié (contenu et travail)';
  const corps1 = `<div class="sous">Prenez vos agendas pour le… — la date part au tableau, dans le cahier de textes.</div>${out(echLabel)}<div style="margin-top:6px"><button class="btn" id="f-sans-ech" title="Pas d\'échéance donnée : le cahier dira « la prochaine fois »">Sans échéance</button></div>`;
  const corps2 = `${out(h3prevu)}${out(rangee)}`;
  const corps3 = `<div class="sous">Ce qui nourrit le travail à faire : ce que la trame prévoyait, les notions cochées, l\'activité à finir à la maison si tu l\'as décidé — et ce que tu écris toi-même (dans la colonne, ou dans la diapo du cahier).</div>${out(travail)}<div class="sous" style="margin-top:8px">Et pour la prochaine fois, rien d\'autre ? <button class="btn" id="f-rien" title="Rien à faire pour la prochaine fois : l\'étape est faite, en connaissance de cause">${(S.rienProchaine || {})[S.heure] ? '✔ rien pour la prochaine fois' : 'Rien pour la prochaine fois'}</button> <button class="btn" id="f-vers-travail" title="Va au champ du travail à faire, dans la diapo du cahier">Écrire dans le cahier ▸</button></div>`;
  const corps4 = `<div class="sous">Parcours le récit une fois (dans le cahier, onglet Contenus, ou dans la relecture) : l\'étape se coche quand tu as atteint le bout, ou d\'un clic.</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" id="f-vers-recit" title="Va au récit dans la diapo du cahier">Lire dans le cahier ▸</button><button class="btn" id="f-relu" title="Tu l\'as relu : l\'étape est faite">${e4 ? '✔ relu' : 'Relu'}</button></div>`;
  const corps5 = cloture ? out(avant) : '<div class="sous">(à la clôture)</div>';
  const corps6 = `<div class="sous">Copie, puis colle dans École Directe : d\'abord le contenu de séance, puis le travail à faire.</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" id="f-copie-contenu" title="Copie le récit pour le coller dans École Directe">${S.copieED && S.copieED[S.heure] && S.copieED[S.heure].contenu ? '✔ contenu copié' : 'Copier le contenu de séance'}</button><button class="btn" id="f-copie-travail" title="Copie le travail à faire en entier pour le coller dans École Directe">${S.copieED && S.copieED[S.heure] && S.copieED[S.heure].travail ? '✔ travail copié' : 'Copier le travail à faire'}</button><span id="f-copie-etat" style="color:var(--texte2);font-size:.85rem"></span></div>`;
  const corps7 = out(barre);
  return `<div class="seq">` + tete + liste + sec(1, 'L\'échéance', corps1, e1, resume1) + fleche(2, e1) + sec(2, 'Ce qui reste', corps2, e2, resume2) + fleche(3, e2) + sec(3, 'Le travail à faire', corps3, e3, resume3) + fleche(4, e3) + sec(4, 'Le récit relu', corps4, e4, resume4) + fleche(5, e4) + sec(5, 'Avant de clore', corps5, f(5), resume5) + fleche(6, f(5)) + sec(6, 'Copier pour École Directe', corps6, e6, resume6) + fleche(7, e6) + sec(7, 'Clore l\'heure', corps7, false, '') + `</div>`; }
"""
s=s[:i]+new_seq+s[j:]
# les branchements : tout titre ouvre sa section ; les nouveaux boutons ; la garde à Clore
rep("  $('fin').querySelectorAll('[data-ouvre]').forEach(t => t.onclick = () => { const n = +t.dataset.ouvre; if (n === S.finSection) return; if (n < S.finSection || S.finFaites[n - 1] || n === 1) { S.finSection = n; ouvrirFin(cloture); } });",
r"""  $('fin').querySelectorAll('[data-ouvre]').forEach(t => t.onclick = () => { const n = +t.dataset.ouvre; if (n === S.finSection) return; S.finSection = n; ouvrirFin(cloture); });
  $('fin').querySelectorAll('[data-ctl]').forEach(l => l.onclick = () => { const n = +l.dataset.ctl; S.finSection = n; ouvrirFin(cloture); });
  const fpr = $('f-preparer'); if (fpr) fpr.onclick = preparerCahier; const frv = $('f-revenir'); if (frv) frv.onclick = revenirAuCours;
  const frn = $('f-rien'); if (frn) frn.onclick = () => { S.rienProchaine = S.rienProchaine || {}; S.rienProchaine[S.heure] = !S.rienProchaine[S.heure]; journal('rien-prochaine-fois', { h: S.heure, valeur: S.rienProchaine[S.heure] }); ouvrirFin(cloture); };
  const fvt = $('f-vers-travail'); if (fvt) fvt.onclick = () => { allerAuCahier('travail'); }; const fvr = $('f-vers-recit'); if (fvr) fvr.onclick = () => { allerAuCahier('contenu'); };
  const frl = $('f-relu'); if (frl) frl.onclick = () => { S.recitRelu = S.recitRelu || {}; S.recitRelu[S.heure] = true; journal('recit-relu', { h: S.heure, par: 'clic' }); ouvrirFin(cloture); };
  const fcc = $('f-copie-contenu'); if (fcc) fcc.onclick = () => { S.copieED = S.copieED || {}; S.copieED[S.heure] = Object.assign(S.copieED[S.heure] || {}, { t: now(), contenu: true }); journal('copie-ed', { quoi: 'contenu' }); const d = document.createElement('div'); d.innerHTML = recitPourED(S.heure); copierTexte(d.textContent, 'copié : le contenu de séance'); ouvrirFin(cloture); };
  const fct = $('f-copie-travail'); if (fct) fct.onclick = () => { S.copieED = S.copieED || {}; S.copieED[S.heure] = Object.assign(S.copieED[S.heure] || {}, { t: now(), travail: true }); journal('copie-ed', { quoi: 'travail' }); copierTexte(texteTravail() || '(rien à faire)', 'copié : le travail à faire'); ouvrirFin(cloture); };""")
rep("function ouvrirFin(cloture){", r"""function allerAuCahier(onglet){ const i = ordreHeure(S.heure).find(k => seance().ecrans[k].role === 'fin'); if (i == null) return; S.finVue = onglet; if (S.di !== i) { if (S.gel || S.preparation) { S._parGardeCahier = true; S.di = i; S.page = null; S._parGardeCahier = false; tout(); } else aller(i); } else tout(); setTimeout(() => { const c = document.querySelector(onglet === 'travail' ? '#mur #ed-edit' : '#mur .ed-recit'); if (c && onglet === 'travail') c.focus(); }, 80); }
function copierTexte(txt, ok){ const dire = m => { const z = $('f-copie-etat') || $('r-copie-etat'); if (z) z.textContent = m; }; if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(txt).then(() => dire(ok)).catch(() => dire('copie impossible ici')); else dire('copie impossible ici'); }
function manquesAvantDeClore(restantes){ return controleCahier(restantes).etapes.filter(e => !e.ok && e.n < 7); }
function ouvrirFin(cloture){""")
# le récit relu par le défilement (une fois, au fond) ; « ma version » coche
rep("S.cahierScroll[h] = ratio; if (!S._scT)","S.cahierScroll[h] = ratio; if (ratio >= 0.97 && !(S.recitRelu || {})[h] && S.finVue === 'contenu') { S.recitRelu = S.recitRelu || {}; S.recitRelu[h] = true; journal('recit-relu', { h, par: 'défilement' }); if (S.enFin) setTimeout(() => ouvrirFin(true), 100); } if (!S._scT)")
# la garde à Clore : au clic sur Clore, ce qui manque et les risques
rep("const fc = $('f-clore'); if (fc) fc.onclick = () => {", r"""const fc = $('f-clore'); if (fc) fc.onclick = () => { const manques = manquesAvantDeClore(restantes); if (manques.length && !S._cloreQuandMeme) { $('gclore-corps').innerHTML = manques.map(m => `<div class="gc-l"><span class="gc-n">○</span><span><b>${esc(m.lib)}</b>${m.facultatif ? ' (facultatif)' : ''} — ${esc(m.risque)}</span></div>`).join(''); $('garde-clore').classList.add('on'); $('gclore-non').onclick = () => { $('garde-clore').classList.remove('on'); S.finSection = manques[0].n; ouvrirFin(cloture); }; $('gclore-oui').onclick = () => { $('garde-clore').classList.remove('on'); journal('clore-quand-meme', { manques: manques.map(m => m.lib) }); S._cloreQuandMeme = true; fc.click(); S._cloreQuandMeme = false; }; $('gclore-non').focus(); return; }""")
# les copies faites depuis la relecture comptent aussi ; la relecture : « ma version » coche relu
rep("rc.onclick = () => { S.copieED = S.copieED || {}; S.copieED[S.heure] = { t: now(), quoi: 'contenu' }; journal('copie-ed', { quoi: 'contenu' });","rc.onclick = () => { S.copieED = S.copieED || {}; S.copieED[S.heure] = Object.assign(S.copieED[S.heure] || {}, { t: now(), contenu: true }); journal('copie-ed', { quoi: 'contenu' });")
rep("const rt = $('r-copie-travail'); if (rt) rt.onclick = () => copier(texteTravail() || '(rien à faire)', 'copié : le travail à faire');","const rt = $('r-copie-travail'); if (rt) rt.onclick = () => { S.copieED = S.copieED || {}; S.copieED[S.heure] = Object.assign(S.copieED[S.heure] || {}, { t: now(), travail: true }); journal('copie-ed', { quoi: 'travail' }); copier(texteTravail() || '(rien à faire)', 'copié : le travail à faire'); };")
# l'alerte T-5 : « Préparer le cahier de textes » en plus
rep('<button class="btn or" id="al-aller" title="Va au cahier de textes — après la garde (ce qui resterait non fait), puis « Y aller »">Aller au cahier de textes</button>','<button class="btn" id="al-preparer" title="Gèle le tableau sur la diapo en cours et t\'emmène préparer le cahier de textes (échéance, travail, récit) pendant que la classe termine">Préparer le cahier de textes</button><button class="btn or" id="al-aller" title="Va au cahier de textes — après la garde (ce qui resterait non fait), puis « Y aller »">Aller au cahier de textes</button>')
rep("$('al-tard').onclick = () => alerteReplier();","$('al-tard').onclick = () => alerteReplier(); $('al-preparer').onclick = () => { if (document.querySelector('.garde.on')) return; preparerCahier(); };")
rep(".gc-l{display:flex;", r""".ctl{background:#151109;border:1px solid var(--bord);border-radius:8px;padding:6px 10px;font-size:.86rem;line-height:1.5}.ctl-l{cursor:pointer;color:var(--texte2)}.ctl-l.ok{color:var(--joue)}.ctl-l.ici{color:var(--or)}.ctl-l:hover{text-decoration:underline}
.gc-l{display:flex;""")
rep("· v9c.14 d5 — <b>provisoire</b>","· v9c.14 b3 — <b>provisoire</b>")
open(p,'w',encoding='utf-8').write(s); print("(b3) écrit")
