p='vis/v9c14b4-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (b4-1) LA PRÉPARATION : disposition (poignée sous la diapo, notes réduites, volet réduit), le pas à pas, seul « Revenir » dégèle, le cahier entier sans dévoiler, la préparation gardée
# 1. le HTML : la poignée sous la barre d'outils, la zone de préparation avant les notes
rep('<div id="al-boite" class="al-boite" style="display:none">','<div id="poignee-mur" class="poignee-mur" title="Tire vers le haut pour agrandir la diapo, vers le bas pour donner la place à la préparation (comme PowerPoint)"><span></span></div><div id="prep" class="prep" style="display:none"></div><div id="al-boite" class="al-boite" style="display:none">')
# 2. dimensionner : la part de hauteur de la diapo (la poignée)
rep("const hDispo = sc.clientHeight - outils; const part = S.vue || 1;","const hDispo = (sc.clientHeight - outils) * (S.murPart || 1); const part = S.vue || 1;")
# 3. le CSS
rep("\n.mur .ed-part{", r"""
/* (b4) la préparation du cahier de textes (7.0 ter) : la poignée, la zone de préparation sous la diapo, les notes réduites, le volet réduit, le pas à pas */
.poignee-mur{display:none;height:12px;cursor:row-resize;align-items:center;justify-content:center}.poignee-mur span{width:120px;height:6px;border-radius:3px;background:var(--bord2)}.poignee-mur:hover span{background:var(--or)}.corps.prep .poignee-mur{display:flex}
.corps.prep .volet .vig .mini{display:none}.corps.prep .volet .vig{padding:2px 4px}.corps.prep .volet .vig .n{font-size:.9rem}
.notes.reduites{flex:0 0 26px;min-height:26px;height:26px;overflow:hidden;padding:3px 12px;font-size:.75rem;color:var(--sourd)}.notes.reduites h5{margin:0;display:inline}.notes.reduites > *:not(h5){display:none}
.prep{background:var(--carte);border:1px solid var(--or);border-radius:10px;padding:8px 12px;flex:1 1 auto;min-height:0;overflow:auto}
.pp{display:grid;grid-template-columns:1fr 250px;gap:14px}.pp-tete{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:4px}.pp-tete b{color:var(--or)}.pp-fil{display:flex;gap:4px;margin:4px 0 8px}.pp-fil span{flex:1;height:6px;border-radius:3px;background:var(--bord2)}.pp-fil span.ok{background:var(--joue)}.pp-fil span.ici{background:var(--or)}.pp-quoi{font-size:.9rem;color:var(--texte2);margin-bottom:6px}.pp-nav{display:flex;justify-content:space-between;gap:8px;margin-top:10px}.pp-liste{font-size:.8rem;color:var(--texte2);line-height:1.5;border-left:1px dotted var(--bord2);padding-left:12px}.pp-liste .ctl-l{cursor:pointer}.pp-liste .ctl-l.ok{color:var(--joue)}.pp-liste .ctl-l.ici,.pp-liste .sec.ouverte .ctl-l{color:var(--or);font-weight:600}.pp-liste .okr{display:block;font-weight:400;color:var(--joue);font-size:.75rem}.pp-attente{background:#2a2114;border:1px solid #c99a4e;border-radius:8px;padding:6px 10px;color:#e0c48c;font-size:.88rem;margin:4px 0 8px}
#fin .pp{grid-template-columns:1fr}#fin .pp-liste{border-left:0;padding-left:0;border-top:1px dotted var(--bord2);padding-top:6px;margin-top:8px}
.mur .ed-part{""")
# 4. le pas à pas remplace sequenceHtml (mêmes identifiants, une étape à la fois)
i=s.index("function sequenceHtml(h, cloture, restantes){"); j=s.index("function ouvrirFin(cloture){")
new_seq = r"""function sequenceHtml(h, cloture, restantes){ /* (b4) 7.0 bis/ter : le pas à pas — une étape à la fois, ce qu'il faut y faire, ses contrôles, deux boutons ; le fil ; la liste des sept, cliquable */
  const tmp = document.createElement('div'); tmp.innerHTML = h; const q = sel => tmp.querySelector(sel); const out = n => (n ? n.outerHTML : '');
  const echLabel = tmp.querySelector('#f-ech') ? tmp.querySelector('#f-ech').closest('label') : null; if (echLabel) echLabel.remove(); const travaux = tmp.querySelectorAll('.travail'); const travail = travaux[0]; const avant = tmp.querySelector('#f-mot') ? tmp.querySelector('#f-mot').closest('.travail') : null; const rangee = q('.rangee'); const h3prevu = tmp.querySelector('h3'); const barre = q('.barre-fin'); tmp.querySelectorAll('[data-finvue]').forEach(x => x.parentElement.remove());
  S.finSection = S.finSection || 1; S.finFaites = S.finFaites || {}; const ctl = controleCahier(restantes); const E = ctl.etapes; const n = S.finSection; const et = E[n - 1]; const hh = S.heure; const nbF = E.filter(e => e.ok && e.n < 7).length;
  const TITRES = { 1: 'l\'échéance', 2: 'ce qui reste', 3: 'le travail à faire', 4: 'le récit relu', 5: 'avant de clore', 6: 'copier pour École Directe', 7: 'clore l\'heure' };
  const resume = { 1: S.echeance ? '✔ ' + esc((DATA.classe.prochaines.find(x => x.iso === S.echeance) || {}).l || S.echeance) : ((S.finFaites || {})[1] ? '✔ sans échéance' : ''), 2: (restantes || []).length ? (restantes || []).map(x => (S.decisions[x.a.id] || {}).choix).filter(Boolean).map(c => ({ suivante: 'à l\'heure suivante', terminer: 'à la maison', preparer: 'à préparer', reserve: 'en réserve', nonfait: 'non fait', reporter: 'reportée', pastemps: 'à la maison', passee: 'passée' }[c] || c)).join(', ') : 'rien ne restait', 3: (S.rienProchaine || {})[hh] ? 'rien pour la prochaine fois' : esc((texteTravail() || '').trim().slice(0, 50)) + '…', 4: (S.recitVersion || {})[hh] === 'moi' ? 'ma version' : 'relu', 5: 'notes, versements, mot aux absents', 6: 'copié (contenu et travail)', 7: '' };
  const QUOI = { 1: 'Prenez vos agendas pour le… — la date part au tableau, dans le cahier de textes. Choisis-la, ou dis « sans échéance ».', 2: 'Ce qui était prévu pour cette heure et n\'a pas été fait : une décision par activité (à l\'heure suivante, à la maison, à préparer, en réserve, non fait).', 3: 'Ce que les élèves auront à faire. Déjà là : ce que la trame prévoyait, les notions cochées, l\'activité à finir à la maison si tu l\'as décidé. Ajoute ce que tu veux, ou dis qu\'il n\'y a rien d\'autre.', 4: 'Parcours le récit une fois (dans le cahier, onglet Contenus, ou dans la relecture) ; l\'étape se coche quand tu as atteint le bout du récit final, ou d\'un clic.', 5: 'Les notes à garder, ce qui se verse dans la trame, le mot aux absents.', 6: 'Copie, puis colle dans École Directe : d\'abord le contenu de séance, puis le travail à faire.', 7: 'Clore ferme l\'heure : le journal, le récit, le travail à faire et le mot des absents sont enregistrés pour cette classe.' };
  const corps = {};
  corps[1] = `${out(echLabel)}<div style="margin-top:6px"><button class="btn" id="f-sans-ech" title="Pas d\'échéance donnée : le cahier dira « la prochaine fois »">Sans échéance</button></div>`;
  corps[2] = `${out(h3prevu)}${out(rangee)}`;
  corps[3] = `${out(travail)}<div style="margin-top:8px;display:flex;gap:8px;flex-wrap:wrap"><button class="btn" id="f-rien" title="Rien à faire pour la prochaine fois : l\'étape est faite, en connaissance de cause">${(S.rienProchaine || {})[hh] ? '✔ rien pour la prochaine fois' : 'Rien d\'autre pour la prochaine fois'}</button><button class="btn" id="f-vers-travail" title="Va au champ du travail à faire, dans la diapo du cahier">Écrire dans le cahier ▸</button></div>`;
  const recitFinal = !!S.close || (ecran().role === 'fin' && !S.preparation); corps[4] = `${recitFinal ? '' : `<div class="pp-attente">Il est ${hhmm()} : <b>le récit se complète jusqu\'à la fin de l\'heure</b> — ce que tu lis maintenant n\'est pas encore ce qui partira. Tu peux le lire et le retoucher (ma version), l\'étape ne se cochera qu\'une fois l\'heure jouée et le récit relu à la fin.</div>`}<div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" id="f-vers-recit" title="Va au récit dans la diapo du cahier">Lire dans le cahier ▸</button><button class="btn" id="f-relu" ${recitFinal ? '' : 'disabled '}title="${recitFinal ? 'Tu l\'as relu : l\'étape est faite' : 'À relire à la fin de l\'heure : le récit n\'est pas fini'}">${et && E[3].ok ? '✔ relu' : (recitFinal ? 'Relu' : 'Relu (à la fin de l\'heure)')}</button></div>`;
  corps[5] = cloture ? out(avant) : '<div class="sous">(à la clôture)</div>';
  corps[6] = `<div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" id="f-copie-contenu" title="Copie le récit pour le coller dans École Directe">${S.copieED && S.copieED[hh] && S.copieED[hh].contenu ? '✔ contenu copié' : 'Copier le contenu de séance'}</button><button class="btn" id="f-copie-travail" title="Copie le travail à faire en entier pour le coller dans École Directe">${S.copieED && S.copieED[hh] && S.copieED[hh].travail ? '✔ travail copié' : 'Copier le travail à faire'}</button><span id="f-copie-etat" style="color:var(--texte2);font-size:.85rem"></span></div>`;
  corps[7] = out(barre);
  const tete = `<div class="pp-tete"><b>${S.preparation ? 'Préparer le cahier de textes' : 'Fin de l\'heure'} — étape ${n} sur 7 : ${TITRES[n]}</b><span style="display:flex;gap:6px">${S.preparation ? '<button class="btn or" id="f-revenir" title="Te ramène à la diapo où la classe est restée, et dégèle le tableau — c\'est le seul geste qui dégèle">Revenir au cours</button>' : '<button class="btn" id="f-preparer" title="Gèle le tableau sur la diapo en cours, t\'emmène au cahier de textes et ouvre la préparation sous la diapo : tu prépares tout pendant que la classe travaille">Préparer le cahier de textes</button><button class="btn" id="f-fermer" title="Referme la colonne et reprend le cours ; rien n\'est fermé, tes choix restent">Reprendre le cours</button>'}</span></div>`;
  const fil = `<div class="pp-fil">${E.map(e => `<span class="${e.ok ? 'ok' : ''}${e.n === n ? ' ici' : ''}"></span>`).join('')}</div>`;
  const etape = `<div class="sec ouverte" data-sec="${n}"><div class="pp-quoi">${QUOI[n]}</div>${corps[n]}</div>`;
  const nav = `<div class="pp-nav"><span><button class="btn" id="f-precedente" ${n <= 1 ? 'disabled ' : ''}title="L\'étape précédente">◀ Étape précédente</button></span><button class="btn or" id="f-suivante" data-fleche="${Math.min(7, n + 1)}" ${n >= 7 ? 'disabled ' : ''}${et && !et.ok && !et.facultatif ? ' class="btn or grise"' : ''} title="${et && !et.ok ? 'L\'étape en cours n\'est pas faite — tu peux quand même passer à la suivante' : 'L\'étape suivante'}">Étape suivante ▶${n < 7 ? ' (' + TITRES[n + 1] + ')' : ''}</button></div>`;
  const liste = `<div class="pp-liste" title="La liste de contrôle : elle se coche toute seule ; un clic sur une ligne ouvre l\'étape">${E.map(e => `<div class="sec${e.n === n ? ' ouverte' : ''}${e.ok ? ' faite' : ''}" data-sec="${e.n}"><span class="ctl-l${e.ok ? ' ok' : ''}${ctl.prochaine && ctl.prochaine.n === e.n ? ' ici' : ''}" data-ctl="${e.n}" data-ouvre="${e.n}">${e.ok ? '✔' : (e.n === n ? '▶' : '○')} ${e.n} · ${esc(e.lib)}${e.facultatif ? ' <i>(facultatif)</i>' : ''}${e.n === 4 && !e.ok && !recitFinal ? ' — <i>à relire à la fin de l\'heure</i>' : ''}${e.ok && e.n !== n && resume[e.n] ? '<span class="okr">' + resume[e.n] + '</span>' : ''}</span></div>`).join('')}<div style="margin-top:6px;color:var(--sourd);font-size:.75rem">${nbF} étape${nbF > 1 ? 's' : ''} faite${nbF > 1 ? 's' : ''} sur 6${ctl.prochaine ? ' — c\'est là que tu en es : ' + ctl.prochaine.n : ''}</div></div>`;
  return `<div class="seq">${tete}<div class="pp"><div>${fil}${etape}${nav}</div>${liste}</div></div>`; }
"""
s=s[:i]+new_seq+s[j:]
# 5. ouvrirFin : la zone de rendu (la colonne, ou la zone sous la diapo en préparation) ; les branchements : suivante / précédente
rep("  const scrollAvant = $('droite').scrollTop; poserHtml($('fin'), h);","  const zone = S.preparation ? $('prep') : $('fin'); if (S.preparation) { $('prep').style.display = 'block'; $('droite').classList.remove('fin'); } else { $('prep').style.display = 'none'; }\n  const scrollAvant = $('droite').scrollTop; poserHtml(zone, h); if (S.preparation) { if ($('fin').innerHTML) poserHtml($('fin'), ''); }")
rep("  $('fin').querySelectorAll('[data-ouvre]').forEach(t => t.onclick = () => { const n = +t.dataset.ouvre; if (n === S.finSection) return; S.finSection = n; ouvrirFin(cloture); });","  const Z = S.preparation ? $('prep') : $('fin'); Z.querySelectorAll('[data-ouvre]').forEach(t => t.onclick = () => { const n = +t.dataset.ouvre; if (n === S.finSection) return; S.finSection = n; ouvrirFin(cloture); });\n  const fsv = $('f-suivante'); if (fsv) fsv.onclick = () => { if (S.finSection < 7) { S.finFaites[S.finSection] = S.finFaites[S.finSection] || (S.finSection === 5); S.finSection++; journal('fin-section', { n: S.finSection }); ouvrirFin(cloture); } }; const fpv = $('f-precedente'); if (fpv) fpv.onclick = () => { if (S.finSection > 1) { S.finSection--; ouvrirFin(cloture); } };")
rep("  $('fin').querySelectorAll('[data-fleche]').forEach(f => f.onclick = () => { if (f.classList.contains('grise')) return; const n = +f.dataset.fleche; S.finFaites[n - 1] = true; if (n === 3) S.finFaites[3] = true; /* « avant de clore » est faite dès qu'elle est vue : rien n'y est obligatoire */ S.finSection = n; journal('fin-section', { n }); ouvrirFin(cloture); });","")
rep("  $('fin').querySelectorAll('[data-ctl]').forEach(l => l.onclick = () => { const n = +l.dataset.ctl; S.finSection = n; ouvrirFin(cloture); });","")
# le reste des $('fin').querySelectorAll → la zone
s=s.replace("$('fin').querySelectorAll('[data-c]')","Z.querySelectorAll('[data-c]')").replace("$('fin').querySelectorAll('[data-notion]')","Z.querySelectorAll('[data-notion]')").replace("$('fin').querySelectorAll('[data-verse]')","Z.querySelectorAll('[data-verse]')").replace("$('fin').querySelectorAll('[data-verse-duree]')","Z.querySelectorAll('[data-verse-duree]')").replace("$('fin').querySelectorAll('[data-e]')","Z.querySelectorAll('[data-e]')")
# 6. preparerCahier / revenirAuCours : la disposition ; le compteur ; devoiler ; gel ; clore
rep("function preparerCahier(){ if (S.preparation) return;","function preparerCahier(){ if (S.preparation) return; S.dispoAvant = { lg: S.lg, murPart: S.murPart || 1, notes: !!S.notesReduites, vue: S.vueTableau }; S.lg = 64; S.murPart = 0.58; S.notesReduites = true; $('corps').classList.add('prep'); document.querySelector('.notes').classList.add('reduites'); poserColonnes();")
rep("S.preparation = { di: S.gel.di, si: S.gel.si, vue: S.vueTableau }; S.vueTableau = true;","S.preparation = { di: S.gel.di, si: S.gel.si }; S.vueTableau = true;")
rep("const pr = S.preparation; S.preparation = null; S.vueTableau = !!pr.vue; S.si = pr.si; S.di = pr.di; S.page = null;","const pr = S.preparation; S.preparation = null; const d0 = S.dispoAvant || {}; S.lg = d0.lg || 186; S.murPart = d0.murPart || 1; S.notesReduites = !!d0.notes; S.vueTableau = !!d0.vue; $('corps').classList.remove('prep'); document.querySelector('.notes').classList.toggle('reduites', S.notesReduites); poserColonnes(); $('prep').style.display = 'none'; S.si = pr.si; S.di = pr.di; S.page = null; try { dimensionner(); } catch (e) {}")
rep("function tout(){","function tout(){ if (S.preparation) { try { dimensionner(); } catch (e) {} }")
rep("compte').textContent = elements(e).length ? `${etatDiapo().nDev} / ${elements(e).length} dévoilés`","compte').textContent = (S.preparation && e.role === 'fin') ? 'préparation — rien n\\'est montré à la classe' : elements(e).length ? `${etatDiapo().nDev} / ${elements(e).length} dévoilés`")
rep("function devoiler(){ if (ecran().role === 'fin') {","function devoiler(){ if (S.preparation) return; /* en préparation, rien ne se dévoile : le cahier se joue avec la classe */ if (ecran().role === 'fin') {")
rep("function gel(){ if (S.gel) {","function gel(){ if (S.preparation) { $('bgel').title = 'En préparation : reviens au cours d\\'abord (« Revenir au cours »)'; journal('gel-refuse-preparation'); return; } if (S.gel) {")
rep("const fc = $('f-clore'); if (fc) fc.onclick = () => { const manques = manquesAvantDeClore(restantes); if (manques.length && !S._cloreQuandMeme) {","const fc = $('f-clore'); if (fc) fc.onclick = () => { if (S.preparation) { $('gclore-corps').innerHTML = `<div class=\"gc-l\"><span class=\"gc-n\">❄</span><span>Tu prépares le cahier : la classe est encore sur la diapo ${rangeDe(S.preparation.di)} — <b>reviens au cours</b> (« Revenir au cours »), puis clos.</span></div>`; $('garde-clore').classList.add('on'); $('gclore-oui').style.display = 'none'; $('gclore-non').textContent = 'Compris'; $('gclore-non').onclick = () => { $('garde-clore').classList.remove('on'); $('gclore-oui').style.display = ''; $('gclore-non').textContent = 'Y retourner'; }; return; } const manques = manquesAvantDeClore(restantes); if (manques.length && !S._cloreQuandMeme) {")
# le cahier entier en préparation (rendu), sans dévoiler
rep("else if (b0 && b0.t === 'cahier' && et.cahier) { const f = et.cahier; const nd = et.nDev || 0;","else if (b0 && b0.t === 'cahier' && et.cahier) { const f = et.cahier; const nd = (et.pilote && et.preparation) ? 4 : (et.nDev || 0);")
rep("return { onglet: S.finVue || 'travail', grand:","return { onglet: S.finVue || 'travail', prepa: !!S.preparation, grand:")
rep("const etatComplet = () => { S.eidCourant = ecran().eid; co","const etatComplet = () => { S.eidCourant = ecran().eid; const __p = !!S.preparation; co")
# la poignée sous la diapo
rep("(function glisserAlerte(){", r"""(function poigneeMur(){ const pg = $('poignee-mur'); let dep = null; pg.addEventListener('mousedown', ev => { ev.preventDefault(); const sc = document.querySelector('.scene'); dep = { y: ev.clientY, part: S.murPart || 1, h: sc.clientHeight }; document.body.style.cursor = 'row-resize'; const move = e => { if (!dep) return; const d = (e.clientY - dep.y) / dep.h; S.murPart = Math.max(0.3, Math.min(1, dep.part + d * 1.6)); try { dimensionner(); } catch (x) {} }; const up = () => { dep = null; document.body.style.cursor = ''; document.removeEventListener('mousemove', move); document.removeEventListener('mouseup', up); journal('poignee-diapo', { part: Math.round((S.murPart || 1) * 100) }); tout(); }; document.addEventListener('mousemove', move); document.addEventListener('mouseup', up); }); })();
(function glisserAlerte(){""")
rep("· v9c.14 b3 — <b>provisoire</b>","· v9c.14 b4 — <b>provisoire</b>")
open(p,'w',encoding='utf-8').write(s); print("(b4-1) écrit")
