p='vis/v9c14b5-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── A. « Montrer cette suite à la classe » (7.0 ter) : sous la vignette, en préparation seulement
rep("function preparerCahier(){", r"""function suitePourLaClasse(){ /* ce qui serait montré à la classe sur la diapo où elle est (le gel), ou sa diapo suivante ; jamais le cahier de textes */ if (!S.preparation || !S.gel) return null; const E = seance().ecrans; const gi = S.gel.di; const e = E[gi]; const els = elements(e); const nd = S.gel.nDev || 0; if (nd < els.length) return { genre: 'element', di: gi, k: nd, txt: els[nd].txt, lib: 'la suite sur leur diapo' }; const o = ordreHeure(S.heure); const k = o.indexOf(gi); const suiv = o.slice(k + 1).find(i => !retiree(E[i])); if (suiv == null) return { genre: 'rien' }; if (E[suiv].role === 'fin') return { genre: 'cahier' }; return { genre: 'diapo', di: suiv, titre: E[suiv].act, rang: rangDe(suiv) }; }
function montrerSuite(){ const su = suitePourLaClasse(); if (!su || su.genre === 'rien' || su.genre === 'cahier') return; const E = seance().ecrans; if (su.genre === 'element') { S.gel.nDev = (S.gel.nDev || 0) + 1; const k = K(su.di); vuMax[k] = Math.max(vuMax[k] || 0, S.gel.nDev); journal('devoile', { si: S.si, di: su.di, k: S.gel.nDev - 1, depuisPreparation: true }); journal('montre-depuis-preparation', { di: su.di, k: S.gel.nDev - 1 }); } else { const di0 = S.di; S.di = su.di; S.page = null; const et = etatComplet(); S.di = di0; et.nDev = Math.max(et.nDev || 0, 0); S.gel = et; S.preparation.di = su.di; journal('diapo', { si: S.si, di: su.di, eid: E[su.di].eid, deja: 0, nature: 'suivante', depuisPreparation: true }); journal('montre-depuis-preparation', { di: su.di, diapo: true }); } pousser(S.gel); tout(); }
function preparerCahier(){""")
# le rendu : sous le titre de la vignette (vueDroite) — une ligne + un bouton, en préparation seulement
rep("function vueDroite(et){","function ligneSuite(){ const z = $('pv-suite'); if (!z) return; const su = suitePourLaClasse(); if (!su) { z.style.display = 'none'; return; } z.style.display = 'block'; if (su.genre === 'element') z.innerHTML = `<span>Pour les élèves qui ont fini, ${su.lib} : <b>${esc(su.txt)}</b></span><button class=\"btn or\" id=\"pv-montrer\" title=\"Exceptionnel : montre cet élément à la classe sur la diapo où elle est, sans quitter ta préparation. Ça compte pour la classe (journal, récit, temps), pas pour le cahier. Jamais au-delà de la diapo suivante, jamais le cahier de textes.\">Montrer cette suite à la classe</button>`; else if (su.genre === 'diapo') z.innerHTML = `<span>Leur diapo est finie — la suite serait la diapo ${su.rang} : <b>${esc(su.titre)}</b></span><button class=\"btn or\" id=\"pv-montrer\" title=\"Passe la classe à sa diapo suivante, sans quitter ta préparation. Ça compte pour la classe. Jamais le cahier de textes.\">Passer la classe à la diapo ${su.rang}</button>`; else if (su.genre === 'cahier') z.innerHTML = `<span>Leur diapo est finie — la suite serait le cahier de textes, qui se joue avec la classe : <b>reviens au cours</b>.</span>`; else z.innerHTML = `<span>Leur diapo est finie ; rien après dans cette heure.</span>`; const b = $('pv-montrer'); if (b) b.onclick = montrerSuite; }\nfunction vueDroite(et){")
rep("function tout(){","function tout(){ try { ligneSuite(); } catch (e) {}")
rep('<div class="garde" id="garde-copie"','<div class="garde" id="garde-copie"')  # ancrage inchangé
# le HTML : la ligne sous la vignette (dans .suivante, après suiv-titre)
s=s.replace('id="suiv-titre"','id="suiv-titre"',1)
i=s.index('id="suiv-titre"'); j=s.index('</div>', i); s=s[:j+6]+'<div id="pv-suite" class="pv-suite" style="display:none"></div>'+s[j+6:]
rep("\n.mur .ed-part{", r"""
.pv-suite{margin-top:6px;background:#151109;border:1px dashed #6b5230;border-radius:8px;padding:6px 10px;font-size:.82rem;color:var(--texte2)}.pv-suite b{color:var(--texte)}.pv-suite .btn{margin-top:6px;display:block;width:100%;white-space:normal}
.mur .ed-suite{margin-top:.6em;border-top:.12em dashed #9fb4c8;padding-top:.4em;color:#3d4f63;background:#f3f7fb}.mur .ed-suite .ed-suite-t{font-size:.75em;color:#0f8fd1;font-style:italic;margin-bottom:.2em}.recit .ed-suite{margin-top:12px;border-top:1px dashed #6b5230;padding-top:8px}.recit .ed-suite .ed-suite-t{font-size:.85rem;color:var(--or);font-style:italic}
.mur .ed-part{""")
# ── B. le récit au fil de l'heure (2 · 3.8) : ma version + la suite composée depuis la prise de plume ; reprendre ; relu seulement à la fin, décoché si l'heure continue
rep("function troisTemps(html, h, fin){","function troisTemps(html, h, fin, depuis){")
rep("const JH = J.filter(x => x.h === h && x.type === 'diapo' && E[x.di] && !E[x.di].role).sort((x, y) => x.t - y.t); if (!JH.length) return html;","const JH = J.filter(x => x.h === h && x.type === 'diapo' && E[x.di] && !E[x.di].role && (!depuis || x.t >= depuis)).sort((x, y) => x.t - y.t); if (!JH.length) return depuis ? '' : html;")
rep("function poserVersion(h, html){ const v = versionsDe(h); v.l = v.l.slice(0, v.k + 1); v.l.push({ t: now(), html }); v.k = v.l.length - 1; S.recitMoi = S.recitMoi || {}; S.recitMoi[h] = html; }","function poserVersion(h, html){ const v = versionsDe(h); v.l = v.l.slice(0, v.k + 1); v.l.push({ t: now(), html }); v.k = v.l.length - 1; S.recitMoi = S.recitMoi || {}; S.recitMoi[h] = html; S.recitMoiT = S.recitMoiT || {}; if (!S.recitMoiT[h]) S.recitMoiT[h] = now(); }\nfunction suiteDepuis(h){ /* ce que le site a composé depuis la prise de plume (les paragraphes des activités vues après) */ const t = (S.recitMoiT || {})[h]; if (!t) return ''; const html = troisTemps(recitHtml0(now(), h), h, now(), t); if (!html) return ''; const d = document.createElement('div'); d.innerHTML = html; const r = d.querySelector('.recit'); const ps = r ? Array.from(r.querySelectorAll(':scope > p')).filter(x => !x.classList.contains('cadre') && !x.classList.contains('sous') && !x.classList.contains('devoirs') && !x.classList.contains('bilan')) : []; return ps.map(x => x.outerHTML).join(''); }\nfunction suiteHtml(h){ const su = suiteDepuis(h); return su ? `<div class=\"ed-suite\"><div class=\"ed-suite-t\">— la suite de l'heure, composée par le site depuis ${hhmm((S.recitMoiT || {})[h]).replace(':', ' h ')} (tu la reprendras dans ta version) :</div>${su}</div>` : ''; }\nfunction reprendreSuite(h){ const su = suiteDepuis(h); if (!su) return; S.recitMoi[h] = (S.recitMoi[h] || '') + su; S.recitMoiT[h] = now(); poserVersion(h, S.recitMoi[h]); journal('recit-suite-reprise', { h }); tout(); if (document.getElementById('ecran-relecture').classList.contains('on')) relecture(); }")
rep("recitHtml0(fin, h, bornes); /* pose le branchement des boutons */ return `<div class=\"recit ma-version\">${S.recitMoi[h]}</div>` + barreRecit(); }","recitHtml0(fin, h, bornes); /* pose le branchement des boutons */ return `<div class=\"recit ma-version\">${S.recitMoi[h]}${suiteHtml(h)}</div>` + barreRecit(); }")
rep("function recitPourED(h){ if (S.recitVersion && S.recitVersion[h] === 'moi' && S.recitMoi && S.recitMoi[h] != null) return S.recitMoi[h];","function recitPourED(h){ if (S.recitVersion && S.recitVersion[h] === 'moi' && S.recitMoi && S.recitMoi[h] != null) return S.recitMoi[h] + suiteHtml(h);")
# le bouton « Reprendre la suite dans ma version » : dans le cahier (sous le sélecteur) et dans la relecture
rep('<span class="rv-h"><button id="rv-undo" title="Revenir à la version précédente">↶</button><button id="rv-redo" title="Rétablir la version suivante">↷</button></span></div>` : \'\'}','<span class="rv-h">${f.version === \'moi\' && f.suite ? `<button id="rv-reprendre" title="Colle la suite composée par le site à la fin de ta version, en un seul texte à corriger">Reprendre la suite dans ma version</button>` : \'\'}<button id="rv-undo" title="Revenir à la version précédente">↶</button><button id="rv-redo" title="Rétablir la version suivante">↷</button></span></div>` : \'\'}')
rep("return { onglet: S.finVue || 'travail', prepa: !!S.preparation,","return { onglet: S.finVue || 'travail', suite: !!suiteDepuis(S.heure), prepa: !!S.preparation,")
rep("const u = mur.querySelector('#rv-undo'), r = mur.querySelector('#rv-redo');","const rp = mur.querySelector('#rv-reprendre'); if (rp) rp.onclick = () => reprendreSuite(h); const u = mur.querySelector('#rv-undo'), r = mur.querySelector('#rv-redo');")
rep("$('rel').querySelectorAll('[data-rv]').forEach(b => b.onclick = () => basculerRecit(h, b.dataset.rv));","$('rel').querySelectorAll('[data-rv]').forEach(b => b.onclick = () => basculerRecit(h, b.dataset.rv)); if (v === 'moi' && suiteDepuis(h)) { const rvb = $('rel').querySelector('.rv'); if (rvb && !$('rel-reprendre')) rvb.insertAdjacentHTML('beforeend', '<button class=\"btn\" id=\"rel-reprendre\" style=\"margin-left:8px\">Reprendre la suite dans ma version</button>'); const rr = $('rel-reprendre'); if (rr) rr.onclick = () => reprendreSuite(h); }")
# « relu » : seulement sur le récit final (déjà pour le clic) ; par le défilement aussi ; décoché si une nouvelle diapo est vue
rep("if (ratio >= 0.97 && !(S.recitRelu || {})[h] && S.finVue === 'contenu') {","if (ratio >= 0.97 && !(S.recitRelu || {})[h] && S.finVue === 'contenu' && !S.preparation && ecran().role === 'fin') {")
rep("const journal = (type, x) => { const o = ","const journal = (type, x) => { if (type === 'diapo' && S.recitRelu && S.recitRelu[S.heure]) { S.recitRelu[S.heure] = false; S.recitAChange = S.recitAChange || {}; S.recitAChange[S.heure] = true; } const o = ")
rep("${e.n === 4 && !e.ok && !recitFinal ? ' — <i>à relire à la fin de l\\'heure</i>' : ''}","${e.n === 4 && !e.ok && !recitFinal ? ' — <i>à relire à la fin de l\\'heure</i>' : (e.n === 4 && !e.ok && (S.recitAChange || {})[hh] ? ' — <i>le récit a changé depuis : à relire</i>' : '')}")
rep("· v9c.14 b4 — <b>provisoire</b>","· v9c.14 b5 — <b>provisoire</b>")
open(p,'w',encoding='utf-8').write(s); print("(b4-2) écrit")
