p='vis/v9c14f-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (f) la face « Le chapitre » (2 · 1 bis) : une lecture du journal, des décisions, des notions et des travaux ; rien ne se verse
rep("if (hs.length > 1) f += `<button class=\"ong ${S.face === 'seance' ? 'on' : ''}\" data-f=\"seance\" data-h=\"${S.faceH}\" title=\"La relecture de la séance : les heures bout à bout, un seul bilan\">La séance</button>`;",
    "if (hs.length > 1) f += `<button class=\"ong ${S.face === 'seance' ? 'on' : ''}\" data-f=\"seance\" data-h=\"${S.faceH}\" title=\"La relecture de la séance : les heures bout à bout, un seul bilan\">La séance</button>`; f += `<button class=\"ong ${S.face === 'chapitre' ? 'on' : ''}\" data-f=\"chapitre\" data-h=\"${S.faceH}\" title=\"Le chapitre : le tracé des travaux à faire, ce qui a tenu et ce qui manquait, les notions — calculé des heures closes de cette classe, les heures à venir lues dans la trame ; rien ne se verse d'ici\">Le chapitre</button>`;")
rep("$('rel-titre').textContent = S.face === 'seance' ? `Relecture de la séance","$('rel-titre').textContent = S.face === 'chapitre' ? `Le chapitre — ${DATA.classe.nom} · ${seance().titre}` : S.face === 'seance' ? `Relecture de la séance")
rep("$('rel-sous').textContent = S.face === 'seance' ?","$('rel-sous').textContent = S.face === 'chapitre' ? `${Object.keys(S.closes || {}).length} heure(s) close(s) · ${S.lancee && !S.close ? 'une heure en cours' : 'aucune heure en cours'} · les heures à venir lues dans la trame` : S.face === 'seance' ?")
rep("$('rel').innerHTML = S.face === 'recit' ? recitHtml(fin, S.faceH) : S.face === 'passe' ? passeHtml(fin, S.faceH) : recitSeanceHtml(); }",
    "$('rel').innerHTML = S.face === 'chapitre' ? chapitreHtml() : S.face === 'recit' ? recitHtml(fin, S.faceH) : S.face === 'passe' ? passeHtml(fin, S.faceH) : recitSeanceHtml(); if (S.face === 'chapitre') brancherChapitre(); }")
# la clôture archive par heure ce que la face lit (l'échéance, les notions à apprendre)
rep("S.travailHeure = S.travailHeure || {}; S.travailHeure[S.heure] = texteTravailED();","S.travailHeure = S.travailHeure || {}; S.travailHeure[S.heure] = texteTravailED(); S.echeanceHeure = S.echeanceHeure || {}; S.echeanceHeure[S.heure] = S.echeance; S.apprendreHeure = S.apprendreHeure || {}; S.apprendreHeure[S.heure] = (S.travail && S.travail.apprendre) ? S.travail.apprendre.slice() : [];")
rep("function relecture(){", r"""function tempsActiviteH(a, h){ let passe = 0; const ev = J.filter(x => x.type === 'diapo' && x.h === h); ev.forEach((x, k) => { const fin = k + 1 < ev.length ? ev[k + 1].t : ((S.closes && S.closes[h]) || now()); if (a.diapos.includes(x.di)) passe += fin - x.t; }); (S.coupures || []).forEach(c => { if (!c.compte && a.diapos.includes(c.di)) passe -= (c.fin - c.debut); }); return Math.max(0, Math.round(passe / 60000)); }
function chapitreHtml(){ /* (f) 2 · 1 bis — une lecture, jamais une écriture */ const E = seance().ecrans; const acts = DATA.activites[String(S.si)] || []; const closes = Object.keys(S.closes || {}).map(Number).sort(); const enCours = (S.lancee && !S.close) ? S.heure : null; const heuresJouees = closes.concat(enCours != null && !closes.includes(enCours) ? [enCours] : []); const toutesH = [...new Set(E.map(e => e.heure))].sort(); const aVenir = toutesH.filter(h => !heuresJouees.includes(h));
  /* 1 · le tracé des travaux à faire */ let h1 = '<h3>1 · Le tracé des travaux à faire</h3>'; heuresJouees.forEach(h => { const sim = HEURES_SIM[h]; const ech = (S.echeanceHeure || {})[h] !== undefined ? (S.echeanceHeure || {})[h] : (h === S.heure ? S.echeance : null); const p = ech ? DATA.classe.prochaines.find(x => x.iso === ech) : null; const texte = (S.travailHeure || {})[h] || (h === S.heure ? texteTravailED() : ''); h1 += `<div class="chap-h"><div class="chap-t"><b>Heure ${h}</b> — donné le ${esc(sim.jour)}${p ? ', pour <b>' + esc(p.l) + '</b>' : ', <i>sans échéance</i>'}${S.closes && S.closes[h] ? '' : ' <i>(heure en cours — ce qui est en préparation)</i>'}${p && p.deja ? `<div class="chap-deja">déjà donné pour cette date (${esc(p.dejaQuand || '')}) : ${esc(p.deja)}</div>` : ''}</div><div class="chap-txt">${texte ? esc(texte).replace(/\n/g, '<br>') : '<i>rien</i>'}</div><button class="btn" data-copie-travail="${h}" title="Copie ce travail à faire tel qu\'il est parti">Copier pour École Directe</button></div>`; }); aVenir.forEach(h => { const sim = HEURES_SIM[h]; const prevu = E.filter(e => e.heure === h).map(e => e.act).slice(0, 4); h1 += `<div class="chap-h avenir"><div class="chap-t"><b>Heure ${h}</b> — ${sim ? esc(sim.jour) : 'à venir'} · <i>à venir : la trame prévoit</i> ${prevu.map(esc).join(', ')}…</div></div>`; });
  /* 2 · ce qui manquait, ce qui était en trop */ let h2 = '<h3>2 · Ce qui manquait, ce qui était en trop</h3>'; heuresJouees.forEach(h => { const dec = Object.keys(S.decisions).map(id => ({ id, d: S.decisions[id] })).filter(x => x.d.heure === h && !x.d.defaut); const actsH = acts.filter(a => a.diapos.some(i => E[i].heure === h)); const lignes = dec.map(x => { const a = acts.find(z => z.id === x.id); if (!a) return ''; const prevu = (S.durees && S.durees[a.id] != null) ? S.durees[a.id] : a.diapos.filter(i => E[i].heure === h).reduce((t, i) => t + (E[i].dur || 0), 0); const passe = tempsActiviteH(a, h); const lib = { suivante: 'reportée à l\'heure suivante', terminer: 'partie à la maison (à terminer)', preparer: 'partie à la maison (à préparer)', reserve: 'mise en réserve', nonfait: 'non faite', pastemps: 'partie à la maison', reporter: 'reportée', passee: 'passée' }[x.d.choix] || x.d.choix; return `<div class="chap-l"><b>A${a.num} · ${esc(a.titre)}</b> — ${lib} · ${prevu} min prévues, ${passe} min passées${x.d.motif ? ' · <i>' + esc(x.d.motif) + '</i>' : ''}</div>`; }).join(''); const trop = dec.reduce((t, x) => { const a = acts.find(z => z.id === x.id); if (!a) return t; const prevu = (S.durees && S.durees[a.id] != null) ? S.durees[a.id] : a.diapos.filter(i => E[i].heure === h).reduce((q, i) => q + (E[i].dur || 0), 0); return t + prevu; }, 0);
    const JH = J.filter(x => x.h === h); const imprevues = JH.filter(x => x.type === 'notion-imprevue').map(x => { let lib = x.id; DATA.taxo.forEach(d => d.familles.forEach(f => f.notions.forEach(n => { if (n.id === x.id) lib = n.prof || n.eleve || n.id; }))); return lib; }); const modifs = JH.filter(x => /texte-modifie|diapo-modifiee|travail-edite/.test(x.type)).length; const versees = JH.filter(x => /note-versee|versee|verse-/.test(x.type)).length; const gardees = JH.filter(x => x.type === 'reponse-gardee' || x.type === 'garder-reponse').length;
    h2 += `<div class="chap-h"><div class="chap-t"><b>Heure ${h}</b> — <i>parti à la maison ou reporté</i> : ${dec.length ? dec.length + ' activité' + (dec.length > 1 ? 's' : '') + ' sur ' + actsH.length + ' n\'' + (dec.length > 1 ? 'ont' : 'a') + ' pas tenu · ' + trop + ' min de trop' : 'tout a tenu'}</div>${lignes}<div class="chap-t" style="margin-top:6px"><i>ce qui manquait</i> (ajouté pendant l\'heure, absent de la trame) : ${imprevues.length ? 'notions imprévues : ' + imprevues.map(esc).join(', ') : 'aucune notion imprévue'} · ${gardees} réponse${gardees > 1 ? 's' : ''} gardée${gardees > 1 ? 's' : ''} · ${versees} note${versees > 1 ? 's' : ''} versée${versees > 1 ? 's' : ''} · ${modifs} diapo${modifs > 1 ? 's' : ''} modifiée${modifs > 1 ? 's' : ''}</div></div>`; });
  /* 3 · les notions du chapitre */ let h3 = '<h3>3 · Les notions du chapitre</h3><div class="chap-notions">'; const vues = {}; J.filter(x => x.type === 'diapo' && E[x.di]).forEach(x => { (E[x.di].comp || []).forEach(id => { vues[id] = vues[id] || []; vues[id].push({ h: x.h, act: E[x.di].act }); }); }); const prevues = {}; E.forEach((e, i) => (e.comp || []).forEach(id => { prevues[id] = prevues[id] || []; prevues[id].push({ h: e.heure, act: e.act }); })); const donnees = {}; Object.keys(S.apprendreHeure || {}).forEach(h => (S.apprendreHeure[h] || []).forEach(id => { donnees[id] = donnees[id] || []; donnees[id].push(+h); })); if (S.travail && S.travail.apprendre && S.lancee && !S.close) S.travail.apprendre.forEach(id => { donnees[id] = donnees[id] || []; if (!donnees[id].includes(S.heure)) donnees[id].push(S.heure); }); const imprev = {}; Object.keys(S.notionsImprevues || {}).forEach(eid => (S.notionsImprevues[eid] || []).forEach(id => { imprev[id] = true; }));
  const ligneN = (n, f) => { const pv = prevues[n.id] || [], vu = vues[n.id] || [], dn = donnees[n.id] || []; const etat = vu.length ? 'travaillée' : (pv.some(x => aVenir.includes(x.h)) ? 'à venir' : (pv.length ? 'non travaillée' : (imprev[n.id] ? 'imprévue' : ''))); if (!pv.length && !vu.length && !dn.length && !imprev[n.id]) return ''; return `<div class="chap-n ${etat.replace(/\s/g, '-').replace('é', 'e')}"><b>${esc(n.prof || n.eleve || n.id)}</b> <span class="chap-etat">${etat}</span> — prévue ${pv.length ? pv.map(x => 'h' + x.h + ' (' + esc(x.act) + ')').join(', ') : 'nulle part'} · travaillée ${vu.length ? [...new Set(vu.map(x => 'h' + x.h + ' (' + esc(x.act) + ')'))].join(', ') : 'pas encore'} · à apprendre ${dn.length ? 'donnée h' + dn.join(', h') : 'pas encore'}${imprev[n.id] ? ' · <i>imprévue, ajoutée pendant l\'heure</i>' : ''}</div>`; };
  DATA.taxo.forEach(d => d.familles.forEach(f => f.notions.forEach(n => { h3 += ligneN(n, f); }))); h3 += '</div>';
  return `<div class="chapitre">${h1}${h2}${h3}</div>`; }
function brancherChapitre(){ $('rel').querySelectorAll('[data-copie-travail]').forEach(b => b.onclick = () => { const h = +b.dataset.copieTravail; const txt = (S.travailHeure || {})[h] || (h === S.heure ? texteTravailED() : ''); copierTexte(txt || '(rien à faire)', 'copié : le travail à faire de l\'heure ' + h); journal('copie-ed', { quoi: 'travail', h }); b.textContent = '✔ copié'; }); }
function relecture(){""")
rep("\n.mur .ed-part{", r"""
.chapitre h3{color:var(--or);margin:14px 0 6px;font-size:1.05rem}.chap-h{background:var(--carte);border:1px solid var(--bord);border-radius:8px;padding:8px 12px;margin-bottom:8px}.chap-h.avenir{opacity:.7}.chap-t{font-size:.95rem}.chap-deja{color:var(--texte2);font-style:italic;font-size:.88rem;margin:4px 0}.chap-txt{margin:6px 0;line-height:1.45}.chap-l{padding:3px 0 3px 10px;border-left:2px solid var(--bord2);margin:4px 0;font-size:.92rem}.chap-notions{display:flex;flex-direction:column;gap:4px}.chap-n{font-size:.9rem;padding:4px 8px;border-radius:6px;background:var(--carte)}.chap-etat{font-size:.72rem;border-radius:999px;padding:0 6px;margin-left:4px;background:rgba(201,154,78,.2);color:#e0c48c}.chap-n.travaillee .chap-etat{background:rgba(60,187,128,.18);color:#8fe0b8}.chap-n.a-venir .chap-etat{background:rgba(111,179,224,.15);color:#a8cbea}.chap-n.imprevue .chap-etat{background:rgba(232,72,76,.18);color:#f0a0a0}
.mur .ed-part{""")
rep("· v9c.14 e — <b>provisoire</b> : « Le chapitre » en (f) <span","· v9c.14 f <span")
open(p,'w',encoding='utf-8').write(s); print("(f) écrit")
