p='vis/v9c14g-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (g1) la donnée « remobilise » dans la trame simulée (cadrage 4 · 2.7) : mardi, « Les règles héritées » remobilise « Décrire une image fixe ou mobile », travaillée par l'activité 1 de lundi
rep("const $ = id => document.getElementById(id);","/* (g1) simulation de la donnée de préparation (cadrage 4 · 2.7) : la trame dit ce que chaque activité remobilise — ici, mardi, « Les règles héritées » remobilise « Décrire une image fixe ou mobile », travaillée par l'activité 1 de lundi */ DATA.seances.forEach(se => se.ecrans.forEach(e => { if (e.act === 'Les règles héritées') e.remob = ['litt-036']; }));\nconst $ = id => document.getElementById(id);")
# ── le geste « Expliqué à l'oral » (7.2) : ⋯ → « Expliqué à l'oral » remplace « notion imprévue »
rep("{ a: 'notion', l: 'Déclarer une notion imprévue…', t: 'une notion travaillée à l\\'oral","{ a: 'oral', l: 'Expliqué à l\\'oral…', t: 'ce que tu as expliqué sans jouer la diapo : ça remplace une activité de l\\'heure (faite à l\\'oral) ou c\\'est une reprise ; les notions cochées passent travaillées à l\\'oral ; ta phrase devient le paragraphe au récit' }, { a: 'notion', l: 'Déclarer une notion imprévue…', t: 'une notion travaillée à l\\'oral")
rep("if (a === 'notion') ouvrirNotion();","if (a === 'notion') ouvrirNotion(); if (a === 'oral') ouvrirOral();")
rep('<div id="gc-apercu"', r"""<div class="garde" id="oral" title="Expliqué à l'oral (7.2)"><div class="boite" style="width:760px;max-width:96vw;border-color:var(--or)"><div style="display:flex;justify-content:space-between;align-items:baseline;gap:10px"><h3 style="margin:0;color:var(--or);font-size:1.1rem">Expliqué à l'oral</h3><div id="oral-chrono" style="color:var(--texte2);font-size:.9rem"></div></div>
<div id="oral-rempl" class="oral-bloc"></div><div id="oral-notions" class="oral-bloc"></div><textarea id="oral-txt" rows="3" placeholder="Une phrase courte, tapée — ou rien" title="Ce que tu as expliqué : ce texte devient le paragraphe de l'activité au récit (ou la reprise, à sa place dans le temps)"></textarea>
<div class="choix" style="justify-content:flex-start;align-items:center;gap:8px;margin-top:8px"><button class="btn" id="oral-pause" title="N'arrête que le temps compté sur cet oral">⏸ Pause</button><button class="btn" id="oral-reprendre" disabled>▶ Reprendre</button><button class="btn or" id="oral-valider" title="Valide : l'activité est faite à l'oral (ou la reprise est notée), le texte va au récit, les notions cochées passent travaillées (à l'oral), le curseur va à l'activité suivante">✔ Valider</button><button class="btn" id="oral-annuler">Annuler</button><span id="oral-h" style="margin-left:auto;color:var(--texte2);font-size:.85rem"></span></div><div style="color:var(--sourd);font-size:.8rem;margin-top:6px">Remise en forme légère à la validation (majuscules, point final), jamais de reformulation. Tout est noté au journal ; rien ne se verse dans la trame.</div></div></div>
<div id="gc-apercu\"""")
s=s.replace('id="gc-apercu\\"','id="gc-apercu"')
rep("\n.mur .ed-part{", r"""
.oral-bloc{background:#151109;border:1px solid var(--bord);border-radius:8px;padding:6px 10px;margin:8px 0;font-size:.92rem}.oral-bloc label{display:block;margin:3px 0}.oral-bloc label.inline{display:inline-block;margin:2px 12px 2px 0}.oral-bloc .prop{color:#ff8a8e;font-size:.8rem;margin-left:4px}#oral-txt{width:100%;box-sizing:border-box;font:inherit;font-size:1.05rem;padding:8px 10px;border:2px solid var(--or);border-radius:8px;background:#fff;color:#1c1712}
.mur .oral-carte{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:.4em;background:#fbfaf5;color:#1c1712}.mur .oral-carte .t{font-size:1.3em;font-weight:700}.mur .oral-carte .s{font-size:.9em;color:#6a5a48;font-style:italic}
.mur .ed-part{""")
# les fonctions : notions remobilisées non travaillées, ouvrirOral, la mise en forme légère, la validation
rep("function preparerCahier(){", r"""function notionsTravaillees(){ /* les notions travaillées (une diapo vue qui les porte, ou un oral) — toutes heures de la classe */ const E = seance().ecrans; const t = {}; J.filter(x => x.type === 'diapo' && E[x.di]).forEach(x => (E[x.di].comp || []).forEach(id => { t[id] = t[id] || { h: x.h, par: E[x.di].act }; })); Object.keys(S.notionsOral || {}).forEach(id => { t[id] = t[id] || S.notionsOral[id]; }); return t; }
function libNotion(id){ let lib = id; DATA.taxo.forEach(d => d.familles.forEach(f => f.notions.forEach(n => { if (n.id === id) lib = n.prof || n.eleve || id; }))); return lib; }
function remobNonTravaillees(h){ /* ce que les activités de l'heure h remobilisent sans que ce soit travaillé (7.1) */ const E = seance().ecrans; const trav = notionsTravaillees(); const out = []; E.forEach((e, i) => { if (e.heure !== h || retiree(e)) return; (e.remob || []).forEach(id => { if (!trav[id] && !out.some(o => o.id === id && o.di === i)) { const a = (DATA.activites[String(S.si)] || []).find(z => z.diapos.includes(i)); const src = E.findIndex(z => (z.comp || []).includes(id)); const as = src >= 0 ? (DATA.activites[String(S.si)] || []).find(z => z.diapos.includes(src)) : null; const dec = as ? S.decisions[as.id] : null; out.push({ id, lib: libNotion(id), di: i, act: e.act, a, source: as, sourceEtat: dec ? ({ reserve: 'en réserve', nonfait: 'non faite', terminer: 'partie à la maison', preparer: 'partie à la maison', suivante: 'reportée' }[dec.choix] || dec.choix) : (src >= 0 && E[src].heure < h ? 'non jouée' : 'à venir') }); } }); }); return out; }
function miseEnFormeLegere(t){ t = String(t || '').trim().replace(/\s+([,.!?:;»])/g, (m, p) => (/[?!:;»]/.test(p) ? ' ' + p : p)).replace(/([«])\s*/g, '$1 ').replace(/\s{2,}/g, ' '); t = t.replace(/\b(\w+)\s+\1\b/gi, '$1'); if (!t) return t; t = t.charAt(0) === t.charAt(0).toLowerCase() ? t.charAt(0).toUpperCase() + t.slice(1) : t; t = t.replace(/([.!?])\s+([a-zà-ÿ])/g, (m, p, c) => p + ' ' + c.toUpperCase()); if (!/[.!?»]$/.test(t)) t += '.'; return t; }
function ouvrirOral(prerempli){ const h = S.heure; const E = seance().ecrans; const acts = (DATA.activites[String(S.si)] || []).filter(a => a.diapos.some(i => E[i].heure === h) && !(S.faiteOral || {})[a.id] && !(S.decisions[a.id] && !S.decisions[a.id].defaut) && a.diapos.some(i => !retiree(E[i]) && E[i].role !== 'fin')); const enCours = acts.find(a => a.diapos.includes(S.di)); const nonFaites = acts.filter(a => !a.diapos.filter(i => E[i].heure === h).every(i => finie(E[i], i)));
  S.oralEnCours = { t0: now(), pauses: [], di: S.di, eid: ecran().eid, act: enCours ? enCours.id : null }; $('oral-rempl').innerHTML = 'Cet oral :' + nonFaites.map(a => `<label><input type="radio" name="oral-r" value="${a.id}" ${prerempli && prerempli.act === a.id ? 'checked' : (!prerempli && enCours && enCours.id === a.id ? 'checked' : '')}> <b>remplace l'activité ${a.num} — ${esc(a.titre)}</b>, faite à l'oral (ses diapos ne seront pas dévoilées ; la classe voit « Activité ${a.num} — à l'oral »)</label>`).join('') + `<label><input type="radio" name="oral-r" value="" ${prerempli && !prerempli.act ? 'checked' : (nonFaites.length && !(prerempli && prerempli.act) && enCours ? '' : 'checked')}> est <b>une reprise</b> (rien de prévu : le prévu se décale d'autant)</label>`;
  const remob = remobNonTravaillees(h); const trav = notionsTravaillees(); let hn = 'Notions travaillées à l\'oral : '; const vues = {}; remob.forEach(r => { if (vues[r.id]) return; vues[r.id] = 1; hn += `<label class="inline"><input type="checkbox" data-n="${r.id}" ${prerempli && prerempli.notion === r.id ? 'checked' : ''}> ${esc(r.lib)} <span class="prop">remobilisée, non travaillée</span></label>`; }); const courantes = enCours ? [...new Set(enCours.diapos.flatMap(i => E[i].comp || []))] : (E[S.di].comp || []); courantes.forEach(id => { if (vues[id]) return; vues[id] = 1; hn += `<label class="inline"><input type="checkbox" data-n="${id}"> ${esc(libNotion(id))}</label>`; }); hn += ` <a href="#" id="oral-autres" style="font-size:.85rem">autres notions…</a><div id="oral-autres-z" style="display:none;margin-top:4px"></div>`; $('oral-notions').innerHTML = hn; $('oral-autres').onclick = ev => { ev.preventDefault(); const z = $('oral-autres-z'); z.style.display = 'block'; z.innerHTML = DATA.taxo.map(d => d.familles.map(f => f.notions.filter(n => !vues[n.id]).map(n => `<label class="inline"><input type="checkbox" data-n="${n.id}"> ${esc(n.prof || n.eleve || n.id)}</label>`).join('')).join('')).join(''); };
  $('oral-txt').value = prerempli && prerempli.texte ? prerempli.texte : ''; $('oral').classList.add('on'); journal('oral-debut', { h, di: S.di, act: S.oralEnCours.act }); const tick = () => { if (!S.oralEnCours) return; const o = S.oralEnCours; const enPause = o.pauses.length && !o.pauses[o.pauses.length - 1].fin; const passe = Math.round((now() - o.t0 - o.pauses.reduce((t, x) => t + ((x.fin || now()) - x.debut), 0)) / 1000); const a = enCours; const prevu = a ? ((S.durees && S.durees[a.id] != null) ? S.durees[a.id] : a.diapos.filter(i => E[i].heure === h).reduce((t, i) => t + (E[i].dur || 0), 0)) : 0; const ta = a ? tempsActivite(a) : 0; const reste = heureCahier() - now(); const ecart = Math.round((reste - (ordreHeure(h).filter(i => !vuJ(h, i).fin && E[i].role !== 'fin').reduce((t, i) => t + (E[i].dur || 0), 0)) * 60000) / 60000); $('oral-chrono').innerHTML = (a ? `<b style="color:var(--joue)">A${a.num} · ${esc(a.titre)}</b> · ${ta} min passée${ta > 1 ? 's' : ''} sur ${prevu} prévues · ` : '') + (ecart < 0 ? `l'heure est en retard de ${-ecart} min` : ecart > 0 ? `l'heure est en avance de ${ecart} min` : 'l\'heure est dans les temps'); $('oral-h').textContent = 'début ' + hhmm(o.t0).replace(':', ' h ') + ' · ' + Math.floor(passe / 60) + ' min ' + (passe % 60) + ' s' + (enPause ? ' (en pause)' : ''); }; tick(); S._oralTick = setInterval(tick, 1000);
  $('oral-pause').onclick = () => { S.oralEnCours.pauses.push({ debut: now() }); $('oral-pause').disabled = true; $('oral-reprendre').disabled = false; journal('oral-pause'); }; $('oral-reprendre').onclick = () => { const pp = S.oralEnCours.pauses; if (pp.length) pp[pp.length - 1].fin = now(); $('oral-pause').disabled = false; $('oral-reprendre').disabled = true; journal('oral-reprise'); };
  $('oral-annuler').onclick = () => { fermerOral(); journal('oral-annule'); }; $('oral-valider').onclick = validerOral; pousser(etatComplet()); tout(); }
function fermerOral(){ clearInterval(S._oralTick); S.oralEnCours = null; $('oral').classList.remove('on'); $('oral-pause').disabled = false; $('oral-reprendre').disabled = true; }
function validerOral(){ const o = S.oralEnCours; if (!o) return; const h = S.heure; const E = seance().ecrans; const r = document.querySelector('#oral input[name="oral-r"]:checked'); const actId = r && r.value ? r.value : null; const notions = Array.from(document.querySelectorAll('#oral input[data-n]:checked')).map(x => x.dataset.n); const texte = miseEnFormeLegere($('oral-txt').value); const t1 = now(); const duree = Math.round((t1 - o.t0 - o.pauses.reduce((t, x) => t + ((x.fin || t1) - x.debut), 0)) / 60000 * 10) / 10;
  const oral = { h, t0: o.t0, t1, duree, pauses: o.pauses, act: actId, notions, texte, audio: null }; S.oraux = S.oraux || {}; S.oraux[h] = S.oraux[h] || []; S.oraux[h].push(oral); S.notionsOral = S.notionsOral || {}; notions.forEach(id => { S.notionsOral[id] = S.notionsOral[id] || { h, par: actId ? 'A' + ((DATA.activites[String(S.si)] || []).find(a => a.id === actId) || {}).num + ' (à l\'oral)' : 'reprise à l\'oral', oral: true }; });
  if (actId) { const a = (DATA.activites[String(S.si)] || []).find(z => z.id === actId); S.faiteOral = S.faiteOral || {}; S.faiteOral[actId] = { h, t0: o.t0, t1, duree }; journal('oral', { h, act: actId, num: a && a.num, duree, notions, texte, remplace: true }); /* ses diapos sont sautées pour cette heure ; le curseur va à la première diapo de l'activité suivante */ const o2 = ordreHeure(h); const apres = o2.filter(i => !a.diapos.includes(i) && !vuJ(h, i).fin && !retiree(E[i]) && o2.indexOf(i) > o2.indexOf(a.diapos[0])); fermerOral(); if (apres.length) { S._parGardeCahier = E[apres[0]].role === 'fin'; S.di = apres[0]; S.page = null; S._parGardeCahier = false; } } else { /* une reprise : rien de prévu, le prévu se décale d'autant (son temps est une coupure non comptée dans les activités) */ S.coupures = S.coupures || []; S.coupures.push({ debut: o.t0, fin: t1, di: o.di, eid: o.eid, duree: Math.round(duree), compte: false, reprise: true }); journal('oral', { h, act: null, duree, notions, texte, reprise: true }); fermerOral(); }
  tout(); }
function preparerCahier(){""")
# le rendu au tableau pendant un oral qui remplace une activité : le titre et « à l'oral »
rep("return { onglet: S.finVue || 'travail', suite: !!suiteDepuis(S.heure), prepa: !!S.preparation,","return { onglet: S.finVue || 'travail', suite: !!suiteDepuis(S.heure), prepa: !!S.preparation, oral: S.oralEnCours && S.oralEnCours.act ? (function(){ const a = (DATA.activites[String(S.si)] || []).find(z => z.id === S.oralEnCours.act); return a ? { num: a.num, titre: a.titre } : null; })() : null,")
rep("const etatComplet = () => { S.eidCourant = ecran().eid; const __p = !!S.preparation; co","const etatComplet = () => { S.eidCourant = ecran().eid; const __p = !!S.preparation; const __oral = S.oralEnCours && S.oralEnCours.act ? (function(){ const a = (DATA.activites[String(S.si)] || []).find(z => z.id === S.oralEnCours.act); return a ? { num: a.num, titre: a.titre } : null; })() : null; co")
rep("function rendre(mur, et){","function rendre(mur, et){ if (et && et.oral && !et.pilote) { mur.innerHTML = `<div class=\"oral-carte\"><div class=\"t\">Activité ${esc(String(et.oral.num))} — ${esc(et.oral.titre)}</div><div class=\"s\">à l'oral</div></div>`; return; }")
# etatComplet : le champ oral au premier niveau
rep("const etatComplet = () => {","const etatComplet0 = () => {")
s=s.replace("function tout(){","const etatComplet = () => { const et = etatComplet0(); if (S.oralEnCours && S.oralEnCours.act) { const a = (DATA.activites[String(S.si)] || []).find(z => z.id === S.oralEnCours.act); if (a) et.oral = { num: a.num, titre: a.titre }; } return et; };\nfunction tout(){",1)
# une activité faite à l'oral est « finie » pour le pilotage (états de temps, séquence, glissement)
rep("const finie = (e, i) => { const n = elements(e).length;","const finie = (e, i) => { if (S.faiteOral && Object.keys(S.faiteOral).some(id => ((DATA.activites[String(S.si)] || []).find(a => a.id === id) || { diapos: [] }).diapos.includes(i))) return true; /* faite à l'oral (7.2) : ses diapos comptent finies */ const n = elements(e).length;")
rep("function etatWorktrack(a){ const E = seance().ecrans; const diapos = a.diapos.filter(i => ordreHeure(S.heure).includes(i)); if (!diapos.length) return null; const prevu = dureeDe(a); const min = tempsActivite(a);","function etatWorktrack(a){ const E = seance().ecrans; const diapos = a.diapos.filter(i => ordreHeure(S.heure).includes(i)); if (!diapos.length) return null; const prevu = dureeDe(a); if ((S.faiteOral || {})[a.id]) return { k: 'fin', txt: 'faite à l\\'oral', prevu, min: Math.round(S.faiteOral[a.id].duree) }; const min = tempsActivite(a);")
# le récit : le paragraphe d'une activité faite à l'oral, et les reprises à leur place dans le temps
rep("groupes.forEach(g => { co","groupes.forEach(g => { if (g.a && (S.faiteOral || {})[g.a.id] && (S.faiteOral[g.a.id].h === h)) return; /* faite à l'oral : son paragraphe est l'oral (7.2) */ co")
rep("  // le travail à faire : ce que Paul a décidé (7.2), plus une consigne montrée qui porte une échéance (l'ancien moteur)", r"""  (S.oraux && S.oraux[h] || []).forEach(o => { const a = o.act ? (DATA.activites[String(S.si)] || []).find(z => z.id === o.act) : null; const notions = (o.notions || []).map(libNotion); if (a) p.push('<p data-cle="' + esc(o.act) + '" data-t0="' + o.t0 + '" data-t1="' + o.t1 + '" data-titre="Activité ' + esc(String(a.num)) + ' — ' + esc(a.titre).replace(/"/g, '&quot;') + '"><span class="act-r">Activité ' + esc(String(a.num)) + ' — ' + esc(a.titre) + '</span> <b>faite à l\'oral</b>' + (notions.length ? ' (' + notions.map(esc).join(', ') + ')' : '') + (o.texte ? ' : ' + esc(o.texte) : '.') + '</p>'); else p.push('<p data-cle="reprise-' + o.t0 + '" data-t0="' + o.t0 + '" data-t1="' + o.t1 + '" data-titre="Reprise à l\'oral">À <b>' + hm(o.t0) + '</b>, on a repris à l\'oral' + (notions.length ? ' ' + notions.map(esc).join(', ') : '') + (o.texte ? ' : ' + esc(o.texte) : '.') + '</p>'); });
  p.sort((x, y) => (+(x.match(/data-t0="(\d+)"/) || [0, 0])[1]) - (+(y.match(/data-t0="(\d+)"/) || [0, 0])[1]));
  // le travail à faire : ce que Paul a décidé (7.2), plus une consigne montrée qui porte une échéance (l'ancien moteur)""")
# le chapitre : « travaillée (à l'oral, heure n) »
rep("const vues = {}; J.filter(x => x.type === 'diapo' && E[x.di]).forEach(x => { (E[x.di].comp || []).forEach(id => { vues[id] = vues[id] || []; vues[id].push({ h: x.h, act: E[x.di].act }); }); });","const vues = {}; J.filter(x => x.type === 'diapo' && E[x.di]).forEach(x => { (E[x.di].comp || []).forEach(id => { vues[id] = vues[id] || []; vues[id].push({ h: x.h, act: E[x.di].act }); }); }); Object.keys(S.notionsOral || {}).forEach(id => { const o = S.notionsOral[id]; vues[id] = vues[id] || []; vues[id].push({ h: o.h, act: (o.par || 'à l\\'oral') + (o.par && /oral/.test(o.par) ? '' : ' (à l\\'oral)') }); });")
rep("const finH = (S.closes && S.closes[h]) || fin; const cleDe = e => e.actId || ('r-' + e.eid); const acts = []; JH.forEach((x, k) => {","const finH = (S.closes && S.closes[h]) || fin; const cleDe = e => e.actId || ('r-' + e.eid); const acts = []; (S.oraux && S.oraux[h] || []).filter(o => !depuis || o.t0 >= depuis).forEach(o => { const ad = o.act ? (DATA.activites[String(S.si)] || []).find(z => z.id === o.act) : null; acts.push({ cle: o.act ? o.act : 'reprise-' + o.t0, titre: ad ? 'l\\'activité ' + ad.num + ' — ' + ad.titre + ' (à l\\'oral)' : 'une reprise à l\\'oral', t0: o.t0, t1: o.t1, vues: [], oral: true }); }); JH.forEach((x, k) => {")
rep("let a = acts.find(z => z.cle === cle); if (!a) { const ad = actDe(e);","let a = acts.find(z => z.cle === cle); if (a && a.oral) return; if (!a) { const ad = actDe(e);")
rep("const REP = { debut: 'Au début de l\\'heure, on a commencé par',","acts.sort((x, y) => x.t0 - y.t0); /* les oraux prennent leur place dans le temps */ const REP = { debut: 'Au début de l\\'heure, on a commencé par',")
rep("· v9c.14 f <span","· v9c.14 g1 — <b>provisoire</b> : le faisceau à l'ouverture en g2 <span")
open(p,'w',encoding='utf-8').write(s); print("(g1) écrit")
