p='vis/v9c14g2-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (g2) le faisceau oui / non à l'ouverture de l'heure (7.1)
rep("function ouvrirOuverture(){", r"""function faisceauHtml(h){ /* 7.1 : pour chaque activité de l'heure qui remobilise une notion non travaillée, un faisceau de questions oui / non ; une notion à la fois */ const E = seance().ecrans; const liste = remobNonTravaillees(h).filter(r => !(S.faisceauFait || {})[h + ':' + r.id + ':' + r.di]); if (!liste.length) { S.faisceau = null; return ''; } const r = liste[0]; const f = S.faisceau && S.faisceau.h === h && S.faisceau.id === r.id && S.faisceau.di === r.di ? S.faisceau : (S.faisceau = { h, id: r.id, di: r.di, q: 1, reps: [] }); const src = r.source; const prevuSrc = src ? dureeDe(src) : 0; const prevuH = ordreHeure(h).filter(i => E[i].role !== 'fin').reduce((t, i) => t + (E[i].dur || 0), 0); const utiles = (HEURES_SIM[h] && HEURES_SIM[h].utiles) || 50; const depasse = Math.max(0, prevuH + prevuSrc - utiles);
  const ctx = `<div class="ctx"><b>${esc(r.act)}</b>${r.a ? ' (activité ' + r.a.num + ' de cette heure)' : ''} remobilise <b>« ${esc(r.lib)} »</b> — <b>non travaillée</b>${src ? ' : « ' + esc(src.titre) + ' » (activité ' + src.num + ' de l\'heure ' + (E[src.diapos[0]].heure) + ') est ' + esc(r.sourceEtat) + '.' : '.'}</div>`;
  const Q = { 1: 'Cette heure a-t-elle besoin de cette notion pour tenir ?', 2: src ? `As-tu le temps de jouer d'abord « ${esc(src.titre)} » (${prevuSrc} min prévues${depasse ? ' — l\'heure dépasserait de ' + depasse + ' min' : ''}) ?` : 'As-tu le temps de jouer d\'abord l\'activité qui la travaille ?', 3: 'Peux-tu reprendre la notion toi-même, à l\'oral, en quelques minutes ?' };
  const ENT = { 1: `Si <b>non</b> → on laisse tel quel (noté au journal). Si <b>oui</b> → question 2.`, 2: `Si <b>oui</b> → on remet « ${src ? esc(src.titre) : 'l\'activité'} » avant, en tête de l'heure. Si <b>non</b> → question 3.`, 3: `Si <b>oui</b> → une reprise à l'oral avant « ${esc(r.act)} » (une ligne dans l'ordre de l'heure). Si <b>non</b> → on décale « ${esc(r.act)} » à l'heure suivante.` };
  const fil = f.reps.map((x, k) => `<div class="fil">${k + 1} · ${Q[k + 1].replace(/<[^>]+>/g, '')} — <b>${x ? 'oui' : 'non'}</b></div>`).join('');
  if (f.concl) { const LIB = { laisser: 'on laisse tel quel — l\'heure se joue comme prévu, en le sachant', remettre: `on remet « ${src ? esc(src.titre) : ''} » avant, en tête de l'heure`, reprise: `une reprise à l'oral de « ${esc(r.lib)} » avant « ${esc(r.act)} »`, decaler: `on décale « ${esc(r.act)} » à l'heure suivante` }; return `<div class="fais" id="fais"><h4>Ce que cette heure remobilise et qui n'a pas été travaillé — conclusion${liste.length > 1 ? ' (' + liste.length + ' notions, une à la fois)' : ''}</h4>${ctx}${fil}<div class="concl">Donc : <b>${LIB[f.concl]}</b>.</div><div class="rep"><button class="oui" id="fais-ok" title="Confirme : c'est noté au journal, l'ordre de l'heure se recalcule s'il y a lieu">C'est ça</button><button id="fais-re" title="Repart de la question 1">Recommencer</button></div></div>`; }
  return `<div class="fais" id="fais"><h4>Ce que cette heure remobilise et qui n'a pas été travaillé — question ${f.q} sur 3${liste.length > 1 ? ' (' + liste.length + ' notions, une à la fois)' : ''}</h4>${ctx}${fil}<div class="q">${f.q} · ${Q[f.q]}</div><div class="rep"><button class="oui" data-fais="1">Oui</button><button data-fais="0">Non</button></div><div class="concl">${ENT[f.q]}</div></div>`; }
function brancherFaisceau(h){ const z = $('fais'); if (!z) return; z.querySelectorAll('[data-fais]').forEach(b => b.onclick = () => { const f = S.faisceau; const oui = b.dataset.fais === '1'; f.reps.push(oui); if (f.q === 1) { if (!oui) f.concl = 'laisser'; else f.q = 2; } else if (f.q === 2) { if (oui) f.concl = 'remettre'; else f.q = 3; } else { f.concl = oui ? 'reprise' : 'decaler'; } journal('faisceau-reponse', { h, notion: f.id, q: f.q, oui }); ouvrirOuverture(); });
  const re = $('fais-re'); if (re) re.onclick = () => { S.faisceau.q = 1; S.faisceau.reps = []; delete S.faisceau.concl; journal('faisceau-recommence', { h }); ouvrirOuverture(); };
  const ok = $('fais-ok'); if (ok) ok.onclick = () => { const f = S.faisceau; const E = seance().ecrans; const r = remobNonTravaillees(h).find(x => x.id === f.id && x.di === f.di); S.faisceauFait = S.faisceauFait || {}; S.faisceauFait[h + ':' + f.id + ':' + f.di] = f.concl; if (f.concl === 'remettre' && r && r.source) { S.decisions[r.source.id] = { choix: 'suivante', heure: E[diaposAct(r.source)[0]].heure, t: now(), remob: true }; } if (f.concl === 'decaler' && r && r.a) { S.decisions[r.a.id] = { choix: 'suivante', heure: h, moment: 'classe', t: now(), remob: true }; } if (f.concl === 'reprise' && r) { S.reprisesPrevues = S.reprisesPrevues || {}; S.reprisesPrevues[h] = S.reprisesPrevues[h] || []; S.reprisesPrevues[h].push({ notion: f.id, lib: r.lib, avant: f.di, act: r.act }); } journal('faisceau-conclusion', { h, notion: f.id, lib: r ? r.lib : f.id, activite: r ? r.act : '', conclusion: f.concl, reponses: f.reps }); S.faisceau = null; ouvrirOuverture(); }; }
function ouvrirOuverture(){""")
rep("  x += `<div class=\"travail\"><b>Ce que l'heure ${h} jouera, dans l'ordre</b> : ","  x += faisceauHtml(h);\n  const rp = (S.reprisesPrevues || {})[h] || []; x += `<div class=\"travail\"><b>Ce que l'heure ${h} jouera, dans l'ordre</b> : ${rp.map(q => `<span class=\"puce\" style=\"color:var(--or)\">↺ reprise à l'oral de « ${esc(q.lib)} » avant « ${esc(q.act)} »</span>`).join('')}")
# les branchements de l'ouverture : après le rendu
rep("  poserHtml($('fin'), x); $('ecran-fin').classList.add('on', 'ouverture');","  poserHtml($('fin'), x); $('ecran-fin').classList.add('on', 'ouverture'); brancherFaisceau(h);")
# la reprise prévue dans « Où on en est » de l'heure : une ligne cliquable qui ouvre l'oral prérempli
rep("function ouOnEnEst(){","function reprisesPrevuesHtml(){ const rp = (S.reprisesPrevues || {})[S.heure] || []; const faites = (S.oraux || {})[S.heure] || []; return rp.filter(q => !faites.some(o => (o.notions || []).includes(q.notion))).map(q => `<div class=\"rep-prevue\" data-reprise=\"${esc(q.notion)}\" title=\"Reprise à l'oral prévue à l'ouverture de l'heure : un clic ouvre « Expliqué à l'oral » avec la notion déjà cochée\">↺ reprise à l'oral de <b>${esc(q.lib)}</b> avant « ${esc(q.act)} »</div>`).join(''); }\nfunction ouOnEnEst(){")
rep("\n.mur .ed-part{", r"""
.fais{background:#2a1416;border:1px solid #c4474b;border-radius:10px;padding:12px 16px;margin:10px 0;color:#f2c9c9}.fais h4{margin:0 0 8px;color:#ff8a8e;font-size:1rem}.fais .ctx{margin-bottom:10px;padding-left:10px;border-left:2px solid #c4474b}.fais .ctx b{color:#fff}.fais .q{font-size:1.15rem;color:#fff;margin:8px 0}.fais .rep{display:flex;gap:10px;margin:8px 0}.fais .rep button{font:inherit;font-size:1.05rem;padding:8px 22px;border-radius:10px;border:1px solid #c4474b;background:#3a1c1e;color:#fff;cursor:pointer}.fais .rep .oui{background:#c99a4e;border-color:#c99a4e;color:#1c1712;font-weight:700}.fais .fil{font-size:.85rem;color:#e0a0a3;margin-top:4px}.fais .fil b{color:#fff}.fais .concl{margin-top:10px;padding:8px 10px;background:#1c1712;border-radius:8px;color:#e8dcc4}.fais .concl b{color:#c99a4e}
.rep-prevue{background:#2a2114;border:1px dashed #c99a4e;border-radius:8px;padding:5px 10px;margin:6px 0;color:#e0c48c;font-size:.9rem;cursor:pointer}.rep-prevue b{color:#fff}
.chap-alerte{margin-top:6px;color:#ff8a8e;font-size:.9rem}.chap-n.manquante-pour-la-suite .chap-etat{background:rgba(232,72,76,.3);color:#ffb3b5}
.mur .ed-part{""")
open(p,'w',encoding='utf-8').write(s); print("(g2) écrit — partie 1")
# ── (g2) partie 2 : la reprise prévue dans « Où on en est » (cliquable → oral prérempli) ; le chapitre : l'alerte sur l'heure à venir et « manquante pour la suite »
s=open(p,encoding='utf-8').read()
rep("  const d = $('durees'); poserHtml(d, lignes.join(''));","  const d = $('durees'); poserHtml(d, lignes.join('') + reprisesPrevuesHtml()); d.querySelectorAll('[data-reprise]').forEach(l => l.onclick = () => { const q = ((S.reprisesPrevues || {})[S.heure] || []).find(x => x.notion === l.dataset.reprise); ouvrirOral({ act: null, notion: l.dataset.reprise, texte: '' }); if (q) journal('reprise-prevue-ouverte', { notion: q.notion }); });")
rep("aVenir.forEach(h => { const sim = HEURES_SIM[h]; const prevu = E.filter(e => e.heure === h).map(e => e.act).slice(0, 4); h1 += `<div class=\"chap-h avenir\"><div class=\"chap-t\"><b>Heure ${h}</b> — ${sim ? esc(sim.jour) : 'à venir'} · <i>à venir : la trame prévoit</i> ${prevu.map(esc).join(', ')}…</div></div>`; });",
    "aVenir.forEach(h => { const sim = HEURES_SIM[h]; const prevu = E.filter(e => e.heure === h).map(e => e.act).slice(0, 4); const rm = remobNonTravaillees(h); h1 += `<div class=\"chap-h avenir\"><div class=\"chap-t\"><b>Heure ${h}</b> — ${sim ? esc(sim.jour) : 'à venir'} · <i>à venir : la trame prévoit</i> ${prevu.map(esc).join(', ')}…</div>${rm.map(r => `<div class=\"chap-alerte\">⚠ « ${esc(r.act)} » remobilise <b>${esc(r.lib)}</b> — <b>non travaillée</b>${r.source ? ' (« ' + esc(r.source.titre) + ' » ' + esc(r.sourceEtat) + ')' : ''}. À régler à l'ouverture de l'heure ${h}.</div>`).join('')}</div>`; });")
rep("const ligneN = (n, f) => { const pv = prevues[n.id] || [], vu = vues[n.id] || [], dn = donnees[n.id] || []; const etat = vu.length ? 'travaillée' : (pv.some(x => aVenir.includes(x.h)) ? 'à venir' : (pv.length ? 'non travaillée' : (imprev[n.id] ? 'imprévue' : '')));",
    "const manquantes = {}; aVenir.forEach(h => remobNonTravaillees(h).forEach(r => { manquantes[r.id] = manquantes[r.id] || []; manquantes[r.id].push({ h, act: r.act }); }));\n  const ligneN = (n, f) => { const pv = prevues[n.id] || [], vu = vues[n.id] || [], dn = donnees[n.id] || []; const etat = manquantes[n.id] && !vu.length ? 'manquante pour la suite' : vu.length ? 'travaillée' : (pv.some(x => aVenir.includes(x.h)) ? 'à venir' : (pv.length ? 'non travaillée' : (imprev[n.id] ? 'imprévue' : '')));")
rep("if (!pv.length && !vu.length && !dn.length && !imprev[n.id]) return '';","if (!pv.length && !vu.length && !dn.length && !imprev[n.id] && !manquantes[n.id]) return '';")
rep("${imprev[n.id] ? ' · <i>imprévue, ajoutée pendant l\\'heure</i>' : ''}</div>`; };","${imprev[n.id] ? ' · <i>imprévue, ajoutée pendant l\\'heure</i>' : ''}${manquantes[n.id] && !vu.length ? ' · <i>attendue par ' + manquantes[n.id].map(x => '« ' + esc(x.act) + ' » (heure ' + x.h + ')').join(', ') + '</i>' : ''}</div>`; };")
# le chapitre lit « travaillée » avec le même critère que le pilotage (l'activité finie, ou l'oral)
rep("const vues = {}; J.filter(x => x.type === 'diapo' && E[x.di]).forEach(x => { (E[x.di].comp || []).forEach(id => { vues[id] = vues[id] || []; vues[id].push({ h: x.h, act: E[x.di].act }); }); }); Object.keys(S.notionsOral || {}).forEach(id => { const o = S.notionsOral[id]; vues[id] = vues[id] || []; vues[id].push({ h: o.h, act: (o.par || 'à l\\'oral') + (o.par && /oral/.test(o.par) ? '' : ' (à l\\'oral)') }); });","const vues = {}; const trav = notionsTravaillees(); Object.keys(trav).forEach(id => { const t = trav[id]; vues[id] = [{ h: t.h, act: (t.par || '') + (t.oral && !/oral/.test(t.par || '') ? ' (à l\\'oral)' : '') }]; });")
# l'ouverture : une activité décalée par le faisceau est marquée dans l'ordre de l'heure
rep("${E[i].role === 'reactivation' ? ' <i style=\"color:var(--ambre)\">réactivation</i>' : ''}","${E[i].role === 'reactivation' ? ' <i style=\"color:var(--ambre)\">réactivation</i>' : ''}${retiree(E[i]) && decisionDe(E[i]) && decisionDe(E[i]).remob ? ' <i style=\"color:var(--rouge)\">↪ décalée à l\\'heure suivante</i>' : ''}")
rep("· v9c.14 g1 — <b>provisoire</b> : le faisceau à l'ouverture en g2 <span","· v9c.14 g <span")
open(p,'w',encoding='utf-8').write(s); print("(g2) écrit — partie 2")
