p='vis/v9c15p1-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (p1) l'atelier : un troisième onglet du même écran (cadrage 4 · 1.1)
rep('<button class="ong" id="ong-relecture" title="Le récit de l\'heure et ce qui s\'est passé (R)">Relecture</button>','<button class="ong" id="ong-relecture" title="Le récit de l\'heure et ce qui s\'est passé (R)">Relecture</button><button class="ong" id="ong-atelier" title="L\'atelier : la préparation de la séance, diapo par diapo — le même écran, la même diapo, rien n\'est joué ni écrit">Atelier</button>')
rep("function voir(v){ ['fnotes', 'fcomm', 'fnotion', 'freserve', 'fdocs', 'fsimu', 'ppop', 'vif-palette', 'menu', 'menuplus'].forEach(id => $(id).classList.remove('on')); document.body.classList.toggle('vue-relecture', v === 'relecture'); $('ecran-relecture').classList.toggle('on', v === 'relecture'); $('ong-pilotage').classList.toggle('on', v !== 'relecture'); $('ong-relecture').classList.toggle('on', v === 'relecture'); if (v === 'relecture') relecture(); }",
    "function voir(v){ ['fnotes', 'fcomm', 'fnotion', 'freserve', 'fdocs', 'fsimu', 'ppop', 'vif-palette', 'menu', 'menuplus'].forEach(id => $(id).classList.remove('on')); document.body.classList.toggle('vue-relecture', v === 'relecture'); $('ecran-relecture').classList.toggle('on', v === 'relecture'); const at = v === 'atelier'; if (at !== !!S.atelier) { S.atelier = at; journal(at ? 'atelier-ouvert' : 'atelier-ferme', { di: S.di }); } document.body.classList.toggle('vue-atelier', at); $('ong-pilotage').classList.toggle('on', v === 'pilotage'); $('ong-relecture').classList.toggle('on', v === 'relecture'); $('ong-atelier').classList.toggle('on', at); if (v === 'relecture') relecture(); else tout(); }\n$('ong-atelier').onclick = () => voir('atelier');")
# le HTML : la barre de l'atelier (sous la diapo), les zones de l'atelier
rep('<div id="poignee-mur" class="poignee-mur"','<div id="outils-atelier" class="outils-atelier" style="display:none"><button class="btn" disabled title="Ajoute un bloc à la diapo (à venir : p2)">+ bloc</button><button class="btn" disabled title="Ajoute une étape (à venir : p2)">+ étape</button><button class="btn" disabled title="Ajoute une image (à venir : p4)">+ image</button><button class="btn" disabled title="Lie une fiche d\'une feuille du chapitre (à venir : p4)">+ fiche…</button><button class="btn" disabled title="Ajoute une vidéo (à venir : p4)">+ vidéo…</button><span class="at-taille">taille : <b>normal</b></span><span class="at-save" id="at-save" title="L\'enregistrement est automatique, quelques secondes après la frappe (à venir : p2)">✔ enregistré</span><button class="btn or" id="at-jouer" title="Jouer en avance : le même écran que le pilotage, la fenêtre du tableau possible — rien n\'est écrit (ni journal, ni copie), aucune garde, aucun gel">▶ Jouer en avance</button></div><div id="poignee-mur" class="poignee-mur"')
rep("\n.mur .ed-part{", r"""
/* (p1) l'atelier */
.vue-atelier #chr,.vue-atelier #heure,.vue-atelier #bfin,.vue-atelier #btableau,.vue-atelier #bvideoproj,.vue-atelier #bqui,.vue-atelier .outils,.vue-atelier #compte,.vue-atelier #al-boite,.vue-atelier #al-ligne{display:none !important}.vue-atelier #outils-atelier{display:flex !important}.vue-atelier #droite-fin,.vue-atelier .suivante,.vue-atelier #suivi,.vue-atelier .suivi,.vue-atelier #droite > :not(#droite-atelier){display:none !important}.vue-atelier #droite-atelier{display:block !important}#droite-atelier{display:none}.vue-atelier #numero + *{display:none !important}
.outils-atelier{display:flex;gap:8px;align-items:center;padding:6px 0;font-size:.9rem;color:var(--texte2)}.outils-atelier .btn{padding:5px 10px}.outils-atelier .at-taille{margin-left:8px}.outils-atelier .at-save{margin-left:auto;color:var(--joue);font-size:.85rem}
.at-chap{font-size:.86rem}.at-chap .sea{margin:6px 0 4px;color:var(--or);font-weight:700;font-size:.8rem;letter-spacing:.04em}.at-chap .sea2{margin:8px 0 4px;color:var(--texte2);font-weight:700;font-size:.8rem}.at-chap .fr{margin:8px 0 4px;padding:3px 6px;border-top:1px dashed var(--bord2);color:var(--texte2);font-size:.75rem;display:flex;justify-content:space-between;gap:6px}.at-chap .fr .plus{color:#ff8a8e;font-weight:700}.at-chap .d{display:flex;gap:6px;align-items:center;padding:3px 6px;border-radius:6px;color:var(--texte2);cursor:pointer}.at-chap .d:hover{background:var(--carte)}.at-chap .d.on{background:var(--carte);color:var(--texte);border:1px solid var(--or)}.at-chap .d .n{width:18px;color:var(--sourd);text-align:right;flex:none}.at-chap .d .t{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.at-chap .d .a{font-size:.7rem;color:var(--or);flex:none}.at-chap .d .h{font-size:.72rem;color:var(--sourd);flex:none}.at-chap .aide{color:var(--sourd);font-size:.75rem;margin-top:10px}
.at-d{background:var(--carte);border:1px solid var(--bord);border-radius:8px;padding:8px 12px;margin-bottom:8px;font-size:.88rem}.at-d h5{margin:0 0 4px;font-size:.72rem;letter-spacing:.06em;color:var(--or)}.at-d .l{padding:2px 0;color:var(--texte2)}.at-d .l b{color:var(--texte)}.at-d .ok{color:var(--joue)}.at-d .al{color:#ff8a8e}.at-d .al i{display:block;color:var(--texte2);font-size:.8rem}.at-note{color:var(--sourd);font-size:.75rem}
.mur .ed-part{""")
# la colonne de droite : un conteneur pour l'atelier
rep('<div id="droite-fin"','<div id="droite-atelier"></div><div id="droite-fin"')
# le rendu : en atelier, la diapo entière (tous ses éléments), sans compteur
rep("const etatComplet = () => { const et = etatComplet0();","const etatComplet = () => { const et = etatComplet0(); if (S.atelier) { et.atelier = true; et.nDev = elements(ecran()).length; }")
rep("function rendre(mur, et){ if (et && et.oral && !et.pilote) {","function rendre(mur, et){ if (et && et.atelier && et.pilote) { et = Object.assign({}, et, { nDev: elements(DATA.seances[et.si].ecrans[et.di]).length }); } if (et && et.oral && !et.pilote) {")
# le volet et la colonne de droite de l'atelier ; le numéro ; « Jouer en avance »
rep("function tout(){", r"""function creneauDe(di){ /* l'heure prévue d'une diapo : la base de son heure + le cumul des durées avant elle */ const E = seance().ecrans; const h = E[di].heure; const o = ordreHeure(h); let t = HEURES_SIM[h] ? HEURES_SIM[h].base : 0; for (const i of o) { if (i === di) break; t += (E[i].dur || 0) * 60000; } return { debut: t, fin: t + (E[di].dur || 0) * 60000 }; }
function voletAtelier(){ const E = seance().ecrans; const heures = [...new Set(E.map(e => e.heure))].sort(); const acts = DATA.activites[String(S.si)] || []; const numA = i => { const a = actDe(E[i]); return a ? 'A' + a.num : ''; }; let h = `<div class="at-chap"><div class="sea">Chapitre · ${esc(seance().titre)}</div><div class="sea2">Séance 1 — ${esc(seance().titre.split(':')[0].trim())} (${heures.length} h)</div>`; heures.forEach(hh => { const o = ordreHeure(hh); const prevu = o.filter(i => E[i].role !== 'fin').reduce((t, i) => t + (E[i].dur || 0), 0); const sim = HEURES_SIM[hh]; const dep = prevu + 5 - 50; h += `<div class="fr"><span>H${hh} · ${sim ? esc(sim.jour.replace(/ 2026$/, '')) : ''} · 55 min</span><span>${prevu} + 5 = ${prevu + 5} min ${dep > 0 ? '<span class="plus" title="Ce que l\'heure dépasse : réduis une durée ou déplace une diapo">+' + dep + '</span>' : '<span style="color:var(--joue)">✔</span>'}</span></div>`; o.forEach(i => { const e = E[i]; h += `<div class="d${i === S.di ? ' on' : ''}" data-at-di="${i}" title="Ouvre cette diapo dans l'atelier"><span class="n">${rangDe(i, hh)}</span><span class="t">${e.role === 'fin' ? 'Cahier de textes' : esc(e.act)}</span>${e.role === 'fin' ? '' : '<span class="a">' + numA(i) + '</span>'}<span class="h">${e.role === 'fin' ? 5 : (e.dur || 0)} min</span></div>`; }); }); h += `<div class="sea2" style="color:var(--sourd)">Séance 2 — (à venir dans la maquette) · H3</div><div class="aide">Ctrl + molette : zoom · clic droit : dupliquer, insérer, envoyer… (à venir : p3)</div></div>`; return h; }
function droiteAtelier(){ const E = seance().ecrans; const e = ecran(); const a = actDe(e); const dA = a ? diaposAct(a) : [e]; const rang = a ? dA.indexOf(S.di) + 1 : 1; const cr = creneauDe(S.di); const sim = HEURES_SIM[e.heure]; const comp = (e.comp || []).map(libNotion); const remob = (e.remob || []).map(libNotion); const nEl = elements(e).length;
  let x = `<div class="at-d"><h5>CE QUE LA DIAPO DÉCLARE</h5><div class="l">${a ? '<b>Activité ' + a.num + '</b> — ' + esc(a.titre) + ' · diapo ' + rang + ' sur ' + dA.length + ' de l\'activité' : (e.role === 'fin' ? '<b>Cahier de textes</b> — les cinq minutes réservées' : '<i>hors activité</i>')}</div><div class="l">Heure prévue : <b>H${e.heure}</b>${sim ? ' (' + esc(sim.jour.replace(/ 2026$/, '')) + ')' : ''} · <b>${e.role === 'fin' ? 5 : (e.dur || 0)} min</b> · ${hhmm(cr.debut)} → ${hhmm(cr.fin)} — <span class="at-note">proposée d'après les durées ; déplaçable</span></div><div class="l">Notions travaillées : ${comp.length ? comp.map(n => '<b>' + esc(n) + '</b>').join(', ') : '<i>aucune</i>'}</div><div class="l">Remobilise : ${remob.length ? remob.map(n => '<b>' + esc(n) + '</b>').join(', ') : '<i>rien</i>'}</div><div class="l">Éléments : ${nEl}${nEl > 1 ? ' · dévoilés un par un' : ''}</div></div>`;
  /* pour la classe : le temps et les notions */ const alertes = []; const h = e.heure; const o = ordreHeure(h); const prevu = o.filter(i => E[i].role !== 'fin').reduce((t, i) => t + (E[i].dur || 0), 0); const dep = prevu + 5 - 50; if (dep > 0) alertes.push(`⚠ L'heure ${h} dépasse de ${dep} min<i>${prevu} min d'activités + 5 min de cahier pour 50 utiles — le T-5 le redira ; réduis une durée ou déplace une diapo</i>`); const compTous = new Set(E.flatMap(z => z.comp || [])); E.forEach((z, i) => (z.remob || []).forEach(id => { const avant = E.some((y, j) => j < i && (y.comp || []).includes(id)); if (!avant) alertes.push(`⚠ « ${esc(z.act)} » (H${z.heure}) remobilise une notion que rien ne travaille avant<i>« ${esc(libNotion(id))} »${compTous.has(id) ? ' est travaillée plus tard — remonte l\'activité qui la travaille, ou change l\'ordre' : ' n\'est travaillée nulle part dans le chapitre'}</i>`); })); const jamais = [...new Set(E.flatMap(z => z.remob || []))].filter(id => !compTous.has(id)); if (jamais.length) alertes.push(`⚠ ${jamais.length} notion${jamais.length > 1 ? 's' : ''} remobilisée${jamais.length > 1 ? 's' : ''} ${jamais.length > 1 ? 'ne sont travaillées' : 'n\'est travaillée'} par aucune activité<i>${jamais.map(id => '« ' + esc(libNotion(id)) + ' »').join(', ')} — prévue${jamais.length > 1 ? 's' : ''} nulle part</i>`); x += `<div class="at-d"><h5>POUR LA CLASSE — le temps et les notions</h5>${alertes.length ? alertes.map(t => '<div class="l al">' + t + '</div>').join('') : '<div class="l ok">✔ Rien à signaler : l\'heure tient, les notions remobilisées sont travaillées avant</div>'}</div>`;
  /* sur la forme : seulement s'il y a quelque chose à dire */ const forme = []; (e.blocs || []).forEach((b, bi) => { if (b.t === 'fiche' && !b.feuille) forme.push(`⚠ La fiche « ${esc(b.txt || '')} » (bloc ${bi + 1}) n'est liée à aucune feuille du chapitre<i>lie-la à une feuille, ou le bloc ne s'affichera pas (cadrage 4, 1.7)</i>`); if ((b.t === 'html' || b.t === 'page') && !b.contrat) forme.push(`⚠ « ${esc(b.txt || 'page')} » est une page HTML sans contrat de pilotage<i>l'objet manque à l'éditeur : le texte prêt à copier pour l'instance est dans « À régler » (4.3)</i>`); if (b.t === 'video' && b.src && !/^(https?:|\/|\.)/.test(b.src)) forme.push(`⚠ La vidéo « ${esc(b.txt || '')} » pointe vers un fichier non atteignable<i>vérifie le chemin ou la clé USB (4 bis)</i>`); }); if (forme.length) x += `<div class="at-d"><h5>SUR LA FORME — ce qui peut casser en classe</h5>${forme.map(t => '<div class="l al">' + t + '</div>').join('')}<div class="at-note">Ces alertes ne s'affichent jamais pendant une heure réelle : elles se règlent ici, ou dans « À régler » du chapitre.</div></div>`;
  /* le chapitre */ const acts = DATA.activites[String(S.si)] || []; const nH = [...new Set(E.map(z => z.heure))].length; const notions = [...new Set(E.flatMap(z => (z.comp || []).concat(z.remob || [])))]; const trav = notions.filter(id => compTous.has(id)); x += `<div class="at-d"><h5>LE CHAPITRE</h5><div class="l">1 séance dans la maquette · ${nH} h · ${E.length} diapos · ${acts.length} activités · notions : ${notions.length}, <span class="ok">travaillées : ${trav.length}</span>${notions.length - trav.length ? ', <span class="al">jamais travaillées : ' + (notions.length - trav.length) + '</span>' : ''}</div><div class="l">Pages HTML : <b>${E.reduce((t, z) => t + (z.blocs || []).filter(b => b.t === 'html' || b.t === 'page').length, 0)}</b> · objets manquants à l'éditeur : <b>0</b> <span class="at-note">(à faire tendre vers zéro, 4.4)</span></div></div>`; return x; }
function tout(){ if (S.atelier) { const v = $('volet'); if (v) { const hv = voletAtelier(); if (v.dataset.atelier !== hv) { v.innerHTML = hv; v.dataset.atelier = hv; v.querySelectorAll('[data-at-di]').forEach(d => d.onclick = () => { S.di = +d.dataset.atDi; S.page = null; journal('atelier-diapo', { di: S.di }); tout(); }); } } const da = $('droite-atelier'); if (da) { const hd = droiteAtelier(); if (da.innerHTML !== hd) da.innerHTML = hd; } const aj = $('at-jouer'); if (aj && !aj._ok) { aj._ok = true; aj.onclick = () => { journal('atelier-jouer-en-avance', { di: S.di }); voir('pilotage'); }; } }""")
# le numéro en atelier ; l'EDT : « Éditer dans l'atelier »
rep("$('numero').textContent = `${rangDe(S.di) ? 'Diapo ' + rangDe(S.di) + ' sur ' + ordreHeure(S.heure).length","$('numero').innerHTML = S.atelier ? (function(){ const e = ecran(); const a = actDe(e); const cr = creneauDe(S.di); return `<b>Atelier · Diapo ${rangDe(S.di, e.heure)} sur ${ordreHeure(e.heure).length} · heure ${e.heure}${a ? ' · activité ' + a.num : ''} · ${esc(e.role === 'fin' ? 'Cahier de textes' : e.act)}</b> <span style=\"color:var(--texte2)\">· prévue ${e.role === 'fin' ? 5 : (e.dur || 0)} min · H${e.heure} ${hhmm(cr.debut).replace(':', ' h ')} → ${hhmm(cr.fin).replace(':', ' h ')}</span>`; })() : `${rangDe(S.di) ? 'Diapo ' + rangDe(S.di) + ' sur ' + ordreHeure(S.heure).length")
rep('<button class="btn" data-preparer="${h}" title="L\'atelier, là où la classe en est (maquette de la préparation : à venir)" disabled>Préparer</button>','<button class="btn" data-atelier="${h}" title="Ouvre l\'atelier sur la première diapo de cette heure : tu prépares, rien n\'est joué">Éditer dans l\'atelier</button>')
rep("  c.querySelectorAll('[data-lancer]').forEach(b => b.onclick = () => {","  c.querySelectorAll('[data-atelier]').forEach(b => b.onclick = () => { const h = +b.dataset.atelier; S.heure = h; S.di = ordreHeure(h)[0]; S.page = null; $('ecran-edt').classList.remove('on'); voir('atelier'); });\n  c.querySelectorAll('[data-lancer]').forEach(b => b.onclick = () => {")
rep("function volet(){","function volet(){ if (S.atelier) return; /* (p1) en atelier, la colonne du chapitre remplace les vignettes */")
rep("function pousser(et){","function pousser(et){ if (S.atelier) return; /* (p1) l'atelier ne pousse rien au tableau, n'écrit rien au journal, ne marque rien comme vu (cadrage 4, 1.5) */")
rep("const journal = (type, x) => { if (type === 'diapo'","const journal = (type, x) => { if (S.atelier && !/^atelier/.test(type)) return; if (type === 'diapo'")
rep("· v9c.14 g <span","· v9c.15 p1 — <b>provisoire</b> : l'atelier (p2 à p6 à venir) <span")
open(p,'w',encoding='utf-8').write(s); print("(p1) écrit")
