p='vis/v9c15p2-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (p2) écrire dans la diapo (cadrage 4 · 1.2, 1.6, 1.8)
rep("\n.mur .ed-part{", r"""
/* (p2) l'écriture dans la diapo */
.vue-atelier .mur [data-p]{cursor:text}.vue-atelier .mur [contenteditable]:focus{outline:none;background:#fff2c7;border-radius:.15em}.mur .bloc-edit{outline:2px dashed #c99a4e;outline-offset:6px;border-radius:.2em;position:relative}.mur .bloc-barre{position:absolute;right:-.2em;top:-1.7em;display:flex;gap:.2em;align-items:center;font-size:.42em;background:#fff;border:1px solid #c99a4e;border-radius:.5em;padding:.15em .3em;box-shadow:0 2px 8px rgba(0,0,0,.15);z-index:3}.mur .bloc-barre .nom{color:#c99a4e;letter-spacing:.06em;margin-right:.4em}.mur .bloc-barre button{font:inherit;border:1px solid #d9cfbf;background:#fbfaf5;border-radius:.4em;padding:.1em .5em;color:#1c1712;cursor:pointer}.mur .bloc-barre button:disabled{opacity:.4;cursor:default}.mur .bloc-barre .sep{width:1px;height:1.2em;background:#d9cfbf;margin:0 .2em}.mur li.li-neuf:empty:before,.mur li[data-vide]:empty:before{content:"(nouvelle étape — tape, Entrée pour la suivante, Échap pour l'annuler)";color:#8a7a66;font-style:italic}
.outils-atelier .at-save.dirty{color:var(--or)}.outils-atelier .at-save.err{color:#ff8a8e}
.at-aide{border-color:var(--or) !important;font-size:.82rem !important}.at-aide b{color:var(--or)}.at-aide .x{float:right;cursor:pointer;color:var(--sourd);margin-left:8px}
.mur .ed-part{""")
rep("function tout(){ if (S.atelier) {", r"""function blocDe(el){ const li = el.closest('[data-p]'); if (!li) return null; const [bi, ei] = li.dataset.p.split('.'); return { bi: +bi, ei: ei === 't' ? 't' : +ei, li }; }
function marquerModif(quoi){ S.atelierDirty = Date.now(); const sv = $('at-save'); if (sv) { sv.className = 'at-save dirty'; sv.textContent = '● modification en cours — enregistrement dans 3 s'; } journal('atelier-modif', quoi); }
function ecrireDansDiapo(el){ const b = blocDe(el); if (!b) return; const e = ecran(); const bloc = e.blocs[b.bi]; if (!bloc) return; const txt = el.textContent; if (b.ei === 't') bloc.txt = txt; else { bloc.el = bloc.el || []; bloc.el[b.ei] = txt; } marquerModif({ di: S.di, bi: b.bi, ei: b.ei, n: txt.length }); }
function elementsEditables(){ return Array.from(document.querySelectorAll('#mur [data-p][contenteditable]')); }
function elementsDeLaDiapo(){ return Array.from(document.querySelectorAll('#mur [data-p]')); }
function focaliser(el, fin){ if (!el) return; if (!el.getAttribute('contenteditable')) brancherAtelier(); /* le rendu du mur est différé : on branche avant de mettre le curseur */ el.focus(); if (fin !== false) { const r = document.createRange(); r.selectNodeContents(el); r.collapse(false); const sel = getSelection(); sel.removeAllRanges(); sel.addRange(r); } }
const atBranches = new WeakSet(); /* les nœuds branchés (un clone du morph n'y est pas : il sera rebranché) */
let atObs = null; function observerMur(){ if (atObs) return; const mur = $('mur'); if (!mur) return; atObs = new MutationObserver(() => { if (S.atelier) brancherAtelier(); }); atObs.observe(mur, { childList: true, subtree: true }); }
function brancherAtelier(){ const mur = $('mur'); if (!mur || !S.atelier) return; const e = ecran(); if (!e || e.role === 'fin') return;
  elementsDeLaDiapo().forEach(x => { if (!x.getAttribute('contenteditable')) { x.setAttribute('contenteditable', 'plaintext-only'); x.setAttribute('spellcheck', 'false'); x.title = 'Écris ici : c\'est enregistré tout seul quelques secondes après (Tab : l\'élément suivant · Entrée : un nouvel élément · Échap : annule une ligne vide)'; } /* le morph réutilise les nœuds et retire les attributs absents du nouveau rendu : on les repose à chaque passage ; les écouteurs, eux, une seule fois */ if (atBranches.has(x)) return; atBranches.add(x);
    x.addEventListener('focus', () => { mur.querySelectorAll('.bloc-edit').forEach(z => z.classList.remove('bloc-edit')); const conteneur = x.closest('ul, ol, .bloc, p') || x.parentElement; conteneur.classList.add('bloc-edit'); poserBarreBloc(conteneur, blocDe(x)); });
    x.addEventListener('input', () => ecrireDansDiapo(x));
    x.addEventListener('keydown', ev => { const e = ecran(); /* la diapo du moment, pas celle du branchement : le morph réutilise les nœuds d'une diapo à l'autre */ const all = elementsEditables(); const k = all.indexOf(x); if (['Tab', 'Enter', 'Escape'].includes(ev.key) || (ev.altKey && /^Arrow/.test(ev.key))) ev.stopPropagation(); /* le clavier global (Échap ferme, flèches naviguent) ne reçoit pas ce que l'atelier traite */ if (ev.key === 'Tab') { ev.preventDefault(); const n = all[k + (ev.shiftKey ? -1 : 1)]; if (n) focaliser(n); return; } if (ev.key === 'Enter') { ev.preventDefault(); const b = blocDe(x); if (!b || b.ei === 't') { const n = all[k + 1]; if (n) focaliser(n); return; } const bloc = e.blocs[b.bi]; bloc.el = bloc.el || []; bloc.el.splice(b.ei + 1, 0, ''); marquerModif({ di: S.di, bi: b.bi, ajout: b.ei + 1 }); tout(); setTimeout(() => { const nv = mur.querySelector(`[data-p="${b.bi}.${b.ei + 1}"]`); if (nv) { nv.setAttribute('data-vide', '1'); focaliser(nv); } }, 0); return; } if (ev.key === 'Escape') { const b = blocDe(x); if (b && b.ei !== 't' && !x.textContent.trim()) { ev.preventDefault(); const bloc = e.blocs[b.bi]; if ((bloc.el || []).length > 1) { bloc.el.splice(b.ei, 1); marquerModif({ di: S.di, bi: b.bi, retrait: b.ei }); tout(); setTimeout(() => { const prev = mur.querySelector(`[data-p="${b.bi}.${Math.max(0, b.ei - 1)}"]`); if (prev) focaliser(prev); }, 0); } } return; } if (ev.altKey && (ev.key === 'ArrowUp' || ev.key === 'ArrowDown')) { ev.preventDefault(); const b = blocDe(x); if (b) deplacerBloc(b.bi, ev.key === 'ArrowUp' ? -1 : 1); } });
  }); }
function poserBarreBloc(conteneur, b){ const mur = $('mur'); mur.querySelectorAll('.bloc-barre').forEach(z => z.remove()); if (!b) return; const e = ecran(); const bloc = e.blocs[b.bi]; if (!bloc) return; const n = (bloc.el || []).length; const barre = document.createElement('div'); barre.className = 'bloc-barre'; barre.innerHTML = `<span class="nom">BLOC ${b.bi + 1} · ${esc((bloc.t || '').toUpperCase())} · ${n} ÉLÉMENT${n > 1 ? 'S' : ''}</span><button data-bb="haut" title="Monte ce bloc d\'un cran dans la diapo (Alt + ↑)" ${b.bi === 0 ? 'disabled' : ''}>▲</button><button data-bb="bas" title="Descend ce bloc d\'un cran (Alt + ↓)" ${b.bi >= e.blocs.length - 1 ? 'disabled' : ''}>▼</button><span class="sep"></span><button data-bb="etape" title="Ajoute un élément à la fin de ce bloc (Entrée en fin de ligne fait pareil)">+ étape</button><button data-bb="suppr" title="Supprime ce bloc — le site demande confirmation si des réponses d\'élèves y sont accrochées (1.8)">✕</button>`; conteneur.appendChild(barre); barre.querySelectorAll('[data-bb]').forEach(bt => bt.addEventListener('mousedown', ev => ev.preventDefault())); barre.querySelector('[data-bb="haut"]').onclick = () => deplacerBloc(b.bi, -1); barre.querySelector('[data-bb="bas"]').onclick = () => deplacerBloc(b.bi, 1); barre.querySelector('[data-bb="etape"]').onclick = () => { bloc.el = bloc.el || []; bloc.el.push(''); marquerModif({ di: S.di, bi: b.bi, ajout: bloc.el.length - 1 }); tout(); setTimeout(() => { const nv = mur.querySelector(`[data-p="${b.bi}.${bloc.el.length - 1}"]`); if (nv) { nv.setAttribute('data-vide', '1'); focaliser(nv); } }, 0); }; barre.querySelector('[data-bb="suppr"]').onclick = () => supprimerBloc(b.bi); }
function deplacerBloc(bi, sens){ const e = ecran(); const j = bi + sens; if (j < 0 || j >= e.blocs.length) return; const t = e.blocs[bi]; e.blocs[bi] = e.blocs[j]; e.blocs[j] = t; marquerModif({ di: S.di, bloc: bi, vers: j }); tout(); setTimeout(() => { const el = $('mur').querySelector(`[data-p^="${j}."]`); if (el) focaliser(el, false); }, 0); }
function supprimerBloc(bi){ const e = ecran(); const st = parDiapo[K(S.di)] || { reps: {} }; const reps = Object.keys(st.reps || {}).filter(k => +k === bi && (st.reps[k] || []).length).length; if (reps && !confirm('Des réponses d\'élèves sont accrochées à ce bloc : les supprimer avec lui ?')) return; if (e.blocs.length <= 1) { alert('Une diapo garde au moins un bloc.'); return; } e.blocs.splice(bi, 1); marquerModif({ di: S.di, supprime: bi, reps }); tout(); }
setInterval(() => { const sv = $('at-save'); if (!sv || !S.atelier) return; if (S.atelierDirty) { const d = Math.ceil((3000 - (Date.now() - S.atelierDirty)) / 1000); if (d <= 0) { S.atelierDirty = null; S.atelierSaved = Date.now(); sv.className = 'at-save'; sv.textContent = '✔ enregistré'; journal('atelier-enregistre', { di: S.di }); } else sv.textContent = '● modification en cours — enregistrement dans ' + d + ' s'; } else if (S.atelierSaved) { const n = Math.round((Date.now() - S.atelierSaved) / 1000); sv.textContent = '✔ enregistré' + (n >= 1 ? ' il y a ' + (n < 60 ? n + ' s' : Math.round(n / 60) + ' min') : ''); } }, 1000);
function tout(){ if (S.atelier) { observerMur(); setTimeout(brancherAtelier, 0); """)
rep('<button class="btn" disabled title="Ajoute un bloc à la diapo (à venir : p2)">+ bloc</button><button class="btn" disabled title="Ajoute une étape (à venir : p2)">+ étape</button>','<button class="btn" id="at-bloc" title="Ajoute un bloc de texte à la fin de la diapo (une consigne et ses étapes) ; le curseur va dedans">+ bloc</button><button class="btn" id="at-etape" title="Ajoute une étape à la fin du bloc où tu es (ou du dernier bloc) ; le curseur va dedans">+ étape</button>')
rep("function tout(){ if (S.atelier) { observerMur(); setTimeout(brancherAtelier, 0);", r"""function tout(){ if (S.atelier) { observerMur(); setTimeout(brancherAtelier, 0); const ab = $('at-bloc'); if (ab && !ab._ok) { ab._ok = true; ab.onclick = () => { const e = ecran(); if (!e || e.role === 'fin') return; e.blocs.push({ t: 'consigne', bid: 'b' + Date.now().toString(36), txt: 'Nouveau bloc', el: [''] }); marquerModif({ di: S.di, bloc: 'ajout', bi: e.blocs.length - 1 }); tout(); setTimeout(() => { const nv = $('mur').querySelector('[data-p="' + (e.blocs.length - 1) + '.t"]'); if (nv) focaliser(nv); }, 0); }; } const ae = $('at-etape'); if (ae && !ae._ok) { ae._ok = true; ae.onclick = () => { const e = ecran(); if (!e || e.role === 'fin') return; const b = document.activeElement && blocDe(document.activeElement); const bi = b ? b.bi : e.blocs.length - 1; const bloc = e.blocs[bi]; if (!bloc) return; bloc.el = bloc.el || []; bloc.el.push(''); marquerModif({ di: S.di, bi, ajout: bloc.el.length - 1 }); tout(); setTimeout(() => { const nv = $('mur').querySelector('[data-p="' + bi + '.' + (bloc.el.length - 1) + '"]'); if (nv) { nv.setAttribute('data-vide', '1'); focaliser(nv); } }, 0); }; }""")
rep("function droiteAtelier(){ const E = seance().ecrans; const e = ecran();","function droiteAtelier(){ const E = seance().ecrans; const e = ecran(); const aide = S.aideFermee ? '' : '<div class=\"at-d at-aide\" id=\"at-aide\"><span class=\"x\" title=\"Ferme l\\'aide\">✕</span><b>Écrire dans la diapo</b> — un clic dans un bloc, tu tapes ; <b>Tab</b> passe à l\\'élément suivant, <b>Maj + Tab</b> au précédent, <b>Entrée</b> en fin de ligne crée l\\'élément suivant, <b>Échap</b> annule une ligne vide ; <b>Alt + ↑ / ↓</b> monte ou descend le bloc. Rien à sauver : c\\'est enregistré quelques secondes après la frappe, et le témoin le dit.</div>'; return aide + droiteAtelier0(e, E); }\nfunction droiteAtelier0(e, E){")
rep("const da = $('droite-atelier'); if (da) { const hd = droiteAtelier(); if (da.innerHTML !== hd) da.innerHTML = hd; }","const da = $('droite-atelier'); if (da) { const hd = droiteAtelier(); if (da.innerHTML !== hd) { da.innerHTML = hd; const ax = da.querySelector('#at-aide .x'); if (ax) ax.onclick = () => { S.aideFermee = true; tout(); }; } }")
rep("· v9c.15 p1 — <b>provisoire</b> : l'atelier (p2 à p6 à venir) <span","· v9c.15 p2 — <b>provisoire</b> : l'atelier (p3 à p6 à venir) <span")
open(p,'w',encoding='utf-8').write(s); print("(p2) écrit")
