p='vis/v9c15p3-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (p3) le clic droit complet de l'atelier (cadrage 4 · 1.4, 0.4)
# la taille d'un bloc (petit / normal / grand) se lit au rendu, pilote comme tableau
rep("const fsB = et.fsBloc || {};","const fsB = Object.assign({}, et.fsBloc || {}); (e.blocs || []).forEach((b, bi) => { if (b.taille === 'petit') fsB[bi] = (fsB[bi] || 1) * 0.85; if (b.taille === 'grand') fsB[bi] = (fsB[bi] || 1) * 1.2; });")
rep("function brancherMenus(){\n  // sur une diapo (volet et scène), sur un bloc / une ligne / une réponse, sur un nom\n  $('volet').oncontextmenu = ev => { const v = ev.target.closest('.vig'); if (!v) return; ev.preventDefault(); menuDiapo(+v.dataset.i, ev.clientX, ev.clientY); };\n  mur.oncontextmenu = ev => { ev.preventDefault();",
    "function brancherMenus(){\n  // sur une diapo (volet et scène), sur un bloc / une ligne / une réponse, sur un nom\n  $('volet').oncontextmenu = ev => { if (S.atelier) { const d = ev.target.closest('[data-at-di]'); if (!d) return; ev.preventDefault(); menuAtelierDiapo(+d.dataset.atDi, ev.clientX, ev.clientY); return; } const v = ev.target.closest('.vig'); if (!v) return; ev.preventDefault(); menuDiapo(+v.dataset.i, ev.clientX, ev.clientY); };\n  mur.oncontextmenu = ev => { ev.preventDefault(); if (S.atelier) { menuAtelierMur(ev); return; }")
rep("function blocDe(el){", r"""/* ── (p3) l'atelier : les gestes sur la trame, tous par identité ── */
function toast(msg){ let t = $('at-toast'); if (!t) { t = document.createElement('div'); t.id = 'at-toast'; t.style.cssText = 'position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#1c1712;color:#e8dcc4;border:1px solid var(--or);border-radius:10px;padding:8px 14px;font-size:.9rem;z-index:90;max-width:70vw'; document.body.appendChild(t); } t.textContent = msg; t.style.display = 'block'; clearTimeout(t._t); t._t = setTimeout(() => { t.style.display = 'none'; }, 4000); }
const nouvelEid = () => 'e' + Date.now().toString(36) + Math.random().toString(36).slice(2, 6); const nouveauBid = () => 'b' + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
const roleFixe = e => e.role === 'fin' ? 'la diapo de fin d\'heure' : e.role === 'bilan' ? 'le bilan de la séance' : e.role === 'reactivation' ? 'la réactivation' : null;
function apresTrame(quoi){ reindexer(); if (S.ordres) { Object.keys(S.ordres).forEach(h => { if (!(S.closes && S.closes[h]) && !(S.lancee && +h === S.heure)) delete S.ordres[h]; }); } marquerModif(quoi); tout(); }
function cloneBloc(b){ const c = JSON.parse(JSON.stringify(b)); c.bid = nouveauBid(); return c; }
function dupliquerDiapo(i){ const E = seance().ecrans; const e = E[i]; const rf = roleFixe(e); if (rf) return alert(rf + ' ne se duplique pas.'); const c = JSON.parse(JSON.stringify(e)); c.eid = nouvelEid(); c.act = e.act + ' (copie)'; c.blocs = (c.blocs || []).map(cloneBloc); delete c.ajouteeALImport; E.splice(i + 1, 0, c); apresTrame({ di: i, duplique: c.eid }); S.di = i + 1; tout(); }
function insererDiapoApres(i){ const E = seance().ecrans; const e = E[i]; if (e.role === 'bilan') return alert('Rien ne s\'insère après le bilan : il reste le dernier de la séance.'); if (e.role === 'fin') return alert('Rien ne s\'insère après la fin d\'heure : insère avant elle.'); const c = { eid: nouvelEid(), act: 'Nouvelle diapo', heure: e.heure, dur: 5, role: null, comp: [], blocs: [{ t: 'consigne', bid: nouveauBid(), txt: 'Nouvelle diapo', el: [''] }], actId: e.actId }; E.splice(i + 1, 0, c); apresTrame({ di: i, insere: c.eid }); S.di = i + 1; tout(); }
function deplacerDiapo(i, sens){ const E = seance().ecrans; const e = E[i]; const rf = roleFixe(e); if (rf) return alert(rf + ' ne se déplace pas : elle reste à sa place dans son heure.'); const j = i + sens; if (j < 0 || j >= E.length) return; const v = E[j]; if (v.role === 'bilan' && sens > 0) return alert('Rien ne passe après le bilan.'); if (v.role === 'reactivation' && sens < 0) return alert('Rien ne passe avant la réactivation.'); let dit = ''; if (v.role === 'fin' && sens > 0) { /* on franchit la frontière d'heure : la diapo change d'heure prévue, la fin d'heure reste la dernière de la sienne */ const hSuiv = E.slice(j + 1).find(z => z.heure !== e.heure); if (!hSuiv) return alert('Il n\'y a pas d\'heure après : la fin d\'heure reste la dernière.'); E.splice(i, 1); E.splice(j, 0, e); e.heure = hSuiv.heure; dit = `elle passe en H${e.heure}`; } else if (v.heure !== e.heure) { E.splice(i, 1); E.splice(j, 0, e); const anc = e.heure; e.heure = v.heure; dit = `elle passe en H${e.heure} (elle était en H${anc})`; } else { E[i] = v; E[j] = e; } apresTrame({ di: i, deplace: e.eid, vers: j, heure: e.heure }); S.di = indexDe(e.eid); if (dit) toast('Diapo déplacée : ' + dit + ' — le compte des heures est recalculé.'); tout(); }
function supprimerDiapo(i){ const E = seance().ecrans; const e = E[i]; const rf = roleFixe(e); if (rf) return alert(rf + ' ne se supprime pas.'); const vue = !!vuMax[K(i)] || J.some(x => x.type === 'diapo' && x.eid === e.eid); if (!confirm('Supprimer « ' + e.act + ' » de la trame ?' + (vue ? ' Une classe l\'a déjà vue : elle la garde dans sa copie, seule la trame change.' : ''))) return; E.splice(i, 1); apresTrame({ supprime: e.eid, vue }); S.di = Math.min(i, E.length - 1); tout(); }
function couperDiapoIci(i, bi){ const E = seance().ecrans; const e = E[i]; if (!bi || bi >= (e.blocs || []).length) return alert('Choisis un bloc qui n\'est pas le premier : la diapo se coupe avant lui.'); const suite = JSON.parse(JSON.stringify(e)); suite.eid = nouvelEid(); suite.act = e.act + ' (suite)'; suite.blocs = e.blocs.slice(bi); e.blocs = e.blocs.slice(0, bi); suite.dur = Math.round((e.dur || 0) / 2); e.dur = (e.dur || 0) - suite.dur; E.splice(i + 1, 0, suite); apresTrame({ di: i, coupe: bi, suite: suite.eid }); toast('Diapo coupée : « ' + suite.act + ' », même heure, mêmes notions.'); tout(); }
function envoyerVersSeance(i){ const E = seance().ecrans; const e = E[i]; if (DATA.seances.length < 2) return alert('Une seule séance dans le chapitre : rien où envoyer.'); const choix = DATA.seances.map((sc, k) => k === S.si ? null : (k + 1) + ' · ' + (sc.titre || 'séance ' + (k + 1))).filter(Boolean); const rep = prompt('Envoyer « ' + e.act + ' » vers quelle séance ? Tape son numéro :\n' + choix.join('\n')); if (!rep) return; const k = parseInt(rep, 10) - 1; if (!(k >= 0 && k < DATA.seances.length) || k === S.si) return alert('Numéro inconnu.'); const cible = DATA.seances[k]; const heures = [...new Set(cible.ecrans.map(z => z.heure))].sort(); const hFin = heures[heures.length - 1] || 1; /* identité inchangée ; à l'arrivée : la dernière heure de la séance cible, avant sa fin d'heure (et avant le bilan) */ E.splice(i, 1); e.heure = hFin; delete e.actId; let pos = cible.ecrans.length; for (let q = cible.ecrans.length - 1; q >= 0; q--) { if (cible.ecrans[q].role === 'fin' || cible.ecrans[q].role === 'bilan') pos = q; else break; } cible.ecrans.splice(pos, 0, e); apresTrame({ envoye: e.eid, vers: k, heure: hFin }); S.di = Math.min(i, E.length - 1); toast('Diapo envoyée vers la séance ' + (k + 1) + ' (H' + hFin + ') — identité inchangée, heure recalculée à l\'arrivée.'); tout(); }
function menuAtelierDiapo(i, x, y){ const E = seance().ecrans; const e = E[i]; const a = actDe(e); const rf = roleFixe(e); const h = e.heure; const o = ordreHeure(h); const enTete = `${e.role === 'fin' ? 'Cahier de textes (fin d\'heure)' : e.act}${a ? ' · A' + a.num : ''} · H${h}`;
  let noteDesc = ''; const j = i + 1; if (!rf && E[j] && E[j].role === 'fin') { const hS = E.slice(j + 1).find(z => z.heure !== h); if (hS) { const p1 = o.filter(k => E[k].role !== 'fin' && k !== i).reduce((t, k) => t + (E[k].dur || 0), 0); const p2 = ordreHeure(hS.heure).filter(k => E[k].role !== 'fin').reduce((t, k) => t + (E[k].dur || 0), 0) + (e.dur || 0); noteDesc = `↓ en descendant, elle passe en H${hS.heure} : l'heure ${h} revient à ${p1} + 5 = ${p1 + 5} min${p1 + 5 - 50 > 0 ? ' +' + (p1 + 5 - 50) : ' ✔'}, l'heure ${hS.heure} monte à ${p2 + 5} min${p2 + 5 - 50 > 0 ? ' +' + (p2 + 5 - 50) : ' ✔'}`; } }
  const items = [{ a: 'titre', l: enTete, off: true }, '-', { a: 'ouvrir', l: 'Ouvrir', t: 'Entrée — la diapo dans l\'atelier', off: i === S.di }, { a: 'dupliquer', l: 'Dupliquer', off: !!rf, t: rf ? rf + ' ne se duplique pas (2.6)' : 'Ctrl + D — une nouvelle diapo juste après, mêmes blocs, nouvelle identité (les réponses d\'élèves n\'y sont pas), notions copiées, heure héritée' }, { a: 'inserer', l: 'Insérer une diapo après', off: e.role === 'bilan' || e.role === 'fin', t: e.role === 'bilan' ? 'rien après le bilan' : e.role === 'fin' ? 'rien après la fin d\'heure : insère avant elle' : 'Ctrl + Entrée — une diapo vide juste après, dans la même heure, sans rôle' }, '-', { a: 'monter', l: 'Monter', off: !!rf || i === 0, t: rf ? rf + ' reste à sa place' : 'Alt + ↑ — l\'ordre change, pas l\'identité : ce que la classe a fait sur cette diapo la suit' }, { a: 'descendre', l: 'Descendre', off: !!rf || i >= E.length - 1, t: rf ? rf + ' reste la dernière de son heure' : 'Alt + ↓ — si elle franchit la frontière d\'heure, elle change d\'heure prévue et le site le dit' }, ...(noteDesc ? [{ a: 'note', l: noteDesc, off: true, ss: true }] : []), { a: 'envoyer', l: 'Envoyer vers une autre séance…', off: !!rf || DATA.seances.length < 2, t: DATA.seances.length < 2 ? 'une seule séance dans la maquette' : 'identité inchangée, heure recalculée à l\'arrivée' }, '-', { a: 'couper', l: 'Couper la diapo ici…', off: !!rf || (e.blocs || []).length < 2, t: (e.blocs || []).length < 2 ? 'un seul bloc : rien à couper' : 'ouvre la diapo : clic droit sur le bloc où couper (0.4)' }, { a: 'supprimer', l: 'Supprimer', off: !!rf, t: rf ? 'chaque heure garde ' + rf + ' (1.4)' : 'Suppr — une classe qui l\'a déjà vue la garde dans sa copie ; les notions du chapitre se recalculent' }];
  menuA($('menu'), x, y, items); $('menu').onclick = ev => { const b = ev.target.closest('[data-a]'); if (!b || b.disabled) return; $('menu').classList.remove('on'); const act = b.dataset.a; journal('atelier-menu', { di: i, action: act }); if (act === 'ouvrir') { S.di = i; S.page = null; tout(); } if (act === 'dupliquer') dupliquerDiapo(i); if (act === 'inserer') insererDiapoApres(i); if (act === 'monter') deplacerDiapo(i, -1); if (act === 'descendre') deplacerDiapo(i, 1); if (act === 'envoyer') envoyerVersSeance(i); if (act === 'couper') { S.di = i; S.page = null; tout(); toast('Clic droit sur le bloc où couper, puis « Couper la diapo ici ».'); } if (act === 'supprimer') supprimerDiapo(i); }; }
function menuAtelierMur(ev){ const li = ev.target.closest('li[data-p]'); const blocEl = ev.target.closest('[data-bi]'); const e = ecran(); if (!e || e.role === 'fin') return; const bi = blocEl ? +blocEl.dataset.bi : (li ? +li.dataset.p.split('.')[0] : null); if (bi == null || !e.blocs[bi]) return; const b = e.blocs[bi]; const n = (b.el || []).length; const ei = li && li.dataset.p.split('.')[1] !== 't' ? +li.dataset.p.split('.')[1] : null;
  if (ei != null) { const items = [{ a: 'titre', l: `Élément ${ei + 1} sur ${n} · bloc ${bi + 1}`, off: true }, '-', { a: 'e-dupliquer', l: 'Dupliquer l\'élément' }, { a: 'e-monter', l: 'Monter', off: ei === 0 }, { a: 'e-descendre', l: 'Descendre', off: ei >= n - 1 }, '-', { a: 'e-supprimer', l: 'Supprimer l\'élément', off: n <= 1, t: n <= 1 ? 'un bloc garde au moins un élément' : 'Suppr' }]; menuA($('menu'), ev.clientX, ev.clientY, items); $('menu').onclick = ev2 => { const bt = ev2.target.closest('[data-a]'); if (!bt || bt.disabled) return; $('menu').classList.remove('on'); const act = bt.dataset.a; journal('atelier-menu', { di: S.di, bi, ei, action: act }); if (act === 'e-dupliquer') b.el.splice(ei + 1, 0, b.el[ei]); if (act === 'e-monter') { const t = b.el[ei - 1]; b.el[ei - 1] = b.el[ei]; b.el[ei] = t; } if (act === 'e-descendre') { const t = b.el[ei + 1]; b.el[ei + 1] = b.el[ei]; b.el[ei] = t; } if (act === 'e-supprimer') b.el.splice(ei, 1); marquerModif({ di: S.di, bi, ei, action: act }); tout(); }; return; }
  const image = b.t === 'image'; const items = image ? [{ a: 'titre', l: `Image · bloc ${bi + 1}`, off: true }, '-', { a: 'b-supprimer', l: 'Supprimer l\'image' }] : [{ a: 'titre', l: `Bloc ${bi + 1} · ${(b.t || '').toUpperCase()} · ${n} élément${n > 1 ? 's' : ''}`, off: true }, '-', { a: 'b-dupliquer', l: 'Dupliquer le bloc', t: 'juste après, nouvelle identité' }, { a: 'b-monter', l: 'Monter', off: bi === 0, t: 'Alt + ↑' }, { a: 'b-descendre', l: 'Descendre', off: bi >= e.blocs.length - 1, t: 'Alt + ↓' }, { a: 'b-taille', l: `Taille : ${b.taille === 'petit' ? '[petit]' : 'petit'} · ${!b.taille || b.taille === 'normal' ? '[normal]' : 'normal'} · ${b.taille === 'grand' ? '[grand]' : 'grand'}`, t: 'tourne : petit → normal → grand ; la classe le verra à cette taille' }, '-', { a: 'b-copier', l: 'Copier', t: 'Ctrl + C' }, { a: 'b-couper', l: 'Couper', t: 'Ctrl + X', off: e.blocs.length <= 1 }, { a: 'b-coller', l: 'Coller ici', off: !S.pressePapiers, t: S.pressePapiers ? 'Ctrl + V — coller donne toujours une nouvelle identité : le bloc est neuf jusqu\'à sa première apparition' : 'rien dans le presse-papiers' }, '-', { a: 'b-couper-diapo', l: 'Couper la diapo ici', off: bi === 0, t: bi === 0 ? 'la diapo se coupe avant un bloc qui n\'est pas le premier' : 'une seconde diapo « (suite) » avec ce bloc et les suivants, même heure, mêmes notions (0.4)' }, { a: 'b-supprimer', l: 'Supprimer le bloc', t: 'confirmation si des réponses d\'élèves y sont accrochées' }];
  menuA($('menu'), ev.clientX, ev.clientY, items); $('menu').onclick = ev2 => { const bt = ev2.target.closest('[data-a]'); if (!bt || bt.disabled) return; $('menu').classList.remove('on'); const act = bt.dataset.a; journal('atelier-menu', { di: S.di, bi, action: act }); if (act === 'b-dupliquer') { e.blocs.splice(bi + 1, 0, cloneBloc(b)); marquerModif({ di: S.di, bi, duplique: true }); tout(); } if (act === 'b-monter') deplacerBloc(bi, -1); if (act === 'b-descendre') deplacerBloc(bi, 1); if (act === 'b-taille') { b.taille = b.taille === 'petit' ? 'normal' : (!b.taille || b.taille === 'normal') ? 'grand' : 'petit'; marquerModif({ di: S.di, bi, taille: b.taille }); tout(); } if (act === 'b-copier') { S.pressePapiers = JSON.parse(JSON.stringify(b)); toast('Bloc copié.'); } if (act === 'b-couper') { S.pressePapiers = JSON.parse(JSON.stringify(b)); e.blocs.splice(bi, 1); marquerModif({ di: S.di, bi, coupe: true }); tout(); } if (act === 'b-coller') { e.blocs.splice(bi + 1, 0, cloneBloc(S.pressePapiers)); marquerModif({ di: S.di, bi, colle: true }); tout(); } if (act === 'b-couper-diapo') couperDiapoIci(S.di, bi); if (act === 'b-supprimer') supprimerBloc(bi); }; }
function blocDe(el){""")
# les raccourcis de l'atelier sur la diapo ouverte (hors champ de saisie) : Ctrl + D, Ctrl + Entrée, Suppr, Alt + ↑ / ↓
rep("$('ong-atelier').onclick = () => voir('atelier');","$('ong-atelier').onclick = () => voir('atelier');\ndocument.addEventListener('keydown', ev => { if (!S.atelier) return; const champ = /INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName) || document.activeElement.isContentEditable; if (champ) return; if ($('menu').classList.contains('on')) return; if (ev.ctrlKey && (ev.key === 'd' || ev.key === 'D')) { ev.preventDefault(); dupliquerDiapo(S.di); } else if (ev.ctrlKey && ev.key === 'Enter') { ev.preventDefault(); insererDiapoApres(S.di); } else if (ev.key === 'Delete') { ev.preventDefault(); supprimerDiapo(S.di); } else if (ev.altKey && ev.key === 'ArrowUp') { ev.preventDefault(); deplacerDiapo(S.di, -1); } else if (ev.altKey && ev.key === 'ArrowDown') { ev.preventDefault(); deplacerDiapo(S.di, 1); } }, true);")
rep("· v9c.15 p2 — <b>provisoire</b> : l'atelier (p3 à p6 à venir) <span","· v9c.15 p3 — <b>provisoire</b> : l'atelier (p4 à p6 à venir) <span")
open(p,'w',encoding='utf-8').write(s); print("(p3) écrit")
