p='vis/v9c15p4a-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (p4a) les objets et leurs gardes (cadrage 4 · §3, §4, 1.7, 3.3, 4.3, 6.1)
# la donnée simulée : les feuilles du chapitre et leurs fiches (cadrage 1.7) ; quatre fiches de la trame liées, deux non liées ; un objet inconnu sur une diapo ; une page HTML sans contrat
rep("const $ = id => document.getElementById(id);", r"""/* (p4a) simulation de la donnée : les feuilles du chapitre (les fiches vivent là) ; quatre fiches liées, deux non liées ; un objet inconnu et une page sans contrat sur « Trois mots pour la frise » */ DATA.feuilles = [{ id: 'f-romantisme', titre: 'Le Romantisme — repères', fiches: [{ id: 'fi-lyrique', titre: 'Le registre lyrique', el: ["Le registre d’un texte, c’est l’effet qu’il produit sur le lecteur.", 'Le lyrique exprime des sentiments personnels.'] }, { id: 'fi-sonnet', titre: 'Le sonnet', el: ['Quatorze vers : deux quatrains, deux tercets.', 'La chute au dernier vers.'] }, { id: 'fi-dates', titre: 'Le Romantisme en cinq dates', el: ['1820 : Les Méditations de Lamartine.', "1830 : la bataille d’Hernani."] }] }, { id: 'f-phrase', titre: 'Grammaire — la phrase', fiches: [{ id: 'fi-pipp', titre: 'P.I et P.P', el: ['La P.I se suffit à elle-même ; la P.P a besoin de ses subordonnées.'] }, { id: 'fi-psr', titre: 'La PSR', el: ['La proposition subordonnée relative complète un nom.'] }, { id: 'fi-que', titre: '« Que » et la PSCc', el: ['« Que » introduit une conjonctive complétive.'] }, { id: 'fi-psci', titre: 'La PSCci', el: ['La circonstancielle dit quand, pourquoi, comment.'] }] }]; (function(){ const lie = { 'b1140': ['f-romantisme', 'fi-lyrique'], 'b230': ['f-phrase', 'fi-pipp'], 'b280': ['f-phrase', 'fi-psr'], 'b420': ['f-romantisme', 'fi-sonnet'] }; DATA.seances.forEach(se => se.ecrans.forEach(e => (e.blocs || []).forEach(b => { if (b.t === 'fiche' && lie[b.bid]) { b.feuille = lie[b.bid][0]; b.fiche = lie[b.bid][1]; } }))); const E = DATA.seances[0].ecrans; const rh = E.find(e => e.act === 'Les règles héritées'); if (rh) { rh.blocs = (rh.blocs || []).concat([{ t: 'fiche', bid: 'b-sim-fiche-nonliee', txt: 'Le registre lyrique', el: ["Le registre d’un texte, c’est l’effet qu’il produit sur le lecteur."] }]); } const cible = E.find(e => e.act === 'Trois mots pour la frise'); if (cible) { cible.blocs = (cible.blocs || []).concat([{ t: 'tableau-double', bid: 'b-sim-inconnu', txt: 'Comparaison en deux colonnes' }, { t: 'page', bid: 'b-sim-page', txt: 'Placer les poètes', src: 'placer-les-poetes.html', contrat: false }]); } })();
const $ = id => document.getElementById(id);""")
# le rendu : les types connus ; « texte » se rend comme une consigne sans puce ; un type inconnu → « objet non lisible » (pilote et atelier), rien au tableau ; une fiche non liée → rien au tableau, une note au pilote ; une page → sa vignette et son contrat
rep("      if (b.t === 'consigne') { h += `<div class=\"cons${marqBloc}${lumBloc}\" data-bloc=\"${bi}\"><span class=\"pic\">${esc(b.pic || '•')}</span>",
    "      const TYPES = ['consigne', 'texte', 'question', 'fiche', 'schema', 'image', 'video', 'page']; if (!TYPES.includes(b.t)) { if (et.pilote || et.atelier) alertesDiapo.push(`<div class=\"obj-nonlisible\" data-bloc=\"${bi}\"><b>⚠ Objet non lisible — « ${esc(b.t || '?')} » (bloc ${bi + 1})</b>Rien ne s'affiche à sa place en classe, jamais une page blanche. Déclare un objet manquant, ou remplace-le (3.1) ; le texte pour l'instance est dans « À régler ».</div>`); h += '</div>'; return; }\n      if (b.t === 'fiche' && !b.feuille) { if (et.pilote || et.atelier) alertesDiapo.push(`<div class=\"obj-nonlisible\" data-bloc=\"${bi}\"><b>⚠ Fiche non liée — « ${esc(b.txt || '')} » (bloc ${bi + 1})</b>Lie-la à une fiche d'une feuille du chapitre (clic droit → Lier à une fiche…), sinon le bloc ne s'affiche pas en classe (1.7).</div>`); h += '</div>'; return; }\n      if (b.t === 'page') { h += `<div class=\"page-sup${marqBloc}${lumBloc}\" data-bloc=\"${bi}\"><div class=\"page-t\" data-p=\"${bi}.t\">${surligne(esc(titre), bi + '.t', et)}</div><div class=\"page-v\">page HTML — ${esc(b.src || 'sans fichier')}${b.contrat ? ' · ' + (b.etapes || '?') + ' étapes, pilotée aux flèches' : ((et.pilote || et.atelier) ? ' · <b style=\"color:#b3261e\">sans contrat de pilotage : jouée comme une image</b>' : '')}</div></div>`; h += '</div>'; return; }\n      if (b.t === 'consigne' || b.t === 'texte') { h += `<div class=\"cons${marqBloc}${lumBloc}\" data-bloc=\"${bi}\">${b.t === 'texte' ? '' : `<span class=\"pic\">${esc(b.pic || '•')}</span>`}")
rep("const numA = numDe(e); const actLib = (numA ? 'Activité ' + numA + ' — ' : '') + e.act; let h = '';","const numA = numDe(e); const actLib = (numA ? 'Activité ' + numA + ' — ' : '') + e.act; let h = ''; const alertesDiapo = []; /* (p4a) les alertes de forme de la diapo : une bandelette en surimpression, elles ne prennent pas la place du contenu */")
rep("      h += '</div>'; });\n    h += '</div>';\n  }\n  if (e.legende &&","      h += '</div>'; });\n    h += '</div>';\n  }\n  if (alertesDiapo.length) h += '<div class=\"alertes-diapo\">' + alertesDiapo.join('') + '</div>';\n  if (e.legende &&")
rep("\n.mur .ed-part{", r"""
/* (p4a) les objets */
.mur .alertes-diapo{position:absolute;left:.6em;right:.6em;bottom:.5em;display:flex;flex-direction:column;gap:.2em;z-index:5;pointer-events:none}.mur .obj-nonlisible{border:2px dashed #b3261e;border-radius:.3em;padding:.3em .6em;color:#b3261e;font-size:.42em;background:#fff4f4;pointer-events:auto}.mur .obj-nonlisible b{display:block;font-size:1.05em}.mur .page-sup .page-t{font-weight:700;margin-bottom:.1em}.mur .page-sup .page-v{font-size:.55em;color:#6a5a48;border:1px dashed #c99a4e;border-radius:.4em;padding:.3em .6em;background:#fbfaf5}
.choix-obj{position:absolute;left:12px;right:12px;bottom:60px;background:#fbfaf5;color:#1c1712;border:1px solid #c99a4e;border-radius:12px;box-shadow:0 8px 30px rgba(0,0,0,.35);padding:12px 14px;z-index:70}.choix-obj h4{margin:0 0 8px;font-size:.8rem;letter-spacing:.06em;color:#8a7a66;display:flex;justify-content:space-between}.choix-obj h4 .x{cursor:pointer;color:#8a7a66}.choix-obj .g{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.choix-obj .c{border:1px solid #d9cfbf;border-radius:8px;padding:8px 10px;cursor:pointer;background:#fff}.choix-obj .c:hover{border-color:#c99a4e;background:#fff7e0}.choix-obj .c b{display:block;font-size:.95rem}.choix-obj .c span{font-size:.78rem;color:#6a5a48}.choix-obj .c.dernier{border-style:dashed;color:#8a7a66}.choix-obj .c.off{opacity:.45;cursor:default}.choix-obj .manque{margin-top:10px;font-size:.85rem;color:#b3261e}.choix-obj .manque a{color:#b3261e;cursor:pointer;text-decoration:underline}
.choix-obj .form{margin-top:8px;font-size:.9rem}.choix-obj .form label{display:block;margin:6px 0 2px;color:#6a5a48;font-size:.8rem}.choix-obj .form input,.choix-obj .form select{font:inherit;padding:5px 8px;border:1px solid #c99a4e;border-radius:6px;width:100%;box-sizing:border-box;background:#fff}.choix-obj .form .err{color:#b3261e;font-size:.82rem;margin-top:4px}.choix-obj .form .ok{margin-top:8px}.choix-obj .form .fi{display:inline-block;margin:4px 8px 0 0;padding:3px 8px;border:1px solid #c99a4e;border-radius:6px;cursor:pointer;font-size:.85rem}.choix-obj .form .fi:hover{background:#fff7e0}.choix-obj .form .fe{margin:6px 0;padding:6px 10px;border:1px solid #d9cfbf;border-radius:8px;background:#fff}.choix-obj .form .fe b{color:#1a7a3e}
.at-regler{margin-top:8px}.at-regler button{font:inherit;font-size:.8rem;padding:4px 8px;border:1px solid #c4474b;border-radius:6px;background:#2a1416;color:#ff8a8e;cursor:pointer}
.mur .ed-part{""")
# la barre de l'atelier : « + bloc » ouvre le choix d'objet ; « + image » et « + fiche… » ouvrent le formulaire du type ; « + vidéo… » reste (p4b)
rep("const ab = $('at-bloc'); if (ab && !ab._ok) { ab._ok = true; ab.onclick = () => { const e = ecran(); if (!e || e.role === 'fin') return; e.blocs.push({ t: 'consigne', bid: 'b' + Date.now().toString(36), txt: 'Nouveau bloc', el: [''] }); marquerModif({ di: S.di, bloc: 'ajout', bi: e.blocs.length - 1 }); tout(); setTimeout(() => { const nv = $('mur').querySelector('[data-p=\"' + (e.blocs.length - 1) + '.t\"]'); if (nv) focaliser(nv); }, 0); }; }",
    "const ab = $('at-bloc'); if (ab && !ab._ok) { ab._ok = true; ab.onclick = () => choixObjet(); } const ai = $('at-image'); if (ai && !ai._ok) { ai._ok = true; ai.onclick = () => choixObjet('image'); } const af = $('at-fiche'); if (af && !af._ok) { af._ok = true; af.onclick = () => choixObjet('fiche'); }")
rep('<button class="btn" disabled title="Ajoute une image (à venir : p4)">+ image</button><button class="btn" disabled title="Lie une fiche d\'une feuille du chapitre (à venir : p4)">+ fiche…</button>','<button class="btn" id="at-image" title="Ajoute une image : une adresse relative dans mjpc-medias, une légende — jamais une adresse complète">+ image</button><button class="btn" id="at-fiche" title="Montre une fiche d\'une feuille du chapitre : le bloc n\'existe pas sans fiche liée">+ fiche…</button>')
rep("function blocDe(el){", r"""/* ── (p4a) le choix d'objet, les formulaires du contrat, le manque d'objet, « À régler » ── */
const OBJETS = [{ t: 'texte', l: 'Texte', d: 'un titre, quelques lignes — pour dire, pas pour faire' }, { t: 'consigne', l: 'Consigne', d: 'à l\'impératif, des étapes — ce que l\'élève fait' }, { t: 'question', l: 'Question', d: 'jamais vide ; ses réponses attendues à part, jamais dévoilées avec elle' }, { t: 'fiche', l: 'Fiche…', d: 'seulement liée à une fiche d\'une feuille du chapitre — sinon refus' }, { t: 'schema', l: 'Schéma…', d: 'carte, frise, arbre, cycle, tableau — se dévoile élément par élément' }, { t: 'image', l: 'Image…', d: 'une adresse relative dans mjpc-medias, une légende, des marques' }, { t: 'video', l: 'Vidéo…', d: 'un fichier sur ta clé USB, des repères — jamais hébergée (p4b)', off: true }, { t: 'page', l: 'Page HTML…', d: 'dernier recours, après un manque déclaré, avec son contrat de pilotage', dernier: true }];
function fermerChoix(){ const z = document.querySelector('.choix-obj'); if (z) z.remove(); }
function choixObjet(type){ fermerChoix(); const e = ecran(); if (!e || e.role === 'fin') return; const z = document.createElement('div'); z.className = 'choix-obj'; z.innerHTML = `<h4><span>QUEL OBJET AJOUTER À LA DIAPO ? — chacun a son contrat (cadrage 4, §3)</span><span class="x" title="Ferme sans rien ajouter">✕</span></h4><div class="g">${OBJETS.map(o => `<div class="c${o.dernier ? ' dernier' : ''}${o.off ? ' off' : ''}" data-t="${o.t}" title="${esc(o.d)}"><b>${o.l}</b><span>${esc(o.d)}</span></div>`).join('')}</div><div class="manque">Aucun objet ne convient ? <a data-manque="1">Déclarer un objet manquant</a> — « objet à ajouter à l'éditeur : … » : la ligne reste visible dans « À régler » du chapitre, avec ce qui l'attend (3.3). Personne ne tord un objet pour en faire un autre.</div><div class="form" id="obj-form"></div>`; document.querySelector('.scene').appendChild(z); z.querySelector('.x').onclick = fermerChoix; z.querySelectorAll('.c:not(.off)').forEach(c => c.onclick = () => formulaireObjet(c.dataset.t)); z.querySelector('[data-manque]').onclick = () => formulaireObjet('manque'); if (type) formulaireObjet(type); }
function ajouterBloc(b, focusT){ const e = ecran(); b.bid = nouveauBid(); e.blocs.push(b); marquerModif({ di: S.di, bloc: 'ajout', type: b.t, bi: e.blocs.length - 1 }); fermerChoix(); tout(); setTimeout(() => { const nv = $('mur').querySelector('[data-p="' + (e.blocs.length - 1) + '.t"]'); if (nv && focusT !== false) focaliser(nv); }, 0); }
function formulaireObjet(t){ const f = $('obj-form'); if (!f) return; const e = ecran();
  if (t === 'texte') return ajouterBloc({ t: 'texte', txt: 'Nouveau texte', el: [''] });
  if (t === 'consigne') return ajouterBloc({ t: 'consigne', txt: 'Nouvelle consigne', el: [''] });
  if (t === 'question') { f.innerHTML = `<label>La question (jamais vide)</label><input id="of-q" placeholder="Qu'ont en commun ces cinq tableaux ?"><label>La réponse attendue (à part, jamais dévoilée avec la question)</label><input id="of-r" placeholder="Une nature immense, un homme petit…"><div class="err" id="of-err"></div><div class="ok"><button class="btn or" id="of-ok">Ajouter la question</button></div>`; $('of-ok').onclick = () => { const q = $('of-q').value.trim(), r = $('of-r').value.trim(); if (!q) { $('of-err').textContent = 'Refus : une question n\'est jamais vide.'; return; } if (!r) { $('of-err').textContent = 'Refus : la réponse attendue manque — elle vit à part, c\'est le contrat.'; return; } ajouterBloc({ t: 'question', txt: q, el: [r] }, false); }; $('of-q').focus(); return; }
  if (t === 'fiche') { f.innerHTML = `<label>Quelle fiche ? — une fiche vit dans une feuille du chapitre (1.7) ; le bloc ne fait que la montrer</label>${DATA.feuilles.map(fe => `<div class="fe"><b>Feuille « ${esc(fe.titre)} »</b> · ${fe.fiches.length} fiche${fe.fiches.length > 1 ? 's' : ''}<br>${fe.fiches.map(fi => `<span class="fi" data-fe="${fe.id}" data-fi="${fi.id}" title="Lie cette fiche : le bloc la montre, elle s'agrandit d'un clic en classe">${esc(fi.titre)}</span>`).join('')}</div>`).join('')}<div class="err">Pas de fiche qui convienne ? Écris-la d'abord dans une feuille du chapitre (l'éditeur de feuilles), puis reviens la lier ici. Le bloc n'existe pas sans fiche liée.</div>`; f.querySelectorAll('.fi').forEach(x => x.onclick = () => { const fe = DATA.feuilles.find(z => z.id === x.dataset.fe); const fi = fe.fiches.find(z => z.id === x.dataset.fi); if (S.lierFiche != null) { const b = e.blocs[S.lierFiche]; b.feuille = fe.id; b.fiche = fi.id; b.txt = fi.titre; b.el = fi.el.slice(); S.lierFiche = null; marquerModif({ di: S.di, bi: e.blocs.indexOf(b), lie: fi.id }); fermerChoix(); tout(); } else ajouterBloc({ t: 'fiche', txt: fi.titre, feuille: fe.id, fiche: fi.id, el: fi.el.slice() }, false); }); return; }
  if (t === 'schema') { f.innerHTML = `<label>La forme du schéma — chacune avec le format de sa source ; échelle « plein » par défaut ; se dévoile élément par élément</label><select id="of-forme"><option value="carte">carte</option><option value="frise">frise</option><option value="arbre">arbre</option><option value="cycle">cycle</option><option value="tableau">tableau</option></select><label>Le titre</label><input id="of-t" placeholder="Les figures de style"><div class="err" id="of-err"></div><div class="ok"><button class="btn or" id="of-ok">Ajouter le schéma</button></div>`; $('of-ok').onclick = () => { const tt = $('of-t').value.trim(); if (!tt) { $('of-err').textContent = 'Refus : un schéma a un titre.'; return; } ajouterBloc({ t: 'schema', txt: tt, forme: $('of-forme').value, echelle: 'plein', el: [] }, false); }; return; }
  if (t === 'image') { f.innerHTML = `<label>L'adresse dans mjpc-medias — relative (jamais complète)</label><input id="of-src" placeholder="poesie-peinture-xixe/tableau-6.jpg"><label>La légende</label><input id="of-lg" placeholder="Le Radeau de la Méduse, Géricault, 1819"><div class="err" id="of-err"></div><div class="ok"><button class="btn or" id="of-ok">Ajouter l'image</button></div>`; $('of-ok').onclick = () => { const src = $('of-src').value.trim(), lg = $('of-lg').value.trim(); if (!src) { $('of-err').textContent = 'Refus : une image a une adresse.'; return; } if (/^(https?:)?\/\//i.test(src) || /^[a-z]:\\/i.test(src)) { $('of-err').textContent = 'Refus : l\'adresse doit être relative dans mjpc-medias, jamais complète (3.2).'; return; } ajouterBloc({ t: 'image', txt: lg, ref: 'https://siteflow-io.github.io/mjpc-medias/' + src.replace(/^\/+/, '') }, false); }; return; }
  if (t === 'page') { const manques = (S.objetsManquants || []).filter(m => m.si === S.si); f.innerHTML = `<label>Une page HTML ne se fait que si aucun objet ne convient, après un manque déclaré, et sur ton mot (4.1)</label>${manques.length ? `<div class="err" style="color:#1a7a3e">Manque déclaré : ${manques.map(m => '« ' + esc(m.texte) + ' »').join(', ')}</div>` : '<div class="err">Aucun manque d\'objet déclaré dans ce chapitre : déclare-le d\'abord, ou attends l\'objet (un mandat court sur l\'éditeur).</div>'}<label>Le fichier de la page</label><input id="of-src" placeholder="placer-les-poetes.html" ${manques.length ? '' : 'disabled'}><label>Le titre</label><input id="of-t" placeholder="Placer les poètes" ${manques.length ? '' : 'disabled'}><label><input type="checkbox" id="of-contrat" style="width:auto" ${manques.length ? '' : 'disabled'}> La page porte son contrat de pilotage (elle annonce ses étapes, reçoit suivante / précédente, répond où elle en est — 4.2)</label><div class="err" id="of-err"></div><div class="ok"><button class="btn or" id="of-ok" ${manques.length ? '' : 'disabled'}>Ajouter la page</button></div>`; if (manques.length) $('of-ok').onclick = () => { const src = $('of-src').value.trim(), tt = $('of-t').value.trim(); const contrat = $('of-contrat').checked; if (!src || !tt) { $('of-err').textContent = 'Refus : un fichier et un titre.'; return; } ajouterBloc({ t: 'page', txt: tt, src, contrat, etapes: contrat ? 3 : null }, false); if (!contrat) toast('Page sans contrat de pilotage : elle sera jouée comme une image ; « À régler » porte le texte pour l\'instance (4.3).'); }; return; }
  if (t === 'manque') { f.innerHTML = `<label>Quel objet manque à l'éditeur ? — dis-le en un mot ou deux : la ligne restera visible dans « À régler », avec le chapitre qui l'attend (3.3)</label><input id="of-m" placeholder="un tableau à deux colonnes remplissable en classe"><div class="err" id="of-err"></div><div class="ok"><button class="btn or" id="of-ok">Déclarer le manque</button></div>`; $('of-ok').onclick = () => { const m = $('of-m').value.trim(); if (!m) { $('of-err').textContent = 'Dis ce qui manque.'; return; } S.objetsManquants = S.objetsManquants || []; S.objetsManquants.push({ si: S.si, di: S.di, texte: m, t: now() }); journal('atelier-objet-manquant', { di: S.di, texte: m }); marquerModif({ di: S.di, manque: m }); fermerChoix(); toast('Objet manquant déclaré : « ' + m + ' » — visible dans « À régler » ; ce chapitre l\'attend.'); tout(); }; $('of-m').focus(); return; } }
function alertesForme(){ /* tout ce qui peut casser en classe, chapitre entier : la liste de « À régler » (6.1), avec le texte prêt à copier */ const E = seance().ecrans; const out = []; E.forEach((e, i) => (e.blocs || []).forEach((b, bi) => { const ou = `diapo ${i + 1} · « ${e.act} » · bloc ${bi + 1}`; const TYPES = ['consigne', 'texte', 'question', 'fiche', 'schema', 'image', 'video', 'page']; if (!TYPES.includes(b.t)) out.push({ di: i, bi, k: 'nonlisible', l: `Objet non lisible « ${b.t} »`, ou, faire: 'déclare un objet manquant, ou remplace-le par un objet connu (3.1)', copier: `Dans le chapitre « ${seance().titre} », ${ou} : l'objet « ${b.t} » n'est pas dans le contrat de l'éditeur MJPC. Remplace-le par un objet du contrat (texte, consigne, question, fiche, schéma, image, vidéo, page avec contrat) ou déclare-le comme objet manquant.` }); if (b.t === 'fiche' && !b.feuille) out.push({ di: i, bi, k: 'fiche', l: `Fiche « ${b.txt || ''} » non liée à une feuille`, ou, faire: 'lie-la à une fiche d\'une feuille du chapitre (clic droit → Lier à une fiche…), sinon le bloc ne s\'affiche pas (1.7)', copier: `Dans le chapitre « ${seance().titre} », ${ou} : la fiche « ${b.txt || ''} » doit être écrite dans une feuille du chapitre et liée par son identifiant (feuille + fiche).` }); if (b.t === 'page' && !b.contrat) out.push({ di: i, bi, k: 'page', l: `Page HTML « ${b.txt || ''} » sans contrat de pilotage`, ou, faire: 'ajoute le contrat (la page annonce ses étapes, reçoit suivante / précédente, répond où elle en est — 4.2) ; jouée comme une image en attendant', copier: `Page « ${b.src || ''}» (${ou}) : ajoute le contrat de pilotage MJPC — au chargement, envoie postMessage({type:'mjpc-page', etapes:n}) ; réponds à {type:'mjpc-etape', aller:k} en affichant l'étape k et en renvoyant {type:'mjpc-ou', etape:k}.` }); if (b.t === 'image' && b.ref && !/mjpc-medias/.test(b.ref)) out.push({ di: i, bi, k: 'image', l: `Image « ${b.txt || ''} » hors de mjpc-medias`, ou, faire: 'range-la dans mjpc-medias et donne son adresse relative (3.2)', copier: `Image « ${b.ref} » (${ou}) : à ranger dans mjpc-medias, adresse relative.` }); })); (S.objetsManquants || []).filter(m => m.si === S.si).forEach(m => out.push({ di: m.di, k: 'manque', l: `Objet à ajouter à l'éditeur : « ${m.texte} »`, ou: `diapo ${m.di + 1} · « ${E[m.di] ? E[m.di].act : ''} »`, faire: 'un mandat court sur l\'éditeur, ou une page HTML pour cette fois, sur ton mot (4.1)', copier: `Mandat : ajouter à l'éditeur MJPC l'objet « ${m.texte} » (attendu par le chapitre « ${seance().titre} », ${E[m.di] ? E[m.di].act : ''}) avec son contrat aux trois endroits : prompt d'injection, validation à l'import, formulaire de l'éditeur.` })); return out; }
function ouvrirARegler(){ const al = alertesForme(); const z = document.createElement('div'); z.className = 'choix-obj'; z.innerHTML = `<h4><span>À RÉGLER — ${al.length ? al.length + ' chose' + (al.length > 1 ? 's' : '') + ' qui peu' + (al.length > 1 ? 'vent' : 't') + ' casser en classe, dans ce chapitre' : 'rien : ce chapitre ne cassera pas en classe'} (cadrage 4, 6.1)</span><span class="x">✕</span></h4>${al.map((a, k) => `<div class="fe"><b>${esc(a.l)}</b> — ${esc(a.ou)}<br><span style="color:#6a5a48;font-size:.85rem">${esc(a.faire)}</span><br><button class="btn" data-ouvrir="${a.di}" style="font-size:.8rem;margin-top:4px">Ouvrir la diapo</button> <button class="btn" data-copier="${k}" style="font-size:.8rem;margin-top:4px" title="Le texte prêt à copier pour l'instance (4.3)">Copier le texte pour l'instance</button></div>`).join('')}`; document.querySelector('.scene').appendChild(z); z.querySelector('.x').onclick = fermerChoix; z.querySelectorAll('[data-ouvrir]').forEach(b => b.onclick = () => { S.di = +b.dataset.ouvrir; S.page = null; fermerChoix(); tout(); }); z.querySelectorAll('[data-copier]').forEach(b => b.onclick = () => { const t = al[+b.dataset.copier].copier; S.dernierCopie = t; if (navigator.clipboard) navigator.clipboard.writeText(t).catch(() => {}); journal('atelier-copie-instance', { k: al[+b.dataset.copier].k }); toast('Copié : « ' + t.slice(0, 80) + '… »'); }); }
function blocDe(el){""")
# la carte « sur la forme » lit alertesForme (diapo ouverte seulement) ; « Le chapitre » compte les pages et les objets manquants ; un bouton « À régler (n) » dans la colonne de gauche
rep("  /* sur la forme : seulement s'il y a quelque chose à dire */ const forme = []; (e.blocs || []).forEach((b, bi) => { if (b.t === 'fiche' && !b.feuille) forme.push(`⚠ La fiche « ${esc(b.txt || '')} » (bloc ${bi + 1}) n'est liée à aucune feuille du chapitre<i>lie-la à une feuille, ou le bloc ne s'affichera pas (cadrage 4, 1.7)</i>`); if ((b.t === 'html' || b.t === 'page') && !b.contrat) forme.push(`⚠ « ${esc(b.txt || 'page')} » est une page HTML sans contrat de pilotage<i>l'objet manque à l'éditeur : le texte prêt à copier pour l'instance est dans « À régler » (4.3)</i>`); if (b.t === 'video' && b.src && !/^(https?:|\\/|\\.)/.test(b.src)) forme.push(`⚠ La vidéo « ${esc(b.txt || '')} » pointe vers un fichier non atteignable<i>vérifie le chemin ou la clé USB (4 bis)</i>`); });",
    "  /* sur la forme : seulement s'il y a quelque chose à dire — la part de la diapo ouverte de la liste « À régler » */ const forme = alertesForme().filter(a => a.di === S.di).map(a => `⚠ ${esc(a.l)}<i>${esc(a.faire)}</i>`);")
rep("<div class=\"l\">Pages HTML : <b>${E.reduce((t, z) => t + (z.blocs || []).filter(b => b.t === 'html' || b.t === 'page').length, 0)}</b> · objets manquants à l'éditeur : <b>0</b> <span class=\"at-note\">(à faire tendre vers zéro, 4.4)</span></div></div>`; return x; }",
    "<div class=\"l\">Pages HTML : <b>${E.reduce((t, z) => t + (z.blocs || []).filter(b => b.t === 'html' || b.t === 'page').length, 0)}</b> · objets manquants à l'éditeur : <b>${(S.objetsManquants || []).filter(m => m.si === S.si).length}</b> <span class=\"at-note\">(à faire tendre vers zéro, 4.4)</span></div><div class=\"at-regler\"><button id=\"at-regler\" title=\"La liste complète de ce qui peut casser en classe dans ce chapitre, avec la marche à suivre et le texte prêt à copier pour l'instance (6.1)\">À régler (${alertesForme().length})</button></div></div>`; return x; }")
rep("const da = $('droite-atelier'); if (da) { const hd = droiteAtelier(); if (da.innerHTML !== hd) { da.innerHTML = hd; const ax = da.querySelector('#at-aide .x'); if (ax) ax.onclick = () => { S.aideFermee = true; tout(); }; } }","const da = $('droite-atelier'); if (da) { const hd = droiteAtelier(); if (da.innerHTML !== hd) { da.innerHTML = hd; const ax = da.querySelector('#at-aide .x'); if (ax) ax.onclick = () => { S.aideFermee = true; tout(); }; const ar = da.querySelector('#at-regler'); if (ar) ar.onclick = ouvrirARegler; } }")
# le clic droit sur une fiche non liée : « Lier à une fiche… »
rep("{ a: 'b-dupliquer', l: 'Dupliquer le bloc', t: 'juste après, nouvelle identité' },","...(b.t === 'fiche' ? [{ a: 'b-lier', l: b.feuille ? 'Changer la fiche liée…' : 'Lier à une fiche…', t: 'la fiche vit dans une feuille du chapitre (1.7)' }] : []), { a: 'b-dupliquer', l: 'Dupliquer le bloc', t: 'juste après, nouvelle identité' },")
rep("if (act === 'b-dupliquer') { e.blocs.splice(bi + 1, 0, cloneBloc(b));","if (act === 'b-lier') { S.lierFiche = bi; choixObjet('fiche'); } if (act === 'b-dupliquer') { e.blocs.splice(bi + 1, 0, cloneBloc(b));")
# le clic droit sur un objet non lisible / une fiche non liée : le mur ne porte pas data-p pour eux : viser data-bloc
rep("function menuAtelierMur(ev){ const li = ev.target.closest('li[data-p]'); const blocEl = ev.target.closest('[data-bi]');","function menuAtelierMur(ev){ const li = ev.target.closest('li[data-p]'); const blocEl = ev.target.closest('[data-bi]') || ev.target.closest('[data-bloc]');")
rep("const bi = blocEl ? +blocEl.dataset.bi : (li ? +li.dataset.p.split('.')[0] : null);","const bi = blocEl ? +(blocEl.dataset.bi != null ? blocEl.dataset.bi : blocEl.dataset.bloc) : (li ? +li.dataset.p.split('.')[0] : null);")
rep("· v9c.15 p3 — <b>provisoire</b> : l'atelier (p4 à p6 à venir) <span","· v9c.15 p4a — <b>provisoire</b> : l'atelier (p4b à p6 à venir) <span")
open(p,'w',encoding='utf-8').write(s); print("(p4a) écrit")
