p='vis/v9c15p4b-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (p4b) la vidéo à préparer, la page pilotée (dette 30), l'objet document (cadrage 4 · 3.2, 4 bis, 4 ter, 4.2)
# 1. les objets : vidéo active, document ajouté
rep("{ t: 'video', l: 'Vidéo…', d: 'un fichier sur ta clé USB, des repères — jamais hébergée (p4b)', off: true }, { t: 'page', l: 'Page HTML…', d: 'dernier recours, après un manque déclaré, avec son contrat de pilotage', dernier: true }",
    "{ t: 'video', l: 'Vidéo…', d: 'un fichier sur ta clé USB, des repères — jamais hébergée' }, { t: 'doc', l: 'Document…', d: 'un document de la séance posé dans le flux : PDF, Word, image à pages, page HTML — tout type, le contrat dit comment il se projette' }, { t: 'page', l: 'Page HTML…', d: 'dernier recours, après un manque déclaré, avec son contrat de pilotage', dernier: true }")
rep("const TYPES = ['consigne', 'texte', 'question', 'fiche', 'schema', 'image', 'video', 'page'];","const TYPES = ['consigne', 'texte', 'question', 'fiche', 'schema', 'image', 'video', 'page', 'doc'];")
rep("const TYPES = ['consigne', 'texte', 'question', 'fiche', 'schema', 'image', 'video', 'page']; if (!TYPES.includes(b.t)) out.push(","const TYPES = ['consigne', 'texte', 'question', 'fiche', 'schema', 'image', 'video', 'page', 'doc']; if (!TYPES.includes(b.t)) out.push(")
# 2. le formulaire vidéo (dossier de la clé simulé, fichier, légende, repères) ; le formulaire document (joindre ou choisir ; le type par extension)
rep("  if (t === 'manque') {", r"""  if (t === 'video') { const b = S.editerVideo != null ? e.blocs[S.editerVideo] : null; const cle = S.cleDossier; const reps = b ? (b.reperes || []).slice() : [{ t: 0, l: '' }]; const mmss = t => Math.floor(t / 60) + ':' + String(t % 60).padStart(2, '0'); const lignes = () => reps.map((r, k) => `<div class="rl" style="display:flex;gap:8px;margin:3px 0"><input style="width:90px" data-rt="${k}" value="${mmss(r.t)}" title="m:ss"><input data-rl="${k}" value="${esc(r.l)}" placeholder="le libellé du repère"><button class="btn" data-rx="${k}" style="padding:2px 8px" title="Retire ce repère">✕</button></div>`).join('');
    const dessiner = () => { f.innerHTML = `<label>Le fichier sur ta clé USB — jamais hébergé (4b.1) : désigne le dossier de la clé une fois, le site retient le nom du fichier et le dossier, jamais un chemin de disque</label><div style="display:flex;gap:8px;align-items:center"><button class="btn" id="of-cle" title="Une fenêtre du navigateur : tu choisis le dossier de la clé, une fois (simulé dans la maquette)">Désigner le dossier de la clé…</button><span id="of-cle-etat" style="color:${cle ? '#1a7a3e' : '#b3261e'}">${cle ? '✔ dossier « ' + esc(cle.nom) + ' » désigné sur cet ordi portable · ' + cle.fichiers.length + ' fichiers' : 'aucun dossier désigné'}</span></div>${cle ? `<div class="fe" style="margin-top:6px">${cle.fichiers.map(x => `<span class="fi ${S._ofFichier === x.nom ? 'on' : ''}" data-f="${esc(x.nom)}" data-d="${x.duree}" style="${S._ofFichier === x.nom ? 'background:#fff2c7' : ''}">${esc(x.nom)} · ${mmss(x.duree)}</span>`).join('')}</div>` : ''}<label>La légende</label><input id="of-lg" value="${esc(b ? b.txt : (S._ofLg || ''))}" placeholder="Le Radeau de la Méduse, Géricault — extrait commenté"><label>Les repères — posés en préparation, ils rendent la vidéo dévoilable comme un bloc : ▶ lance jusqu'au repère suivant et s'arrête, ◀ revient au précédent (4b.2)</label><div class="fe" id="of-reps">${lignes()}<button class="btn" id="of-plus" style="font-size:.85rem">+ repère</button></div><div class="err" id="of-err" style="color:#6a5a48">Sans repère, la vidéo est acceptée mais signalée dans « Sur la forme » : ▶ lance / met en pause, rien ne se dévoile par étapes (4b.5).</div><div class="ok"><button class="btn or" id="of-ok">${b ? 'Enregistrer les repères' : 'Ajouter la vidéo'}</button></div>`;
      $('of-cle').onclick = () => { S.cleDossier = { nom: 'MJPC-VIDEOS', fichiers: [{ nom: 'le-radeau.mp4', duree: 245 }, { nom: 'hernani-acte1.mp4', duree: 760 }, { nom: 'lamartine-le-lac.mp4', duree: 190 }] }; journal('atelier-cle-designee', { dossier: 'MJPC-VIDEOS' }); S._ofLg = $('of-lg').value; formulaireObjet('video'); }; f.querySelectorAll('[data-f]').forEach(x => x.onclick = () => { S._ofFichier = x.dataset.f; S._ofDuree = +x.dataset.d; S._ofLg = $('of-lg').value; formulaireObjet('video'); }); const lire = () => { f.querySelectorAll('[data-rt]').forEach(i => { const k = +i.dataset.rt; const m = /^(\d+):(\d{1,2})$/.exec(i.value.trim()); reps[k].t = m ? +m[1] * 60 + +m[2] : reps[k].t; }); f.querySelectorAll('[data-rl]').forEach(i => { reps[+i.dataset.rl].l = i.value; }); }; $('of-plus').onclick = () => { lire(); reps.push({ t: reps.length ? reps[reps.length - 1].t + 60 : 0, l: '' }); S._ofLg = $('of-lg').value; dessiner(); }; f.querySelectorAll('[data-rx]').forEach(x => x.onclick = () => { lire(); reps.splice(+x.dataset.rx, 1); S._ofLg = $('of-lg').value; dessiner(); });
      $('of-ok').onclick = () => { lire(); const lg = $('of-lg').value.trim(); const propres = reps.filter(r => r.l.trim()).sort((a, b2) => a.t - b2.t); if (b) { b.reperes = propres; b.txt = lg || b.txt; S.editerVideo = null; marquerModif({ di: S.di, bi: e.blocs.indexOf(b), reperes: propres.length }); fermerChoix(); tout(); return; } if (!S.cleDossier) { $('of-err').innerHTML = '<span style="color:#b3261e">Refus : désigne d\'abord le dossier de la clé (une fois).</span>'; return; } if (!S._ofFichier) { $('of-err').innerHTML = '<span style="color:#b3261e">Refus : choisis le fichier sur la clé.</span>'; return; } if (!lg) { $('of-err').innerHTML = '<span style="color:#b3261e">Refus : une vidéo a une légende.</span>'; return; } ajouterBloc({ t: 'video', txt: lg, fichier: S._ofFichier, dossier: S.cleDossier.nom, duree: S._ofDuree || 0, reperes: propres }, false); S._ofFichier = null; S._ofLg = ''; if (!propres.length) toast('Vidéo sans repère : acceptée, signalée dans « Sur la forme » — ▶ lance / met en pause.'); }; }; dessiner(); return; }
  if (t === 'doc') { const docs = DATA.documents[String(S.si)] = DATA.documents[String(S.si)] || []; const typeDe = nom => { const ext = (nom.split('.').pop() || '').toLowerCase(); return ext === 'pdf' ? 'pdf' : ['jpg', 'jpeg', 'png', 'webp'].includes(ext) ? 'image' : ['html', 'htm'].includes(ext) ? 'html' : ext === 'docx' ? 'docx' : 'autre'; }; const CONTRAT = { pdf: 'ses pages, aux flèches', image: 'ses pages, aux flèches', html: 'ses étapes (avec contrat, 4.2)', docx: 'lu par le site (bibliothèque libre) et projeté comme des pages — si la lecture échoue, convertis-le en PDF', autre: 'non projetable tel quel : convertis-le en PDF' };
    f.innerHTML = `<label>Un document de la séance, posé dans le flux à sa place (4 ter) — ${docs.length ? 'choisis-en un déjà joint, ou joins-en un nouveau' : 'joins-en un'}</label>${docs.length ? `<div class="fe">${docs.map(d => `<span class="fi" data-doc="${esc(d.id)}" title="${esc(d.type)} · ${d.pages ? d.pages + ' pages' : (d.etapes || 0) + ' étapes'}">${esc(d.titre)} · ${esc(d.type)}</span>`).join('')}</div>` : ''}<label>Joindre un nouveau document — le nom du fichier (le type se lit dans l'extension : .pdf, .docx, .jpg, .html… tout type est accepté, le contrat dit comment il se projette)</label><input id="of-fic" placeholder="fiche-methode-decrire-une-image.pdf"><label>Le titre</label><input id="of-t" placeholder="Fiche méthode : décrire une image"><label>Pages (PDF, image, Word) ou étapes (page HTML)</label><input id="of-n" type="number" min="1" value="3" style="width:100px"><div class="err" id="of-err"></div><div class="ok"><button class="btn or" id="of-ok">Joindre et poser dans la diapo</button></div>`;
    f.querySelectorAll('[data-doc]').forEach(x => x.onclick = () => ajouterBloc({ t: 'doc', doc: x.dataset.doc, txt: (docs.find(d => d.id === x.dataset.doc) || {}).titre || '' }, false)); $('of-ok').onclick = () => { const fic = $('of-fic').value.trim(), tt = $('of-t').value.trim(), n = +$('of-n').value || 1; if (!fic || !tt) { $('of-err').textContent = 'Refus : un fichier et un titre.'; return; } const type = typeDe(fic); const d = { id: 'doc-' + Date.now().toString(36), titre: tt, fichier: fic, type, pages: type === 'html' ? undefined : n, etapes: type === 'html' ? n : undefined, contrat: type === 'html' ? true : undefined }; docs.push(d); journal('atelier-document-joint', { id: d.id, genre: type }); ajouterBloc({ t: 'doc', doc: d.id, txt: tt }, false); if (type === 'docx') toast('Document Word joint : ' + CONTRAT.docx + '.'); if (type === 'autre') toast('Document « .' + fic.split('.').pop() + ' » joint : ' + CONTRAT.autre + ' — signalé dans « Sur la forme ».'); }; return; }
  if (t === 'manque') {""")
# 3. le rendu : le bloc vidéo (déjà rendu quand il est le premier bloc) ; le bloc document dans le flux ; la page avec contrat pilotée par étapes
rep("      if (b.t === 'page') { h += `<div class=\"page-sup${marqBloc}${lumBloc}\" data-bloc=\"${bi}\"><div class=\"page-t\" data-p=\"${bi}.t\">${surligne(esc(titre), bi + '.t', et)}</div><div class=\"page-v\">page HTML — ${esc(b.src || 'sans fichier')}${b.contrat ? ' · ' + (b.etapes || '?') + ' étapes, pilotée aux flèches' : ((et.pilote || et.atelier) ? ' · <b style=\"color:#b3261e\">sans contrat de pilotage : jouée comme une image</b>' : '')}</div></div>`; h += '</div>'; return; }",
    "      if (b.t === 'page') { const etp = b.contrat ? ((et.pageEtape || {})[bi] || 1) : null; h += `<div class=\"page-sup${marqBloc}${lumBloc}\" data-bloc=\"${bi}\"><div class=\"page-t\" data-p=\"${bi}.t\">${surligne(esc(titre), bi + '.t', et)}</div><div class=\"page-v\">${b.contrat ? `<div class=\"page-cadre\">page HTML — ${esc(b.src || '')} · <b>étape ${etp} / ${b.etapes || 1}</b></div><div class=\"page-etape\">${esc(b.src || 'la page')} — étape ${etp} : ${b.contrat ? 'ce que la page montre à cette étape (dans le site : la page elle-même, chargée dans la diapo)' : ''}</div>` : `page HTML — ${esc(b.src || 'sans fichier')}${(et.pilote || et.atelier) ? ' · <b style=\"color:#b3261e\">sans contrat de pilotage : jouée comme une image</b>' : ''}`}</div></div>`; h += '</div>'; return; }\n      if (b.t === 'doc') { const d = (DATA.documents[String(S.si)] || []).find(x => x.id === b.doc); const proj = d ? (['pdf', 'image', 'html', 'docx'].includes(d.type)) : false; h += `<div class=\"doc-sup${marqBloc}${lumBloc}\" data-bloc=\"${bi}\" data-docbloc=\"${esc(b.doc || '')}\" title=\"${(et.pilote || et.atelier) ? 'Un clic ouvre le document au tableau (pages aux flèches, la croix pour revenir à la diapo)' : ''}\"><span class=\"doc-ic\">📄</span> <span class=\"doc-t\" data-p=\"${bi}.t\">${surligne(esc(titre || (d ? d.titre : 'document')), bi + '.t', et)}</span>${d ? `<span class=\"doc-i\"> · ${esc(d.type)}${d.pages ? ' · ' + d.pages + ' pages' : d.etapes ? ' · ' + d.etapes + ' étapes' : ''}${(et.pilote || et.atelier) ? (proj ? ' · <b style=\"color:#1a7a3e\">projetable</b>' : ' · <b style=\"color:#b3261e\">non projetable tel quel : convertis-le en PDF</b>') : ''}</span>` : `<span class=\"doc-i\" style=\"color:#b3261e\"> · document introuvable dans la séance</span>`}</div>`; h += '</div>'; return; }")
rep("\n.mur .ed-part{", r"""
/* (p4b) la page pilotée, le document dans le flux */
.mur .page-cadre{font-size:.6em;color:#1a7a3e;border:1px dashed #1a7a3e;border-radius:.4em;padding:.3em .6em;background:#f3fbf5}.mur .page-etape{font-size:.55em;color:#6a5a48;padding:.4em .6em;border:1px solid #d9cfbf;border-top:0;border-radius:0 0 .4em .4em;background:#fbfaf5;min-height:2.5em}
.mur .doc-sup{display:flex;align-items:baseline;gap:.4em;padding:.3em .6em;border:1px solid #d9cfbf;border-radius:.4em;background:#fbfaf5;cursor:pointer;font-size:.85em}.mur .doc-sup .doc-i{color:#6a5a48;font-size:.75em}
.mur .ed-part{""")
# 4. l'état poussé porte l'étape des pages ; ▶ / ◀ pilotent la page avec contrat (comme la vidéo) ; le clic sur un bloc document au pilote l'ouvre
rep("const etatComplet = () => { const et = etatComplet0();","const etatComplet = () => { const et = etatComplet0(); et.pageEtape = Object.assign({}, (S.pageEtape || {})[ecran().eid] || {});")
rep("  if (e.blocs[0] && e.blocs[0].t === 'video') { videoSuivant(); return; }\n  const n = elements(e).length; if (d.nDev < n) {","  if (e.blocs[0] && e.blocs[0].t === 'video') { videoSuivant(); return; }\n  { const bp = e.blocs.findIndex(b => b.t === 'page' && b.contrat); if (bp >= 0) { S.pageEtape = S.pageEtape || {}; const pe = S.pageEtape[e.eid] = S.pageEtape[e.eid] || {}; const k = pe[bp] || 1; if (k < (e.blocs[bp].etapes || 1)) { pe[bp] = k + 1; journal('page-etape', { si: S.si, di: S.di, bi: bp, etape: k + 1 }); tout(); return; } } }\n  const n = elements(e).length; if (d.nDev < n) {")
rep("const e = ecran(); if (e.blocs[0] && e.blocs[0].t === 'video') { videoPrecedent(); return; }","const e = ecran(); if (e.blocs[0] && e.blocs[0].t === 'video') { videoPrecedent(); return; } if (!S.preparation && !S.atelier && pagePrecedente()) return;")
rep("function videoSuivant(){","function pagePrecedente(){ const e = ecran(); const bp = e.blocs.findIndex(b => b.t === 'page' && b.contrat); if (bp < 0) return false; const pe = (S.pageEtape || {})[e.eid] || {}; const k = pe[bp] || 1; if (k <= 1) return false; pe[bp] = k - 1; journal('page-etape', { si: S.si, di: S.di, bi: bp, etape: k - 1 }); tout(); return true; }\nfunction videoSuivant(){")
rep("function brancherAtelier(){ const mur = $('mur'); if (!mur || !S.atelier) return;","function brancherDocs(){ const mur = $('mur'); if (!mur || S.atelier) return; mur.querySelectorAll('[data-docbloc]').forEach(x => { if (x._doc) return; x._doc = true; x.onclick = ev => { ev.stopPropagation(); const id = x.dataset.docbloc; const d = (DATA.documents[String(S.si)] || []).find(z => z.id === id); if (!d) return; if (!['pdf', 'image', 'html', 'docx'].includes(d.type)) { alert('Ce document (' + d.type + ') n\\'est pas projetable tel quel : convertis-le en PDF.'); return; } S.doc = S.doc && S.doc.id === id ? null : { id, pos: 1 }; journal(S.doc ? 'doc-ouvert' : 'doc-ferme', { id }); tout(); }; }); }\nfunction brancherAtelier(){ const mur = $('mur'); if (!mur || !S.atelier) return;")
rep("function tout(){ if (S.atelier) { observerMur();","function tout(){ setTimeout(brancherDocs, 0); if (S.atelier) { observerMur();")
# 5. les gardes dans « À régler » / « Sur la forme » : vidéo sans repère, document non projetable, Word
rep("if (b.t === 'image' && b.ref && !/mjpc-medias/.test(b.ref)) out.push(","if (b.t === 'video' && !(b.reperes || []).length) out.push({ di: i, bi, k: 'video', l: `Vidéo « ${b.txt || ''} » sans repère`, ou, faire: 'acceptée ; ▶ lance / met en pause, rien ne se dévoile par étapes — pose des repères (clic droit → Repères…) (4b.5)', copier: `Vidéo « ${b.fichier || ''} » (${ou}) : ajoute des repères (temps + libellé) dans la trame.` }); if (b.t === 'doc') { const d = (DATA.documents[String(S.si)] || []).find(x => x.id === b.doc); if (!d) out.push({ di: i, bi, k: 'doc', l: `Document introuvable dans la séance`, ou, faire: 'rejoins le document ou retire le bloc', copier: `Bloc document (${ou}) : l'identifiant « ${b.doc} » ne correspond à aucun document de la séance.` }); else if (d.type === 'autre') out.push({ di: i, bi, k: 'doc', l: `Document « ${d.titre} » (.${(d.fichier || '').split('.').pop()}) non projetable tel quel`, ou, faire: 'convertis-le en PDF (4 ter)', copier: `Document « ${d.fichier || d.titre} » (${ou}) : à convertir en PDF pour être projeté.` }); else if (d.type === 'docx') out.push({ di: i, bi, k: 'doc', l: `Document Word « ${d.titre} » — lu par le site`, ou, faire: 'si la lecture échoue en classe, convertis-le en PDF (4 ter)', copier: `Document Word « ${d.fichier || d.titre} » (${ou}) : lu par une bibliothèque libre ; en cas d'échec, PDF.` }); } if (b.t === 'image' && b.ref && !/mjpc-medias/.test(b.ref)) out.push(")
# 6. clic droit sur un bloc vidéo → « Repères… »
rep("...(b.t === 'fiche' ? [{ a: 'b-lier', l: b.feuille ? 'Changer la fiche liée…' : 'Lier à une fiche…', t: 'la fiche vit dans une feuille du chapitre (1.7)' }] : []),","...(b.t === 'fiche' ? [{ a: 'b-lier', l: b.feuille ? 'Changer la fiche liée…' : 'Lier à une fiche…', t: 'la fiche vit dans une feuille du chapitre (1.7)' }] : []), ...(b.t === 'video' ? [{ a: 'b-reperes', l: 'Repères…', t: 'les repères rendent la vidéo dévoilable comme un bloc (4b.2)' }] : []),")
rep("if (act === 'b-lier') { S.lierFiche = bi; choixObjet('fiche'); }","if (act === 'b-lier') { S.lierFiche = bi; choixObjet('fiche'); } if (act === 'b-reperes') { S.editerVideo = bi; choixObjet('video'); }")
# 7. la barre : « + vidéo… » active ; un bouton « + document… »
rep('<button class="btn" disabled title="Ajoute une vidéo (à venir : p4)">+ vidéo…</button>','<button class="btn" id="at-video" title="Une vidéo de ta clé USB, avec ses repères — jamais hébergée">+ vidéo…</button><button class="btn" id="at-doc" title="Un document de la séance (PDF, Word, image, page HTML — tout type) posé dans le flux de la diapo">+ document…</button>')
rep("const af = $('at-fiche'); if (af && !af._ok) { af._ok = true; af.onclick = () => choixObjet('fiche'); }","const af = $('at-fiche'); if (af && !af._ok) { af._ok = true; af.onclick = () => choixObjet('fiche'); } const av = $('at-video'); if (av && !av._ok) { av._ok = true; av.onclick = () => { S.editerVideo = null; choixObjet('video'); }; } const ad = $('at-doc'); if (ad && !ad._ok) { ad._ok = true; ad.onclick = () => choixObjet('doc'); }")
# la croix du document au pilote (retour à la diapo, 4t.2)
rep("  else if (et.doc) { h += `<span class=\"act\">${esc(actLib)}</span>` + docHtml(et.doc); }","  else if (et.doc) { h += `<span class=\"act\">${esc(actLib)}</span>` + docHtml(et.doc) + (et.pilote ? `<button class=\"doc-x\" data-docx=\"1\" title=\"Ferme le document : retour à la diapo (le journal note le départ)\">✕ retour à la diapo</button>` : ''); }")
rep("function brancherDocs(){ const mur = $('mur'); if (!mur || S.atelier) return;","function brancherDocs(){ const mur = $('mur'); if (!mur || S.atelier) return; const dx = mur.querySelector('[data-docx]'); if (dx && !dx._ok) { dx._ok = true; dx.onclick = ev => { ev.stopPropagation(); const id = S.doc && S.doc.id; S.doc = null; journal('doc-ferme', { id }); tout(); }; }")
rep("\n.mur .ed-part{", r"""
.mur .doc-x{position:absolute;right:.6em;top:.5em;font:inherit;font-size:.5em;padding:.3em .8em;border:1px solid #c99a4e;border-radius:.5em;background:#fbfaf5;color:#1c1712;cursor:pointer;z-index:6}
.mur .ed-part{""")
# le tableau garde une copie de la trame prise à son ouverture : le pilotage lui envoie la diapo avec l'état, la fenêtre la remplace avant de rendre (une modification en préparation vaut pour la classe qui n'a pas encore vu, cadrage 4 · 8.2)
rep("S.mur = et; if (fenetreMur && !fenetreMur.closed) { try { fenetreMur.postMessage({ et }, '*'); } catch (e) {} }","S.mur = et; if (fenetreMur && !fenetreMur.closed) { try { fenetreMur.postMessage({ et, ecran: DATA.seances[et.si].ecrans[et.di], documents: DATA.documents[String(et.si)] || [] }, '*'); } catch (e) {} }")
rep('if(ev.data&&ev.data.et){ev.data.et.pilote=false;const m=document.getElementById("mur2");','if(ev.data&&ev.data.et){if(ev.data.ecran){DATA.seances[ev.data.et.si].ecrans[ev.data.et.di]=ev.data.ecran;}if(ev.data.documents){DATA.documents=DATA.documents||{};DATA.documents[String(ev.data.et.si)]=ev.data.documents;}ev.data.et.pilote=false;const m=document.getElementById("mur2");')
rep("· v9c.15 p4a — <b>provisoire</b> : l'atelier (p4b à p6 à venir) <span","· v9c.15 p4b — <b>provisoire</b> : l'atelier (p5, p6 à venir) <span")
open(p,'w',encoding='utf-8').write(s); print("(p4b) écrit")
