p='vis/v9c15p6-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (p6) « Jouer en avance — répétition » : le même écran que le pilotage, le tableau reçoit, rien n'est écrit, aucune garde, aucun gel (cadrage 4 · 1.5, 1 · 2.5) ; les alertes « trop pleine » et « fichier non atteignable »
rep("\n.mur .ed-part{", r"""
/* (p6) jouer en avance — répétition */
.rep-bandeau{position:fixed;left:0;right:0;top:0;height:6px;background:repeating-linear-gradient(90deg,#c99a4e 0 24px,#1c1712 24px 32px);z-index:99}.rep-etat{position:fixed;top:10px;left:50%;transform:translateX(-50%);background:#2a2114;border:1px solid var(--or);color:#e8dcc4;border-radius:8px;padding:5px 12px;font-size:.9rem;z-index:99;display:flex;gap:12px;align-items:center;white-space:nowrap}.rep-etat b{color:var(--or)}.rep-etat .btn{padding:3px 10px}
.mur .ed-part{""")
# le bouton de l'atelier : « ▶ Jouer en avance — répétition »
rep('<button class="btn or" id="at-jouer" title="Jouer en avance : le même écran que le pilotage, la fenêtre du tableau possible — rien n\'est écrit (ni journal, ni copie), aucune garde, aucun gel">▶ Jouer en avance</button>','<button class="btn or" id="at-jouer" title="Jouer en avance — répétition : le même écran que le pilotage, la fenêtre du tableau possible, rien n\'est écrit (ni journal, ni copie, ni cours actif), aucune garde, aucun gel ; ce qui est dévoilé en répétition est oublié à l\'arrêt">▶ Jouer en avance — répétition</button>')
rep("aj.onclick = () => { journal('atelier-jouer-en-avance', { di: S.di }); voir('pilotage'); };","aj.onclick = () => { journal('atelier-jouer-en-avance', { di: S.di }); lancerRepetition(); };")
rep("function blocDe(el){", r"""/* ── (p6) la répétition ── */
function lancerRepetition(){ if (S.repetition) return; const clone = x => JSON.parse(JSON.stringify(x)); S.repSnap = { S: clone(Object.fromEntries(Object.entries(S).filter(([k, v]) => !k.startsWith('_') && k !== 'repSnap' && typeof v !== 'function'))), vuMax: clone(vuMax), parDiapo: clone(parDiapo), Jlen: J.length, di: S.di }; S.repetition = true; S.repT0 = Date.now(); S.atelier = false; document.body.classList.remove('vue-atelier'); $('ong-atelier').classList.remove('on'); voir('pilotage'); document.body.insertAdjacentHTML('beforeend', `<div class="rep-bandeau" id="rep-bandeau"></div><div class="rep-etat" id="rep-etat"><b>JOUER EN AVANCE — RÉPÉTITION</b><span>rien n'est écrit · aucune garde, aucun gel</span><span id="rep-chrono" title="Le chrono de la répétition, depuis son lancement — l'heure réelle ne bouge pas">00:00</span><span id="rep-ou"></span><button class="btn or" id="rep-stop" title="Retour à l'atelier sur cette diapo ; tout ce qui a été dévoilé en répétition est oublié">■ Arrêter</button></div>`); $('rep-stop').onclick = arreterRepetition; S._repTick = setInterval(() => { const s2 = Math.round((Date.now() - S.repT0) / 1000); const c = $('rep-chrono'); if (c) c.textContent = String(Math.floor(s2 / 60)).padStart(2, '0') + ':' + String(s2 % 60).padStart(2, '0'); const o = $('rep-ou'); if (o) { const e = ecran(); const d = etatDiapo(); o.textContent = '· diapo ' + (rangDe(S.di, e.heure) || '?') + ', dévoilée ' + d.nDev + ' / ' + elements(e).length; } }, 500); tout(); }
function arreterRepetition(){ if (!S.repetition) return; clearInterval(S._repTick); const snap = S.repSnap; const di = S.di; Object.keys(S).forEach(k => { if (!k.startsWith('_')) delete S[k]; }); Object.assign(S, snap.S); Object.keys(vuMax).forEach(k => delete vuMax[k]); Object.assign(vuMax, snap.vuMax); Object.keys(parDiapo).forEach(k => delete parDiapo[k]); Object.assign(parDiapo, snap.parDiapo); J.length = snap.Jlen; S.repetition = false; delete S.repSnap; S.di = di; ['rep-bandeau', 'rep-etat'].forEach(id => { const x = $(id); if (x) x.remove(); }); if (fenetreMur && !fenetreMur.closed) { try { fenetreMur.postMessage({ et: null, sortie: true }, '*'); } catch (e) {} } voir('atelier'); }
function blocDe(el){""")
# rien n'est écrit : le journal se tait (sauf ses propres marques) ; pousser envoie au tableau sans journal ni vuMax ; les gardes passent ; le gel est inactif ; le T-5 ne s'ouvre pas
rep("const journal = (type, x) => { if (S.atelier && !/^atelier/.test(type)) return;","const journal = (type, x) => { if (S.atelier && !/^atelier/.test(type)) return; if (S.repetition && !/^repetition/.test(type)) return; /* (p6) rien n'est écrit en répétition */")
rep("function pousser(et){ if (S.atelier) return; /* (p1) l'atelier ne pousse rien au tableau, n'écrit rien au journal, ne marque rien comme vu (cadrage 4, 1.5) */","function pousser(et){ if (S.atelier) return; /* (p1) l'atelier ne pousse rien au tableau, n'écrit rien au journal, ne marque rien comme vu (cadrage 4, 1.5) */ if (S.repetition) { /* (p6) la répétition : le tableau reçoit, rien n'est écrit (ni journal, ni vu) */ S.mur = et; if (fenetreMur && !fenetreMur.closed) { try { fenetreMur.postMessage({ et, ecran: DATA.seances[et.si].ecrans[et.di], documents: DATA.documents[String(et.si)] || [] }, '*'); } catch (e) {} } return; }")
rep("function garde(faire, quoi){ if (S.gel) return faire();","function garde(faire, quoi){ if (S.gel || S.repetition) return faire(); /* (p6) aucune garde en répétition */")
rep("function gel(){ if (S.preparation) {","function gel(){ if (S.repetition) { toast('Jouer en avance — répétition : aucun gel, rien n\\'est écrit.'); return; } if (S.preparation) {")
# l'atelier : ouvrir depuis l'EDT ne lance pas ; l'onglet Atelier pendant la répétition l'arrête
rep("$('ong-atelier').onclick = () => voir('atelier');","$('ong-atelier').onclick = () => { if (S.repetition) arreterRepetition(); else voir('atelier'); };")
# le T-5 et le cahier : pas en répétition
rep("function palier(","function palier0(")
rep("function blocDe(el){","function palier(...a){ if (S.repetition) return; /* (p6) pas de T-5 en répétition */ return palier0(...a); }\nfunction blocDe(el){")
# les alertes « trop pleine » (mesurée sur la diapo ouverte dans l'atelier) et « fichier non atteignable » (vidéo)
rep("E.forEach((e, i) => { if (!e.role && !actDe(e)) out.push({ di: i, k: 'activite',","E.forEach((e, i) => (e.blocs || []).forEach((b, bi) => { if (b.t === 'video' && b.fichier) { const cle = S.cleDossier; const ok = cle && cle.fichiers.some(f => f.nom === b.fichier); if (!ok) out.push({ di: i, bi, k: 'video-fichier', l: `Vidéo « ${b.txt || b.fichier} » : fichier non atteignable — « ${b.fichier} » ${cle ? 'n\\'est pas dans le dossier « ' + cle.nom + ' » désigné' : 'et aucun dossier de clé n\\'est désigné'}`, ou: `diapo ${i + 1} · « ${e.act} » · bloc ${bi + 1}`, faire: 'remets le fichier sur la clé, ou redésigne le dossier (« + vidéo… » → Désigner le dossier de la clé…) ; en classe, la diapo passerait toute seule et le récit dirait « qu\\'on regardera à la prochaine séance » (4b.4)', copier: `Vidéo « ${b.fichier} » (${e.act}) : fichier absent du dossier de la clé.` }); } })); if (S.atelier && !S.repetition) { const c = document.querySelector('#mur .corpsd'); const pages = S.pagesCourantes ? S.pagesCourantes.length : 1; if ((c && !c.classList.contains('plein-img') && c.scrollHeight > c.clientHeight + 2) || pages > 1) { const e = E[S.di]; const px = policePx ? Math.round(policePx()) : 0; out.push({ di: S.di, k: 'pleine', l: `Diapo trop pleine : le texte passe sous le plancher lisible du fond${px ? ' (' + px + ' px de police)' : ''}`, ou: `diapo ${S.di + 1} · « ${e.act} »`, faire: 'coupe la diapo : clic droit sur le bloc ou l\\'étape où couper → « Couper la diapo ici » (une seconde diapo « (suite) », même heure, mêmes notions) ; ou retire un bloc ; ou mets-en un en « petit ». Le site ne coupe jamais seul (0.4)', copier: `Diapo « ${e.act} » : trop pleine pour le tableau, à couper en deux.` }); } } E.forEach((e, i) => { if (!e.role && !actDe(e)) out.push({ di: i, k: 'activite',")
rep("function volet(){ if (S.atelier) return;","function volet(){ if (S.atelier) return; const v0 = $('volet'); if (v0 && v0.dataset.atelier) delete v0.dataset.atelier; /* (p6) le volet du pilotage a repris la place : la colonne de l'atelier se réécrira */")
rep("const da = $('droite-atelier'); if (da) { const hd = droiteAtelier(); if (da.innerHTML !== hd) { da.innerHTML = hd; const ax = da.querySelector('#at-aide .x'); if (ax) ax.onclick = () => { S.aideFermee = true; tout(); }; const ar = da.querySelector('#at-regler'); if (ar) ar.onclick = ouvrirARegler; brancherDeclare(da); } }","rendreDroiteAtelier();")
rep("function blocDe(el){","function rendreDroiteAtelier(){ const da = $('droite-atelier'); if (!da || !S.atelier) return; const hd = droiteAtelier(); if (da.innerHTML !== hd) { da.innerHTML = hd; const ax = da.querySelector('#at-aide .x'); if (ax) ax.onclick = () => { S.aideFermee = true; tout(); }; const ar = da.querySelector('#at-regler'); if (ar) ar.onclick = ouvrirARegler; brancherDeclare(da); } }\nfunction blocDe(el){")
rep("atObs = new MutationObserver(() => { if (S.atelier) brancherAtelier(); });","atObs = new MutationObserver(() => { if (S.atelier) { brancherAtelier(); clearTimeout(S._atDroite); S._atDroite = setTimeout(rendreDroiteAtelier, 60); /* (p6) la mesure « trop pleine » se fait sur la diapo rendue */ } });")

# ── (p6 bis, Paul 29/09 : « lourd, fouillis » ; « si je dois faire quelque chose, le site me le dira ») : la colonne sobre
rep("\n.mur .ed-part{", r"""
/* (p6 bis) la colonne sobre */
.at-d .lire{line-height:1.5}.at-d .lire b{color:var(--texte)}.at-d .modif{float:right;font-size:.8rem;color:var(--or);cursor:pointer;text-decoration:underline dotted;font-weight:400;letter-spacing:0}.at-d.pli h5{cursor:pointer;margin-bottom:0}.at-d.pli h5::before{content:"▸ ";color:var(--sourd)}.at-d.pli .l,.at-d.pli .act-l{display:none}.at-d h5[data-pli]{cursor:pointer}.at-d .corr{color:#ff8a8e;font-size:.85rem;margin-bottom:4px}
.mur .ed-part{""")
rep(" : `<div class=\"at-d\"><h5>CE QUE LA DIAPO DÉCLARE — tout s'écrit ici</h5>", " : (!(S.declareOuverte && S.declareEid === e.eid) ? `<div class=\"at-d\"><h5>CE QUE LA DIAPO DÉCLARE <span class=\"modif\" data-declare=\"ouvrir\" title=\"Ouvre les champs : activité, titre, durée, rôle, heure prévue, notions, légende — tu n'y vas que si « À régler » te le demande ou si quelque chose est faux\">modifier</span></h5><div class=\"l lire\">${a ? '<b>A' + a.num + ' · ' + esc(a.titre) + '</b> — diapo ' + rang + ' sur ' + dA.length + ' de l\\'activité' : '<b style=\"color:#ff8a8e\">hors activité</b> — sans numéro : le chapitre est refusé à l\\'import (3.2 bis)'}${e.role ? ' · rituel : <b>' + (e.role === 'reactivation' ? 'réactivation' : e.role) + '</b>' : ''}<br>Heure prévue : <b>H${e.heure}</b>${sim ? ' (' + esc(sim.jour.replace(/ 2026$/, '')) + ')' : ''} · ${hhmm(cr.debut)} → ${hhmm(cr.fin)} · ${e.dur || 0} min<br>Notions travaillées : ${(e.comp || []).length ? (e.comp || []).map(n => '<b>' + esc(libNotion(n)) + '</b>').join(', ') : '<i>aucune</i>'}<br>Remobilise : ${(e.remob || []).length ? (e.remob || []).map(n => '<b>' + esc(libNotion(n)) + '</b>').join(', ') : 'rien'}${e.legende ? '<br>Surlignage : ' + esc(Object.keys(e.legende).map(k => k + ' = ' + e.legende[k]).join(' · ')) : ''}</div></div>` : `<div class=\"at-d\"><h5>CE QUE LA DIAPO DÉCLARE <span class=\"modif\" data-declare=\"fermer\" title=\"Referme les champs\">fermer</span></h5>${S.declareLigne ? `<div class=\"corr\">⚠ À corriger ici : ${esc(S.declareLigne)}</div>` : ''}")
rep("Éléments : ${nEl}${nEl > 1 ? ' · dévoilés un par un' : ''}</div></div>`;", "Éléments : ${nEl}${nEl > 1 ? ' · dévoilés un par un' : ''}</div></div>`);")
rep("<div class=\"at-d\"><h5>L'HEURE ${e.heure} — le travail à faire prévu (2.3)</h5>", "<div class=\"at-d${(S.plis || {}).tp === false ? '' : ' pli'}\"><h5 data-pli=\"tp\" title=\"Un clic pour ouvrir ou replier\">L'HEURE ${e.heure} — le travail à faire prévu</h5>")
rep("<div class=\"at-d\"><h5>LES ACTIVITÉS DU CHAPITRE</h5>", "<div class=\"at-d${(S.plis || {}).acts === false ? '' : ' pli'}\"><h5 data-pli=\"acts\" title=\"Un clic pour ouvrir ou replier\">LES ACTIVITÉS DU CHAPITRE (${acts0.length})</h5>")
rep("function brancherDeclare(da){ const e = ecran(); if (!e) return;", "function brancherDeclare(da){ const e = ecran(); if (!e) return; da.querySelectorAll('[data-declare]').forEach(b => b.onclick = () => { if (b.dataset.declare === 'ouvrir') { S.declareOuverte = true; S.declareEid = e.eid; } else { S.declareOuverte = false; S.declareLigne = null; } tout(); }); da.querySelectorAll('[data-pli]').forEach(h => h.onclick = () => { S.plis = S.plis || {}; const k = h.dataset.pli; S.plis[k] = S.plis[k] === false ? true : false; tout(); });")
rep("z.querySelectorAll('[data-ouvrir]').forEach(b => b.onclick = () => { S.di = +b.dataset.ouvrir; S.page = null; fermerChoix(); tout(); });", "z.querySelectorAll('[data-ouvrir]').forEach(b => b.onclick = () => { S.di = +b.dataset.ouvrir; S.page = null; const a = al.find(x => x.di === S.di && x.k === b.dataset.k) || al.find(x => x.di === S.di); if (a && a.k === 'activite') { S.declareOuverte = true; S.declareEid = seance().ecrans[S.di].eid; S.declareLigne = 'l\\'activité — rattache la diapo à une activité numérotée'; } fermerChoix(); tout(); });")
rep("<button class=\"btn\" data-ouvrir=\"${a.di}\" style=\"font-size:.8rem;margin-top:4px\">Ouvrir la diapo</button>", "<button class=\"btn\" data-ouvrir=\"${a.di}\" data-k=\"${a.k}\" style=\"font-size:.8rem;margin-top:4px\">Ouvrir la diapo</button>")
rep("<div class=\"at-regler\"><button id=\"at-regler\" title=\"La liste complète de ce qui peut casser en classe dans ce chapitre, avec la marche à suivre et le texte prêt à copier pour l'instance (6.1)\">À régler (${alertesForme().length})</button></div>", "<div class=\"at-regler\"><button id=\"at-regler\" title=\"La liste complète de ce qui peut casser en classe dans ce chapitre, avec la marche à suivre et le texte prêt à copier pour l'instance (6.1)\">À régler (${alertesForme().length})</button> <span class=\"at-note\">— la seule liste de ce que tu as à faire ; chaque ligne dit le geste</span></div>")

rep("· v9c.15 p5 — <b>provisoire</b> : l'atelier (p6 à venir) <span","· v9c.15 p6 — la maquette de la préparation complète <span")
open(p,'w',encoding='utf-8').write(s); print("(p6) écrit")
