p='vis/v9c15p7-template.html'; s=open(p,encoding='utf-8').read()
def rep(a, b, n=1):
    global s
    if a not in s: raise SystemExit('ABSENT : ' + a[:90])
    s = s.replace(a, b, n)
# ── (p7) les cinq formes du schéma dessinées depuis la source texte existante (une ligne par élément), dévoilées ligne par ligne ; l'écran d'envoi vers une autre séance
rep("\n.mur .ed-part{", r"""
/* (p7) le schéma dessiné */
.mur .bloc:has(> .sch){flex:1 1 0;min-height:0;display:flex;flex-direction:column}.mur .sch-dessin{flex:1;min-height:0;display:flex;align-items:center;justify-content:center;overflow:hidden}.mur .sch-dessin svg{font-family:inherit;height:100%;width:auto;max-width:100%;max-height:100%;aspect-ratio:16/9}.mur .sch-dessin table{max-height:100%}.mur .sch svg .el.pas{opacity:.3}.tableau .sch svg .el.pas{display:none}.mur .sch table{width:100%;border-collapse:collapse;font-size:.6em}.mur .sch th,.mur .sch td{border:1px solid #c99a4e;padding:.15em .5em;text-align:left}.mur .sch th{background:#fff2c7}.mur .sch tr.el.pas{opacity:.3}.tableau .sch tr.el.pas{display:none}.mur .sch .sch-src{font-size:.45em;color:#8a7a66}
.mur .ed-part{""")
# la simulation : le schéma « Les figures de style » reçoit une source carte (une ligne par branche)
rep("const $ = id => document.getElementById(id);","/* (p7) le schéma simulé reçoit sa source (le format existant : forme + src texte, une ligne par élément) ; la séance jouée reçoit un schéma sur « Les mouvements du siècle » */ (function(){ const E = DATA.seances[0].ecrans; const m = E.find(e => e.act === 'Les mouvements du siècle'); if (m && !(m.blocs || []).some(b => b.t === 'schema')) m.blocs = (m.blocs || []).concat([{ t: 'schema', bid: 'b-sim-schema', txt: 'Les figures de style', forme: 'carte' }]); })(); DATA.seances.forEach(se => se.ecrans.forEach(e => (e.blocs || []).forEach(b => { if (b.t === 'schema' && !b.src) { b.forme = b.forme || 'carte'; b.src = \"Figures d'analogie : comparaison, métaphore\\nFigures d'opposition : antithèse, oxymore\\nFigures d'insistance : anaphore, hyperbole\"; } if (b.t === 'schema' && b.src && !(b.el || []).length) b.el = b.src.split('\\n').map(x => x.trim()).filter(Boolean); })));\nconst $ = id => document.getElementById(id);",1)
# le rendu : chaque ligne de la source est un élément (k), dessiné selon la forme
rep("else if (b.t === 'schema') { h += `<div class=\"sch${marqBloc}${lumBloc}\" data-bloc=\"${bi}\"><div class=\"sch-t\" data-p=\"${bi}.t\">${esc(titre)}</div><div class=\"img-sup\" style=\"flex:1\"><div class=\"img-vide\">schéma — ${esc(titre)}</div></div></div>`; }",
    "else if (b.t === 'schema') { const lignes = (b.el && b.el.length ? b.el : String(b.src || '').split('\\n').map(x => x.trim()).filter(Boolean)); const k0 = k; const cl = i2 => (k0 + i2 >= et.nDev ? 'el pas' : 'el') + (et.flash === k0 + i2 ? ' spot-on' : ''); h += `<div class=\"sch${marqBloc}${lumBloc}\" data-bloc=\"${bi}\"><div class=\"sch-t\" data-p=\"${bi}.t\">${esc(titre)}</div><div class=\"sch-dessin\">${dessinerSchema(b.forme || 'carte', titre, lignes, cl)}</div></div>`; k += lignes.length; }")
rep("function blocDe(el){", r"""/* ── (p7) les cinq formes, dessinées depuis la source texte (contrat existant : forme + src, une ligne par élément) ── */
function dessinerSchema(forme, titre, lignes, cl){ const E = esc; const n = lignes.length; const W = 640, H = 360;
  if (forme === 'frise') { const jal = lignes.map(l => { const m = /^(.+?)\s*[=:—-]\s*(.+)$/.exec(l); return m ? { d: m[1].trim(), t: m[2].trim() } : { d: '', t: l }; }); const x = i2 => 40 + (n > 1 ? i2 * (W - 80) / (n - 1) : (W - 80) / 2); return `<svg viewBox="0 0 ${W} ${H}"><line x1="20" y1="${H / 2}" x2="${W - 20}" y2="${H / 2}" stroke="#c99a4e" stroke-width="3"/>${jal.map((j, i2) => `<g class="${cl(i2)}" data-k="${i2}"><circle cx="${x(i2)}" cy="${H / 2}" r="9" fill="#c99a4e"/><text x="${x(i2)}" y="${H / 2 - 22}" text-anchor="middle" font-size="22" font-weight="700">${E(j.d)}</text><text x="${x(i2)}" y="${H / 2 + 40}" text-anchor="middle" font-size="18">${E(j.t)}</text></g>`).join('')}</svg>`; }
  if (forme === 'cycle') { const cx = W / 2, cy = H / 2, R = 120; return `<svg viewBox="0 0 ${W} ${H}"><circle cx="${cx}" cy="${cy}" r="${R}" fill="none" stroke="#c99a4e" stroke-dasharray="8 6" stroke-width="2"/>${lignes.map((l, i2) => { const a = -Math.PI / 2 + i2 * 2 * Math.PI / n; const x = cx + R * Math.cos(a), y = cy + R * Math.sin(a); return `<g class="${cl(i2)}" data-k="${i2}"><circle cx="${x}" cy="${y}" r="38" fill="#fff2c7" stroke="#c99a4e" stroke-width="2"/><text x="${x}" y="${y + 6}" text-anchor="middle" font-size="16">${E(l.length > 14 ? l.slice(0, 13) + '…' : l)}</text></g>`; }).join('')}</svg>`; }
  if (forme === 'tableau') { const rows = lignes.map(l => l.split('|').map(x => x.trim())); if (!rows.length) return ''; return `<table><thead><tr class="${cl(0)}" data-k="0">${rows[0].map(c => `<th>${E(c)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map((r, i2) => `<tr class="${cl(i2 + 1)}" data-k="${i2 + 1}">${r.map(c => `<td>${E(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
  if (forme === 'arbre') { const noeuds = lignes.map(l => { const m = /^(\s*)(.*)$/.exec(l); return { niv: Math.floor(m[1].replace(/\t/g, '  ').length / 2), t: m[2].trim() }; }); const maxNiv = Math.max(0, ...noeuds.map(x => x.niv)); const parNiv = {}; noeuds.forEach((x, i2) => { (parNiv[x.niv] = parNiv[x.niv] || []).push(i2); }); const pos = noeuds.map((x, i2) => { const ligne = parNiv[x.niv]; const j = ligne.indexOf(i2); return { x: (j + 1) * W / (ligne.length + 1), y: 40 + x.niv * (H - 80) / Math.max(1, maxNiv) }; }); const parent = noeuds.map((x, i2) => { for (let q = i2 - 1; q >= 0; q--) if (noeuds[q].niv < x.niv) return q; return -1; }); return `<svg viewBox="0 0 ${W} ${H}">${noeuds.map((x, i2) => `<g class="${cl(i2)}" data-k="${i2}">${parent[i2] >= 0 ? `<line x1="${pos[parent[i2]].x}" y1="${pos[parent[i2]].y + 16}" x2="${pos[i2].x}" y2="${pos[i2].y - 16}" stroke="#c99a4e" stroke-width="2"/>` : ''}<rect x="${pos[i2].x - 70}" y="${pos[i2].y - 16}" width="140" height="32" rx="6" fill="${x.niv === 0 ? '#fff2c7' : '#fff'}" stroke="#c99a4e" stroke-width="2"/><text x="${pos[i2].x}" y="${pos[i2].y + 6}" text-anchor="middle" font-size="15">${E(x.t.length > 18 ? x.t.slice(0, 17) + '…' : x.t)}</text></g>`).join('')}</svg>`; }
  /* carte (mentale), la forme par défaut : le titre au centre, une ligne « Branche : a, b » par branche */ const cx = W / 2, cy = H / 2; const br = lignes.map(l => { const m = /^(.+?)\s*:\s*(.*)$/.exec(l); return m ? { t: m[1].trim(), sous: m[2].split(',').map(x => x.trim()).filter(Boolean) } : { t: l, sous: [] }; }); return `<svg viewBox="0 0 ${W} ${H}"><ellipse cx="${cx}" cy="${cy}" rx="110" ry="34" fill="#fff2c7" stroke="#c99a4e" stroke-width="2"/><text x="${cx}" y="${cy + 6}" text-anchor="middle" font-size="18" font-weight="700">${E(titre.length > 22 ? titre.slice(0, 21) + '…' : titre)}</text>${br.map((b, i2) => { const a = Math.PI + (i2 + 0.5) * Math.PI / Math.max(1, n / 2) * (i2 < n / 2 ? 1 : 1); const ang = -Math.PI / 2 + (i2 + 0.5) * 2 * Math.PI / n; const x = cx + 240 * Math.cos(ang), y = cy + 140 * Math.sin(ang); return `<g class="${cl(i2)}" data-k="${i2}"><line x1="${cx + 100 * Math.cos(ang)}" y1="${cy + 30 * Math.sin(ang)}" x2="${x}" y2="${y}" stroke="#c99a4e" stroke-width="2"/><text x="${x}" y="${y}" text-anchor="middle" font-size="17" font-weight="700">${E(b.t)}</text>${b.sous.map((sx, q) => `<text x="${x}" y="${y + 20 + q * 18}" text-anchor="middle" font-size="14">${E(sx)}</text>`).join('')}</g>`; }).join('')}</svg>`; }
function blocDe(el){""")
# le formulaire « Schéma… » de l'atelier : la forme, le titre, la source (une ligne par élément) avec la convention de la forme
rep("if (t === 'schema') { f.innerHTML = `<label>La forme du schéma — chacune avec le format de sa source ; échelle « plein » par défaut ; se dévoile élément par élément</label><select id=\"of-forme\"><option value=\"carte\">carte</option><option value=\"frise\">frise</option><option value=\"arbre\">arbre</option><option value=\"cycle\">cycle</option><option value=\"tableau\">tableau</option></select><label>Le titre</label><input id=\"of-t\" placeholder=\"Les figures de style\"><div class=\"err\" id=\"of-err\"></div><div class=\"ok\"><button class=\"btn or\" id=\"of-ok\">Ajouter le schéma</button></div>`; $('of-ok').onclick = () => { const tt = $('of-t').value.trim(); if (!tt) { $('of-err').textContent = 'Refus : un schéma a un titre.'; return; } ajouterBloc({ t: 'schema', txt: tt, forme: $('of-forme').value, echelle: 'plein', el: [] }, false); }; return; }",
    "if (t === 'schema') { const CONV = { carte: 'une ligne par branche : « Branche : a, b » — le titre au centre', frise: 'une ligne par repère : « date = événement »', arbre: 'une ligne par nœud ; deux espaces devant pour descendre d\\'un niveau', cycle: 'une étape par ligne, dans le sens des aiguilles', tableau: 'une ligne par rangée, les colonnes séparées par « | » ; la première ligne = les en-têtes' }; f.innerHTML = `<label>La forme du schéma — le format existant : une source texte, une ligne par élément ; échelle « plein » par défaut ; se dévoile ligne par ligne</label><select id=\"of-forme\"><option value=\"carte\">carte</option><option value=\"frise\">frise</option><option value=\"arbre\">arbre</option><option value=\"cycle\">cycle</option><option value=\"tableau\">tableau</option></select> <span class=\"at-note\" id=\"of-conv\">${CONV.carte}</span><label>Le titre</label><input id=\"of-t\" placeholder=\"Les figures de style\"><label>La source — une ligne par élément</label><textarea id=\"of-src\" rows=\"4\" style=\"width:100%;font:inherit;border:1px solid #c99a4e;border-radius:6px;padding:5px 8px;box-sizing:border-box\" placeholder=\"Figures d'analogie : comparaison, métaphore\"></textarea><div class=\"err\" id=\"of-err\"></div><div class=\"ok\"><button class=\"btn or\" id=\"of-ok\">Ajouter le schéma</button></div>`; $('of-forme').onchange = () => { $('of-conv').textContent = CONV[$('of-forme').value]; }; $('of-ok').onclick = () => { const tt = $('of-t').value.trim(); const src = $('of-src').value.replace(/\\r/g, ''); const lignes = src.split('\\n').map(x => x.replace(/\\s+$/, '')).filter(x => x.trim()); if (!tt) { $('of-err').textContent = 'Refus : un schéma a un titre.'; return; } if (!lignes.length) { $('of-err').textContent = 'Refus : un schéma a au moins un élément (une ligne).'; return; } ajouterBloc({ t: 'schema', txt: tt, forme: $('of-forme').value, echelle: 'plein', src: lignes.join('\\n'), el: lignes.map(x => x.trim()) }, false); }; return; }")
# l'écran d'envoi vers une autre séance : les séances, leurs heures et le compte à l'arrivée
rep("function envoyerVersSeance(i){ const E = seance().ecrans; const e = E[i]; if (DATA.seances.length < 2) return alert('Une seule séance dans le chapitre : rien où envoyer.'); const choix = DATA.seances.map((sc, k) => k === S.si ? null : (k + 1) + ' · ' + (sc.titre || 'séance ' + (k + 1))).filter(Boolean); const rep = prompt('Envoyer « ' + e.act + ' » vers quelle séance ? Tape son numéro :\\n' + choix.join('\\n')); if (!rep) return; const k = parseInt(rep, 10) - 1; if (!(k >= 0 && k < DATA.seances.length) || k === S.si) return alert('Numéro inconnu.'); const cible = DATA.seances[k]; const heures = [...new Set(cible.ecrans.map(z => z.heure))].sort(); const hFin = heures[heures.length - 1] || 1; /* identité inchangée ; à l'arrivée : la dernière heure de la séance cible, avant sa fin d'heure (et avant le bilan) */ E.splice(i, 1); e.heure = hFin; delete e.actId; let pos = cible.ecrans.length; for (let q = cible.ecrans.length - 1; q >= 0; q--) { if (cible.ecrans[q].role === 'fin' || cible.ecrans[q].role === 'bilan') pos = q; else break; } cible.ecrans.splice(pos, 0, e); apresTrame({ envoye: e.eid, vers: k, heure: hFin }); S.di = Math.min(i, E.length - 1); toast('Diapo envoyée vers la séance ' + (k + 1) + ' (H' + hFin + ') — identité inchangée, heure recalculée à l\\'arrivée.'); tout(); }",
    "function envoyerVersSeance(i){ const E = seance().ecrans; const e = E[i]; if (DATA.seances.length < 2) return alert('Une seule séance dans le chapitre : rien où envoyer.'); fermerChoix(); const z = document.createElement('div'); z.className = 'choix-obj'; const dur = e.dur || 0; const compte = (sc, h) => sc.ecrans.filter(x => x.heure === h && x.role !== 'fin').reduce((t, x) => t + (x.dur || 0), 0); const oH = ordreHeure(e.heure); const resteIci = oH.filter(q => q !== i && E[q].role !== 'fin').reduce((t, q) => t + (E[q].dur || 0), 0); z.innerHTML = `<h4><span>ENVOYER « ${esc(e.act)} » VERS UNE AUTRE SÉANCE — identité inchangée, heure recalculée à l'arrivée</span><span class=\"x\">✕</span></h4><div class=\"form\">${DATA.seances.map((sc, k) => { if (k === S.si) return ''; const heures = [...new Set(sc.ecrans.map(x => x.heure))].sort((a, b) => a - b); return `<div class=\"fe\"><b>Séance ${k + 1} — ${esc(sc.titre || '')}</b> · ${heures.length} heure${heures.length > 1 ? 's' : ''}<br>${heures.map(h => { const c = compte(sc, h) + dur + 5; return `<span class=\"fi\" data-si=\"${k}\" data-h=\"${h}\" style=\"${c <= 50 ? 'background:#fff7e0' : ''}\" title=\"La diapo arrive avant la fin d'heure de H${h} ; ses notions et ses réponses d'élèves la suivent\">à la fin de H${h} · ${compte(sc, h)} + ${dur} + 5 = ${c} min${c > 50 ? ' +' + (c - 50) : ' ✔'}</span>`; }).join('')}</div>`; }).join('')}<div class=\"err\" style=\"color:#6a5a48\">Ici, elle sort du compte : l'heure ${e.heure} revient à ${resteIci} + 5 = ${resteIci + 5} min${resteIci + 5 > 50 ? ' +' + (resteIci + 5 - 50) : ' ✔'}.</div></div>`; document.querySelector('.scene').appendChild(z); z.querySelector('.x').onclick = fermerChoix; z.querySelectorAll('[data-si]').forEach(b => b.onclick = () => { const k = +b.dataset.si, h = +b.dataset.h; const cible = DATA.seances[k]; E.splice(i, 1); const anc = e.heure; e.heure = h; delete e.actId; let pos = cible.ecrans.length; for (let q = cible.ecrans.length - 1; q >= 0; q--) { if (cible.ecrans[q].heure === h && cible.ecrans[q].role !== 'fin' && cible.ecrans[q].role !== 'bilan') { pos = q + 1; break; } if (cible.ecrans[q].heure === h && cible.ecrans[q].role === 'fin') pos = q; } cible.ecrans.splice(pos, 0, e); fermerChoix(); apresTrame({ envoye: e.eid, vers: k, heure: h, de: anc }); S.di = Math.min(i, E.length - 1); toast('Diapo envoyée vers la séance ' + (k + 1) + ', à la fin de H' + h + ' — identité inchangée.'); tout(); }); }")
rep("const fns = { esc, elements, rendre, docHtml, videoHtml, paginer, pageDeSuivi, appliquerPages, loupeSur, morph, poserHtml, policePx, surligne, numDe, actDe };","const fns = { esc, elements, rendre, docHtml, videoHtml, paginer, pageDeSuivi, appliquerPages, loupeSur, morph, poserHtml, policePx, surligne, numDe, actDe, dessinerSchema /* (p7) le tableau dessine aussi */ };")
# « trop dense » : le schéma de la diapo ouverte n'a pas la place (le dessin fait moins de la moitié du corps) → « À régler »
rep("if (S.atelier && !S.repetition) { const c = document.querySelector('#mur .corpsd');","if (S.atelier && !S.repetition) { const c0 = document.querySelector('#mur .corpsd'); const svgs = document.querySelectorAll('#mur .sch-dessin svg, #mur .sch-dessin table'); if (c0 && svgs.length) svgs.forEach(sv => { const h = sv.getBoundingClientRect().height; if (h < c0.clientHeight * 0.45) { const bi = +sv.closest('[data-bloc]').dataset.bloc; const e = E[S.di]; out.push({ di: S.di, bi, k: 'dense', l: `Schéma « ${(e.blocs[bi] || {}).txt || ''} » trop dense : il n\\'a pas la place (moins de la moitié de la diapo)`, ou: `diapo ${S.di + 1} · « ${e.act} » · bloc ${bi + 1}`, faire: 'donne-lui sa diapo : clic droit sur le bloc → « Couper la diapo ici » (échelle « plein » : un schéma remplit sa diapo, 3.2)', copier: `Schéma « ${(e.blocs[bi] || {}).txt || ''} » (${e.act}) : à mettre seul sur sa diapo.` }); } }); const c = document.querySelector('#mur .corpsd');")
rep("· v9c.15 p6 — la maquette de la préparation complète <span","· v9c.15 p7 — la maquette de la préparation complète <span")
open(p,'w',encoding='utf-8').write(s); print("(p7) écrit")
