import { chromium, CHROMIUM, MAQUETTE, capture } from './env.mjs';
const nav = await chromium.launch({ executablePath: CHROMIUM, args: ['--no-sandbox','--allow-file-access-from-files'], headless: true });
const ctx = await nav.newContext({ viewport: { width: 1536, height: 864 } }); const page = await ctx.newPage(); const errs = []; page.on('pageerror', e => { errs.push(e.message); console.log('ERREUR JS :', e.message, (e.stack||'').split('\n')[1]); }); const dialogs = []; page.on('dialog', d => { dialogs.push(d.message()); if (d.type() === 'prompt') d.accept('Le concours de la classe'); else d.accept(); });
const D = []; const p = ms => page.waitForTimeout(ms); const ok = (c, m) => { if (!c) D.push(m); }; const ev = (f, a) => page.evaluate(f, a);
await page.goto(MAQUETTE); await p(600); await page.click('#edt-cases [data-atelier="1"]'); await p(500); await ev(() => { S.aideFermee = true; tout(); }); await page.click('#volet .at-chap .d[data-at-di="6"]'); await p(300);
const T = () => ev(() => document.getElementById('droite-atelier').textContent);

ok(await ev(() => !document.querySelector('#dc-act') && /A1 · Analyse d'images/.test(document.getElementById('droite-atelier').textContent) && /Heure prévue : H1/.test(document.getElementById('droite-atelier').textContent)), 'la carte n\'est pas en lecture par défaut'); await page.click('#droite-atelier [data-declare="ouvrir"]'); await p(300); ok(await ev(() => !!document.querySelector('#dc-act') && /fermer/.test(document.getElementById('droite-atelier').textContent)), '« modifier » n\'ouvre pas les champs'); await page.click('#droite-atelier [data-pli="tp"]'); await p(200); await page.click('#droite-atelier [data-pli="acts"]'); await p(300); ok(await ev(() => !!document.querySelector('#dc-tp') && document.querySelectorAll('#droite-atelier .act-l').length >= 3), 'les cartes repliées ne s\'ouvrent pas d\'un clic');
// 1. la carte s'écrit : l'activité de la diapo 7 (A1), le titre, la durée, le rôle, l'heure, les notions, la légende, le travail prévu, les activités du chapitre
const c0 = await T(); ok(/CE QUE LA DIAPO DÉCLARE/.test(c0) && (await ev(() => document.querySelector('#dc-act').value === actDe(ecran()).id)) && /L'HEURE 1 — le travail à faire prévu/.test(c0) && /LES ACTIVITÉS DU CHAPITRE/.test(c0) && /A1/.test(c0), 'la carte éditable manque une part : ' + c0.slice(0, 200));
// le titre de la diapo
await page.click('#dc-titre'); await page.keyboard.press('End'); await page.keyboard.type(' — v2'); await page.keyboard.press('Enter'); await p(300); ok(await ev(() => ecran().act === 'Les hypothèses de la classe — v2' && /Les hypothèses de la classe — v2/.test(document.getElementById('numero').textContent) && /Les hypot/.test(document.querySelector('#volet .at-chap .d.on').textContent)), 'le titre de la diapo ne s\'écrit pas dans la trame, le numéro et la colonne');
// la durée : la colonne et le compte de l'heure suivent
const dep0 = await ev(() => document.querySelector('#volet .at-chap .fr .plus') ? document.querySelector('#volet .at-chap .fr .plus').textContent : '✔'); await page.fill('#dc-dur', '12'); await page.keyboard.press('Tab'); await p(300); ok(await ev(() => ecran().dur === 12 && /12 min/.test(document.querySelector('#volet .at-chap .d.on').textContent)), 'la durée ne s\'écrit pas'); ok((await ev(() => document.querySelector('#volet .at-chap .fr .plus') ? document.querySelector('#volet .at-chap .fr .plus').textContent : '✔')) !== dep0, 'le compte de l\'heure ne suit pas la durée : ' + dep0);
// le titre de l'activité
await page.click('#dc-atitre'); await page.keyboard.press('End'); await page.keyboard.type(' (cinq)'); await page.keyboard.press('Enter'); await p(300); const ta = await ev(() => ({ titre: actDe(ecran()).titre, di: S.di, act: ecran().act, actif: document.activeElement.id, carte: (document.getElementById('droite-atelier').textContent.match(/Titre de l'activité : [^·]*/) || [''])[0] })); ok(ta.titre === "Analyse d'images : les cinq tableaux (cinq)", 'le titre de l\'activité ne s\'écrit pas : ' + JSON.stringify(ta));
// le rôle : bilan refusé (unique), réactivation refusée si pas première, puis retour à aucun
await page.selectOption('#dc-role', 'bilan'); await p(300); ok(dialogs.some(m => /bilan est unique/.test(m)) && (await ev(() => !ecran().role)), 'un second bilan n\'est pas refusé');
await page.selectOption('#dc-role', 'reactivation'); await p(300); ok(dialogs.some(m => /première de son heure/.test(m)) && (await ev(() => !ecran().role)), 'une réactivation ailleurs qu\'en tête de l\'heure n\'est pas refusée');
// les notions : retirer, ajouter par le chapitre, remobilise + proposer
const nComp = await ev(() => (ecran().comp || []).length); await page.click('#droite-atelier [data-retire="comp"]'); await p(300); ok(await ev(n => (ecran().comp || []).length === n - 1, nComp), 'retirer une notion travaillée ne marche pas');
await page.click('#droite-atelier [data-plus="comp"]'); await p(300); ok(await ev(() => !!document.querySelector('.choix-obj') && document.querySelectorAll('.choix-obj [data-n]').length >= 3), 'le choix de notion ne s\'ouvre pas sur les notions du chapitre'); await page.click('.choix-obj [data-n="litt-036"]'); await p(300); ok(await ev(() => (ecran().comp || []).includes('litt-036') && !document.querySelector('.choix-obj')), 'ajouter une notion travaillée ne marche pas');
await page.click('#droite-atelier [data-proposer]'); await p(300); ok(await ev(() => (ecran().remob || []).length >= 1 && J.some(x => x.type === 'atelier-modif' && x.remob)), 'la proposition par défaut de « remobilise » ne propose rien : ' + (await ev(() => JSON.stringify(ecran().remob))));
// la légende
await page.click('#dc-leg'); await page.keyboard.type('jaune = ce qu\'on voit · vert = ce qu\'on ressent'); await page.keyboard.press('Enter'); await p(300); ok(await ev(() => ecran().legende && ecran().legende.jaune === "ce qu'on voit" && ecran().legende.vert === 'ce qu\'on ressent' && /legsur/.test(document.getElementById('mur').innerHTML)), 'la légende ne s\'écrit pas (ou ne se rend pas)');
// le travail à faire prévu de l'heure 1
await page.click('#dc-tp'); await page.keyboard.press('Control+a'); await page.keyboard.type('Relire ses notes sur les cinq tableaux.'); await page.keyboard.press('Enter'); await p(300); ok(await ev(() => DATA.travailPrevu['0|1'] === 'Relire ses notes sur les cinq tableaux.'), 'le travail à faire prévu ne s\'écrit pas');
// 2. passer en H2 : la diapo va en tête de H2, le compte des deux heures se recalcule ; ↑ revient
const avant2 = await ev(() => ({ heure: ecran().heure, di: S.di, act: ecran().act, boutons: Array.from(document.querySelectorAll('#droite-atelier [data-heure]')).map(b => b.dataset.heure), onclick: !!document.querySelector('#droite-atelier [data-heure="2"]').onclick, carte: document.getElementById('droite-atelier').textContent.slice(0, 120) })); ok(avant2.boutons.includes('2') && avant2.onclick, 'le bouton « passer en H2 » n\'a pas de geste branché : ' + JSON.stringify(avant2)); ok(avant2.boutons.includes('2'), 'avant « passer en H2 », le bouton manque : ' + JSON.stringify(avant2)); if (avant2.boutons.includes('2')) await ev(() => document.querySelector('#droite-atelier [data-heure="2"]').click()); await p(500); const apres2 = await ev(() => ({ heure: ecran().heure, di: S.di, boutons: Array.from(document.querySelectorAll('#droite-atelier [data-heure]')).map(b => b.dataset.heure) })); ok(apres2.heure === 2 && apres2.boutons.includes('1'), 'après « passer en H2 », la carte n\'offre pas le retour en H1 : ' + JSON.stringify(apres2)); ok(await ev(() => ecran().heure === 2 && ecran().act === 'Les hypothèses de la classe — v2' && ordreHeure(2)[0] === S.di || (seance().ecrans[ordreHeure(2)[0]].role === 'reactivation' && ordreHeure(2)[1] === S.di)), 'passer en H2 ne met pas la diapo en tête de H2 : ' + (await ev(() => JSON.stringify([ecran().heure, S.di, ordreHeure(2).slice(0, 3)]))));
const etat1 = await ev(() => { const b = document.querySelector('#droite-atelier [data-heure="1"]'); const info = { heure: ecran().heure, di: S.di, act: ecran().act, boutons: Array.from(document.querySelectorAll('#droite-atelier [data-heure]')).map(x => x.dataset.heure), carte: document.getElementById('droite-atelier').textContent.slice(0, 160) }; if (b) b.click(); return info; }); await p(500); ok(etat1.boutons.includes('1') && (await ev(() => ecran().heure === 1 && seance().ecrans[S.di + 1].role === 'fin')), 'revenir en H1 ne met pas la diapo juste avant la fin d\'heure 1 : ' + JSON.stringify(etat1));
// 3. nouvelle activité par le select : la diapo y est rattachée, numérotée à la suite ; « + activité » ; renuméroter ; une diapo sans activité → refus dans « À régler »
const nA0 = await ev(() => (DATA.activites[String(S.si)] || []).length); await page.selectOption('#dc-act', '+'); await p(500); const na = await ev(([nA0]) => { const acts = DATA.activites[String(S.si)]; const a = actDe(ecran()); return { n: acts.length, nA0, titre: a && a.titre, num: a && a.num, rattachee: a && diaposAct(a).includes(S.di), di: S.di, act: ecran().act, dialogs: 0 }; }, [nA0]); ok(na.n === nA0 + 1 && na.titre === 'Le concours de la classe' && na.num === 11 && na.rattachee, '« + nouvelle activité » ne crée pas l\'activité et n\'y rattache pas la diapo : ' + JSON.stringify(na) + ' dialogs=' + JSON.stringify(dialogs.slice(-2)));
await page.selectOption('#dc-act', ''); await p(400); ok(await ev(() => !actDe(ecran()) && /sans numéro d'activité : refus à l'import/.test(document.getElementById('droite-atelier').textContent) && alertesForme().some(a => a.k === 'activite')), 'une diapo hors activité n\'est pas signalée « sans numéro » et refusée');
await page.selectOption('#dc-act', (await ev(() => DATA.activites[String(S.si)][0].id))); await p(400); ok(await ev(() => actDe(ecran()) && actDe(ecran()).num === 1), 'rattacher la diapo à A1 ne marche pas');
await page.click('#droite-atelier [data-renum]'); await p(400); ok(await ev(() => { const nums = (DATA.activites[String(S.si)] || []).map(a => a.num).sort((x, y) => x - y); return nums.every((n, k) => n === k + 1); }), 'renuméroter laisse un trou');
// 4. la fin d'heure : la carte dit son rôle et rien ne s'écrit ; le pilotage lit tout (titre, durée, notions)
await page.click('#volet .at-chap .d[data-at-di="6"]'); await p(300); ok(await ev(() => !document.querySelector('#dc-act') && /modifier/.test(document.getElementById('droite-atelier').textContent)), 'sur une autre diapo, la carte n\'est pas revenue en lecture'); await page.click('#volet .at-chap .d[data-at-di="8"]'); await p(300); ok(await ev(() => /Fin d'heure — posée par le site/.test(document.getElementById('droite-atelier').textContent) && !document.querySelector('#dc-act')), 'la fin d\'heure a une carte éditable');
await page.click('#ong-pilotage'); await p(300); ok(await ev(() => seance().ecrans.some(e => e.act === 'Les hypothèses de la classe — v2')), 'le pilotage ne lit pas la trame modifiée');
if (errs.length) D.push('erreurs JS : ' + JSON.stringify(errs)); console.log(D.length ? D.join('\n') : 'aucun défaut'); console.log('--- fin :', D.length, 'défaut(s)'); await nav.close();
